import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const BED_VEGETABLE_OVERRIDES: Record<string, PlantCareProfile> = {
  // ── New Vegetable Bed Plants ────────────────────────────────────────────
  [buildProfileKey('vegetable', 'Lettuce')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 7,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Lactuca sativa',
    taxonomicFamily: 'Asteraceae',
    lifecycle: 'annual',
    tamilName: 'லெட்டுஸ்',
    description: 'Cool-season leafy green ideal for salads and fresh garnishes',
    daysToHarvest: { min: 30, max: 60 },
    heightCm: { min: 15, max: 35 },
    spacingCm: 25,
    plantingDepthCm: 0.5,
    growingSeason: 'Cool Dry (Oct–Feb)',
    germinationDays: { min: 3, max: 7 },
    germinationTempC: { min: 15, max: 22 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 10, vegetative: 25, mature: 15 },
  },
  [buildProfileKey('vegetable', 'Purslane')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Portulaca oleracea',
    taxonomicFamily: 'Portulacaceae',
    lifecycle: 'annual',
    tamilName: 'பொட்டுக்கீரை',
    description: 'Succulent edible weed rich in omega-3 fatty acids; drought-tolerant ground cover',
    daysToHarvest: { min: 20, max: 35 },
    heightCm: { min: 10, max: 25 },
    spacingCm: 15,
    plantingDepthCm: 0.5,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 20, max: 35 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 7, vegetative: 15, mature: 8 },
  },
  [buildProfileKey('vegetable', 'Pasalai Keerai')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Basella alba',
    taxonomicFamily: 'Basellaceae',
    lifecycle: 'perennial',
    tamilName: 'பசளைக்கீரை',
    description: 'Malabar spinach — vigorous climbing leafy green thriving in Tamil Nadu heat',
    daysToHarvest: { min: 20, max: 35 },
    heightCm: { min: 30, max: 300 },
    spacingCm: 15,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 10, vegetative: 20, mature: 10 },
  },
  [buildProfileKey('vegetable', 'Fenugreek')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 14,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Trigonella foenum-graecum',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'annual',
    tamilName: 'வெந்தயம்',
    description: 'Aromatic annual legume grown for its iron-rich leaves and distinctive seeds',
    daysToHarvest: { min: 25, max: 35 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 10,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 3, max: 5 },
    germinationTempC: { min: 18, max: 28 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 7, vegetative: 13, mature: 8 },
  },
  [buildProfileKey('vegetable', 'Ladies Finger')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Abelmoschus esculentus',
    taxonomicFamily: 'Malvaceae',
    lifecycle: 'annual',
    tamilName: 'வெண்டைக்காய்',
    description: 'Heat-loving mucilaginous pod vegetable essential in South Indian cooking',
    daysToHarvest: { min: 50, max: 70 },
    heightCm: { min: 90, max: 180 },
    spacingCm: 45,
    plantingDepthCm: 2,
    growingSeason: 'Summer (Mar–May)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 6.8 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 14, vegetative: 18, flowering: 10, fruiting: 15 },
  },
  [buildProfileKey('vegetable', 'Moringa')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Moringa oleifera',
    taxonomicFamily: 'Moringaceae',
    lifecycle: 'perennial',
    tamilName: 'முருங்கை',
    description: 'Multipurpose tropical tree with nutrient-dense leaves, pods, and flowers',
    daysToHarvest: { min: 90, max: 120 },
    heightCm: { min: 300, max: 1000 },
    spacingCm: 300,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 60, flowering: 30, fruiting: 60 },
  },
  [buildProfileKey('vegetable', 'Squash')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Cucurbita pepo',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'annual',
    tamilName: 'ஸ்குவாஷ்',
    description:
      'Fast-growing cucurbit producing tender fruits; ideal ground cover in polycultures',
    daysToHarvest: { min: 50, max: 70 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 90,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 14, vegetative: 20, flowering: 10, fruiting: 18 },
  },
  [buildProfileKey('vegetable', 'Yardlong Beans')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Vigna unguiculata subsp. sesquipedalis',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'annual',
    tamilName: 'தட்டப்பயறு',
    description: 'Vigorous climbing legume producing metre-long tender pods; fixes nitrogen',
    daysToHarvest: { min: 55, max: 70 },
    heightCm: { min: 200, max: 400 },
    spacingCm: 30,
    plantingDepthCm: 2,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 12, vegetative: 20, flowering: 10, fruiting: 20 },
  },
  [buildProfileKey('vegetable', 'Beetroot')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Beta vulgaris',
    taxonomicFamily: 'Amaranthaceae',
    lifecycle: 'annual',
    tamilName: 'பீட்ரூட்',
    description: 'Jewel-red root vegetable with earthy sweetness, rich in folate and iron',
    daysToHarvest: { min: 55, max: 70 },
    heightCm: { min: 20, max: 40 },
    spacingCm: 10,
    plantingDepthCm: 1,
    growingSeason: 'Cool Dry (Oct–Feb)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 14, vegetative: 28, mature: 14 },
  },
  [buildProfileKey('vegetable', 'French Beans')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Phaseolus vulgaris',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'annual',
    tamilName: 'பிரெஞ்சு பீன்ஸ்',
    description: 'Bushy or climbing legume producing tender flat pods for stir-fries and curries',
    daysToHarvest: { min: 45, max: 60 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 25,
    plantingDepthCm: 3,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 18, max: 28 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 12, vegetative: 18, flowering: 8, fruiting: 15 },
  },
  [buildProfileKey('vegetable', 'Cluster Beans')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Cyamopsis tetragonoloba',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'annual',
    tamilName: 'கொத்தவரை',
    description: 'Heat-tolerant legume yielding slender pods and nitrogen-fixing roots',
    daysToHarvest: { min: 45, max: 65 },
    heightCm: { min: 60, max: 120 },
    spacingCm: 20,
    plantingDepthCm: 2,
    growingSeason: 'Summer (Mar–May)',
    germinationDays: { min: 4, max: 8 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 7.0, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 10, vegetative: 20, flowering: 10, fruiting: 15 },
  },
  [buildProfileKey('vegetable', 'Black Gram')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Vigna mungo',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'annual',
    tamilName: 'உளுந்து',
    description: 'Essential South Indian pulse crop yielding protein-rich seeds for idli and dosa',
    daysToHarvest: { min: 60, max: 75 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 20,
    plantingDepthCm: 2,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 3, max: 6 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 10, vegetative: 25, flowering: 10, fruiting: 20 },
  },
  [buildProfileKey('vegetable', 'Groundnut')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Arachis hypogaea',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'annual',
    tamilName: 'வேர்க்கடலை',
    description:
      'Nitrogen-fixing oilseed legume producing underground pods rich in protein and fat',
    daysToHarvest: { min: 100, max: 130 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 25,
    plantingDepthCm: 5,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 25, max: 32 },
    soilPhRange: { min: 5.9, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 15, vegetative: 40, flowering: 20, fruiting: 40 },
  },
  [buildProfileKey('vegetable', 'Pigeon Pea')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Cajanus cajan',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'perennial',
    tamilName: 'தொவரம்பருப்பு',
    description: 'Perennial legume producing protein-rich toor dal; a staple of Tamil cuisine',
    daysToHarvest: { min: 140, max: 180 },
    heightCm: { min: 100, max: 200 },
    spacingCm: 45,
    plantingDepthCm: 3,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 20, vegetative: 80, flowering: 20, fruiting: 40 },
  },
  [buildProfileKey('vegetable', 'Yam')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 45,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Dioscorea alata',
    taxonomicFamily: 'Dioscoreaceae',
    lifecycle: 'annual',
    tamilName: 'கிழங்கு',
    description:
      'Starchy tropical vine tuber with thick bark; distinct from elephant yam in texture',
    daysToHarvest: { min: 180, max: 240 },
    heightCm: { min: 50, max: 200 },
    spacingCm: 90,
    plantingDepthCm: 15,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 25, max: 32 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 30, vegetative: 150, mature: 60 },
  },
  [buildProfileKey('vegetable', 'Maize')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Zea mays',
    taxonomicFamily: 'Poaceae',
    lifecycle: 'annual',
    tamilName: 'மக்காச்சோளம்',
    description: 'Tall cereal grass forming the structural canopy in Three Sisters polyculture',
    daysToHarvest: { min: 75, max: 95 },
    heightCm: { min: 150, max: 300 },
    spacingCm: 45,
    plantingDepthCm: 3,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 20, max: 35 },
    soilPhRange: { min: 5.8, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 14, vegetative: 30, flowering: 14, fruiting: 25 },
  },
  [buildProfileKey('vegetable', 'Lotus Stem')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'alluvial',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Nelumbo nucifera',
    taxonomicFamily: 'Nelumbonaceae',
    lifecycle: 'perennial',
    tamilName: 'தாமரைத்தண்டு',
    description:
      'Aquatic perennial with crunchy, tunnel-riddled rhizomes used in South Indian cooking',
    daysToHarvest: { min: 110, max: 140 },
    heightCm: { min: 80, max: 150 },
    spacingCm: 60,
    plantingDepthCm: 20,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 20, vegetative: 80, flowering: 20, mature: 30 },
  },
  [buildProfileKey('vegetable', 'Strawberry')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Fragaria × ananassa',
    taxonomicFamily: 'Rosaceae',
    lifecycle: 'perennial',
    tamilName: 'ஸ்ட்ராபெர்ரி',
    description: 'Low-growing fruiting plant producing sweet red berries; companion to spinach',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 15, max: 30 },
    spacingCm: 30,
    plantingDepthCm: 2,
    growingSeason: 'Cool Dry (Oct–Feb)',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 15, max: 22 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 21, vegetative: 30, flowering: 14, fruiting: 25 },
  },

};
