import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const FLOWER_OVERRIDES: Record<string, PlantCareProfile> = {
  // ── Flowers (10) ─────────────────────────────────────────────────────────
  [buildProfileKey('flower', 'Marigold')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'seedling',
    scientificName: 'Tagetes erecta',
    taxonomicFamily: 'Asteraceae',
    lifecycle: 'annual',
    tamilName: 'செண்டுமல்லி',
    description:
      'Bright orange-yellow blooms that repel nematodes and attract pollinators. Excellent companion plant for vegetables; deadhead spent flowers to promote continuous blooming.',
    daysToHarvest: { min: 45, max: 60 },
    heightCm: { min: 30, max: 90 },
    spacingCm: 30,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 7 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 12, vegetative: 25, flowering: 18 },
  },
  [buildProfileKey('flower', 'Jasmine')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'neem_cake',
    initialGrowthStage: 'vegetative',
    scientificName: 'Jasminum sambac',
    taxonomicFamily: 'Oleaceae',
    lifecycle: 'perennial',
    tamilName: 'மல்லிகை',
    description:
      'Intensely fragrant evergreen shrub whose white flowers are integral to Tamil culture. Prune after each flush to shape the bush and stimulate the next bloom cycle.',
    daysToHarvest: { min: 180, max: 365 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 120,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 25, max: 30 },
    soilPhRange: { min: 6.0, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 45, vegetative: 180, flowering: 140 },
  },
  [buildProfileKey('flower', 'Hibiscus')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Hibiscus rosa-sinensis',
    taxonomicFamily: 'Malvaceae',
    lifecycle: 'perennial',
    tamilName: 'செம்பருத்தி',
    description:
      'Showy tropical shrub producing large colourful blooms used in hair oil and temple offerings. Feed fortnightly for non-stop flowering; tip-prune to maintain compact shape.',
    daysToHarvest: { min: 90, max: 180 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 120,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 25, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 30, vegetative: 90, flowering: 60 },
  },
  [buildProfileKey('flower', 'Rose')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'neem_cake',
    initialGrowthStage: 'vegetative',
    scientificName: 'Rosa × indica',
    taxonomicFamily: 'Rosaceae',
    lifecycle: 'perennial',
    tamilName: 'ரோஜா',
    description:
      'Classic garden shrub grown for fragrant blooms. In Kanyakumari, prune hard after monsoon and apply neem cake to control mildew and aphids. Needs rich, well-drained soil.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 60, max: 200 },
    spacingCm: 60,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 20, max: 25 },
    soilPhRange: { min: 6.0, max: 6.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 30, vegetative: 60, flowering: 45 },
  },
  [buildProfileKey('flower', 'Chrysanthemum')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Chrysanthemum indicum',
    taxonomicFamily: 'Asteraceae',
    lifecycle: 'annual',
    tamilName: 'சாமந்தி',
    description:
      "Popular festival flower grown for bright disc-shaped blooms. Pinch tips twice before flowering to encourage branching. Best performance in Kanyakumari's cool, dry season.",
    daysToHarvest: { min: 90, max: 120 },
    heightCm: { min: 30, max: 90 },
    spacingCm: 30,
    plantingDepthCm: 2,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 10, max: 18 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 14, vegetative: 45, flowering: 30 },
  },
  [buildProfileKey('flower', 'Crossandra')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 60,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Crossandra infundibuliformis',
    taxonomicFamily: 'Acanthaceae',
    lifecycle: 'perennial',
    tamilName: 'கனகாம்பரம்',
    description:
      'Low-growing perennial bearing vibrant orange flowers used for garlands and hair adornment. Prefers morning sun with afternoon shade; keep soil evenly moist but not soggy.',
    daysToHarvest: { min: 120, max: 180 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 30,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 25, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 90, flowering: 60 },
  },
  [buildProfileKey('flower', 'Ixora')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Ixora coccinea',
    taxonomicFamily: 'Rubiaceae',
    lifecycle: 'perennial',
    tamilName: 'வெட்சி',
    description:
      'Evergreen tropical shrub with dense clusters of tiny tubular flowers. Prefers acidic soil; use neem cake or peat to lower pH. Minimal pruning needed once shape is established.',
    daysToHarvest: { min: 180, max: 365 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 90,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 21, max: 30 },
    germinationTempC: { min: 25, max: 30 },
    soilPhRange: { min: 5.0, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 45, vegetative: 120, flowering: 75 },
  },
  [buildProfileKey('flower', 'Sunflower')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Helianthus annuus',
    taxonomicFamily: 'Asteraceae',
    lifecycle: 'annual',
    tamilName: 'சூரியகாந்தி',
    description:
      'Tall, cheerful annual grown for its large composite flower heads that track the sun. Direct-sow in place; stake tall varieties against coastal wind. Seeds are edible and oil-rich.',
    daysToHarvest: { min: 60, max: 80 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 45,
    plantingDepthCm: 2.5,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 10 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 10, vegetative: 30, flowering: 35 },
  },
  [buildProfileKey('flower', 'Dahlia')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Dahlia pinnata',
    taxonomicFamily: 'Asteraceae',
    lifecycle: 'perennial',
    tamilName: 'டேலியா',
    description:
      'Tuberous perennial producing spectacular multi-petalled blooms in every colour except blue. Plant tubers eye-up in well-drained mix; deadhead and disbud for larger flowers.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 30, max: 150 },
    spacingCm: 45,
    plantingDepthCm: 10,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 21, vegetative: 45, flowering: 25 },
  },
  [buildProfileKey('flower', 'Orchid')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 14,
    sunlight: 'partial_sun',
    soilType: 'coco_peat',
    preferredFertiliser: 'seaweed',
    initialGrowthStage: 'vegetative',
    scientificName: 'Dendrobium spp.',
    taxonomicFamily: 'Orchidaceae',
    lifecycle: 'perennial',
    tamilName: 'ஆர்க்கிட்',
    description:
      'Exotic epiphytic perennial grown for elegant long-lasting blooms. Mount on bark or pot in coarse coco-peat with charcoal; never let roots sit in water. Mist daily in dry weather.',
    daysToHarvest: { min: 365, max: 730 },
    heightCm: { min: 30, max: 90 },
    spacingCm: 20,
    plantingDepthCm: 0,
    growingSeason: 'Year Round',
    germinationDays: { min: 30, max: 90 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 60, vegetative: 180, flowering: 125 },
  },
};
