import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const FRUIT_TREE_OVERRIDES: Record<string, PlantCareProfile> = {
  // ── Fruit Trees (23) ─────────────────────────────────────────────────
  [buildProfileKey('fruit_tree', 'Banana')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Musa × paradisiaca',
    taxonomicFamily: 'Musaceae',
    lifecycle: 'perennial',
    tamilName: 'வாழை',
    description:
      "Fast-growing tropical fruit producing large bunches rich in potassium. Thrives in Kanyakumari's warm, humid climate with consistent moisture and organic feeding.",
    daysToHarvest: { min: 270, max: 365 },
    yearsToFirstHarvest: 1,
    heightCm: { min: 200, max: 500 },
    spacingCm: 300,
    plantingDepthCm: 15,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 45, vegetative: 140, flowering: 30, fruiting: 90 },
  },
  [buildProfileKey('fruit_tree', 'Mango')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Mangifera indica',
    taxonomicFamily: 'Anacardiaceae',
    lifecycle: 'perennial',
    tamilName: 'மாம்பழம்',
    description:
      'King of fruits — long-lived tropical tree bearing sweet, aromatic drupes. Grafted saplings fruit in 3–5 years; withhold water before flowering for better yields in Kanyakumari.',
    daysToHarvest: { min: 90, max: 150 },
    yearsToFirstHarvest: 5,
    heightCm: { min: 300, max: 1500 },
    spacingCm: 800,
    plantingDepthCm: 20,
    growingSeason: 'Mar–Jul',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 24, max: 35 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 180, vegetative: 1645 },
    annualCycleDurations: { flowering: 45, fruiting: 120, dormant: 200 },
    floweringStartMonth: 12,
  },
  [buildProfileKey('fruit_tree', 'Guava')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Psidium guajava',
    taxonomicFamily: 'Myrtaceae',
    lifecycle: 'perennial',
    tamilName: 'கொய்யா',
    description:
      "Hardy tropical tree producing vitamin-C-rich fruits year-round. Adapts to most soils; tip-prune regularly to encourage continuous fruiting in Kanyakumari's warm climate.",
    daysToHarvest: { min: 90, max: 150 },
    yearsToFirstHarvest: 3,
    heightCm: { min: 300, max: 800 },
    spacingCm: 500,
    plantingDepthCm: 15,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 120, vegetative: 975 },
    annualCycleDurations: { flowering: 45, fruiting: 180, dormant: 140 },
    floweringStartMonth: 2,
  },
  [buildProfileKey('fruit_tree', 'Papaya')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Carica papaya',
    taxonomicFamily: 'Caricaceae',
    lifecycle: 'perennial',
    tamilName: 'பப்பாளி',
    description:
      'Fast-growing single-trunk tree bearing melon-like fruits rich in papain enzyme. Needs excellent drainage; produces fruit within 9–12 months from seed in Kanyakumari.',
    daysToHarvest: { min: 150, max: 270 },
    yearsToFirstHarvest: 1,
    heightCm: { min: 200, max: 600 },
    spacingCm: 250,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 60, vegetative: 305 },
    annualCycleDurations: { flowering: 60, fruiting: 240, dormant: 65 },
    floweringStartMonth: 1,
  },
  [buildProfileKey('fruit_tree', 'Lemon')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'neem_cake',
    initialGrowthStage: 'vegetative',
    scientificName: 'Citrus × limon',
    taxonomicFamily: 'Rutaceae',
    lifecycle: 'perennial',
    tamilName: 'எலுமிச்சை',
    description:
      'Evergreen citrus tree producing tangy fruits year-round in tropical climates. Grafted plants fruit in 2–3 years; responds well to neem cake and micronutrient sprays in Kanyakumari.',
    daysToHarvest: { min: 120, max: 180 },
    yearsToFirstHarvest: 3,
    heightCm: { min: 200, max: 500 },
    spacingCm: 400,
    plantingDepthCm: 15,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 32 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 120, vegetative: 975 },
    annualCycleDurations: { flowering: 30, fruiting: 150, dormant: 185 },
    floweringStartMonth: 2,
  },
  [buildProfileKey('fruit_tree', 'Pomegranate')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Punica granatum',
    taxonomicFamily: 'Lythraceae',
    lifecycle: 'perennial',
    tamilName: 'மாதுளை',
    description:
      'Drought-tolerant shrubby tree producing antioxidant-rich fruits. Train to 3–4 main stems; select one bahar season for concentrated fruiting in Kanyakumari.',
    daysToHarvest: { min: 120, max: 180 },
    yearsToFirstHarvest: 3,
    heightCm: { min: 200, max: 500 },
    spacingCm: 400,
    plantingDepthCm: 15,
    growingSeason: 'Jun–Nov',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.2 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 120, vegetative: 975 },
    annualCycleDurations: { flowering: 30, fruiting: 120, dormant: 215 },
    floweringStartMonth: 6,
  },
  [buildProfileKey('fruit_tree', 'Jackfruit')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Artocarpus heterophyllus',
    taxonomicFamily: 'Moraceae',
    lifecycle: 'perennial',
    tamilName: 'பலாப்பழம்',
    description:
      "Massive tropical tree producing the world's largest tree-borne fruit. Low-maintenance once established; fruits directly on trunk and branches in Kanyakumari's humid climate.",
    daysToHarvest: { min: 90, max: 180 },
    yearsToFirstHarvest: 5,
    heightCm: { min: 500, max: 2000 },
    spacingCm: 1000,
    plantingDepthCm: 20,
    growingSeason: 'Mar–Sep',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 180, vegetative: 1645 },
    annualCycleDurations: { flowering: 60, fruiting: 120, dormant: 185 },
    floweringStartMonth: 12,
  },
  [buildProfileKey('fruit_tree', 'Chikoo')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Manilkara zapota',
    taxonomicFamily: 'Sapotaceae',
    lifecycle: 'perennial',
    tamilName: 'சப்போட்டா',
    description:
      "Evergreen tropical tree producing sweet, malty-flavoured fruits. Extremely wind-resistant; ideal for Kanyakumari's coastal conditions. Grafted plants fruit in 4–5 years.",
    daysToHarvest: { min: 120, max: 180 },
    yearsToFirstHarvest: 5,
    heightCm: { min: 500, max: 1500 },
    spacingCm: 800,
    plantingDepthCm: 20,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 180, vegetative: 1645 },
    annualCycleDurations: { flowering: 45, fruiting: 180, dormant: 140 },
    floweringStartMonth: 2,
  },
  [buildProfileKey('fruit_tree', 'Water Apple')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Syzygium aqueum',
    taxonomicFamily: 'Myrtaceae',
    lifecycle: 'perennial',
    tamilName: 'நாவல்',
    description:
      "Tropical evergreen tree producing crisp, mildly sweet bell-shaped fruits. Loves moisture-rich soils; thrives near water sources in Kanyakumari's coastal belt.",
    daysToHarvest: { min: 60, max: 90 },
    yearsToFirstHarvest: 5,
    heightCm: { min: 300, max: 1000 },
    spacingCm: 600,
    plantingDepthCm: 15,
    growingSeason: 'Mar–Jul',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 150, vegetative: 1310 },
    annualCycleDurations: { flowering: 30, fruiting: 60, dormant: 275 },
    floweringStartMonth: 3,
  },
  [buildProfileKey('fruit_tree', 'Custard Apple')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Annona squamosa',
    taxonomicFamily: 'Annonaceae',
    lifecycle: 'perennial',
    tamilName: 'சீதாப்பழம்',
    description:
      'Deciduous tropical tree bearing soft, creamy-sweet segmented fruits. Drought-tolerant once established; hand-pollination improves fruit set in Kanyakumari.',
    daysToHarvest: { min: 90, max: 150 },
    yearsToFirstHarvest: 4,
    heightCm: { min: 300, max: 700 },
    spacingCm: 500,
    plantingDepthCm: 3,
    growingSeason: 'Aug–Dec',
    germinationDays: { min: 21, max: 40 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 150, vegetative: 1310 },
    annualCycleDurations: { flowering: 45, fruiting: 120, dormant: 200 },
    floweringStartMonth: 4,
  },
  [buildProfileKey('fruit_tree', 'Amla')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Phyllanthus emblica',
    taxonomicFamily: 'Phyllanthaceae',
    lifecycle: 'perennial',
    tamilName: 'நெல்லிக்காய்',
    description:
      "Hardy deciduous tree producing tart, vitamin-C-rich berries revered in Ayurveda. Thrives in poor soils with minimal care; excellent for Kanyakumari's red laterite patches.",
    daysToHarvest: { min: 120, max: 180 },
    yearsToFirstHarvest: 5,
    heightCm: { min: 300, max: 800 },
    spacingCm: 600,
    plantingDepthCm: 5,
    growingSeason: 'Oct–Feb',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 180, vegetative: 1645 },
    annualCycleDurations: { flowering: 30, fruiting: 150, dormant: 185 },
    floweringStartMonth: 3,
  },
  [buildProfileKey('fruit_tree', 'Orange')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'neem_cake',
    initialGrowthStage: 'vegetative',
    scientificName: 'Citrus × sinensis',
    taxonomicFamily: 'Rutaceae',
    lifecycle: 'perennial',
    tamilName: 'ஆரஞ்சு',
    description:
      "Evergreen citrus tree producing sweet, juicy fruits. Grafted on rough lemon rootstock for Kanyakumari's conditions; benefits from zinc and micronutrient sprays.",
    daysToHarvest: { min: 150, max: 240 },
    yearsToFirstHarvest: 4,
    heightCm: { min: 300, max: 800 },
    spacingCm: 500,
    plantingDepthCm: 15,
    growingSeason: 'Nov–Mar',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 32 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 120, vegetative: 975 },
    annualCycleDurations: { flowering: 30, fruiting: 150, dormant: 185 },
    floweringStartMonth: 2,
  },
  [buildProfileKey('fruit_tree', 'Fig')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Ficus carica',
    taxonomicFamily: 'Moraceae',
    lifecycle: 'perennial',
    tamilName: 'அத்திப்பழம்',
    description:
      "Deciduous tree producing soft, sweet, fibre-rich fruits. Extremely heat and drought tolerant; easy to propagate from cuttings in Kanyakumari's warm climate.",
    daysToHarvest: { min: 60, max: 90 },
    yearsToFirstHarvest: 2,
    heightCm: { min: 200, max: 600 },
    spacingCm: 400,
    plantingDepthCm: 10,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 90, vegetative: 640 },
    annualCycleDurations: { flowering: 30, fruiting: 90, dormant: 245 },
    floweringStartMonth: 2,
  },
  [buildProfileKey('fruit_tree', 'Avocado')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Persea americana',
    taxonomicFamily: 'Lauraceae',
    lifecycle: 'perennial',
    tamilName: 'வெண்ணெய்ப்பழம்',
    description:
      "Evergreen tropical tree producing nutrient-dense, high-fat fruits. Needs excellent drainage and wind protection; West Indian varieties suit Kanyakumari's lowland tropics.",
    daysToHarvest: { min: 150, max: 270 },
    yearsToFirstHarvest: 5,
    heightCm: { min: 500, max: 1200 },
    spacingCm: 800,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Oct',
    germinationDays: { min: 14, max: 30 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 150, vegetative: 1310 },
    annualCycleDurations: { flowering: 45, fruiting: 150, dormant: 170 },
    floweringStartMonth: 2,
  },
  [buildProfileKey('fruit_tree', 'Soursop')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Annona muricata',
    taxonomicFamily: 'Annonaceae',
    lifecycle: 'perennial',
    tamilName: 'முள்ளு சீதா',
    description:
      'Tropical evergreen tree producing large spiny fruits with creamy, tangy pulp. Related to custard apple; hand-pollination improves yields in Kanyakumari.',
    daysToHarvest: { min: 120, max: 180 },
    yearsToFirstHarvest: 4,
    heightCm: { min: 300, max: 900 },
    spacingCm: 500,
    plantingDepthCm: 3,
    growingSeason: 'Year Round',
    germinationDays: { min: 15, max: 30 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 150, vegetative: 1310 },
    annualCycleDurations: { flowering: 45, fruiting: 150, dormant: 170 },
    floweringStartMonth: 3,
  },
  [buildProfileKey('fruit_tree', 'Mangosteen')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 365,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Garcinia mangostana',
    taxonomicFamily: 'Clusiaceae',
    lifecycle: 'perennial',
    tamilName: 'மாங்குஸ்தான்',
    description:
      'Ultra-tropical tree bearing prized purple fruits with snow-white, sweet-tangy segments. Extremely slow to bear (6–10 years); needs deep shade when young and consistent moisture.',
    daysToHarvest: { min: 100, max: 150 },
    yearsToFirstHarvest: 8,
    heightCm: { min: 500, max: 1500 },
    spacingCm: 800,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Sep',
    germinationDays: { min: 20, max: 30 },
    germinationTempC: { min: 25, max: 32 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 365, vegetative: 2555 },
    annualCycleDurations: { flowering: 45, fruiting: 150, dormant: 170 },
    floweringStartMonth: 11,
  },
  [buildProfileKey('fruit_tree', 'Rambutan')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Nephelium lappaceum',
    taxonomicFamily: 'Sapindaceae',
    lifecycle: 'perennial',
    tamilName: 'ரம்புட்டான்',
    description:
      "Tropical evergreen tree producing hairy-skinned fruits with translucent sweet flesh. Needs high humidity and rainfall; Kanyakumari's climate suits it well. Grafted trees fruit in 4–5 years.",
    daysToHarvest: { min: 90, max: 130 },
    yearsToFirstHarvest: 5,
    heightCm: { min: 500, max: 1500 },
    spacingCm: 800,
    plantingDepthCm: 5,
    growingSeason: 'May–Aug',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.0, max: 6.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 180, vegetative: 1645 },
    annualCycleDurations: { flowering: 45, fruiting: 90, dormant: 230 },
    floweringStartMonth: 12,
  },
  [buildProfileKey('fruit_tree', 'Red Banana')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: "Musa acuminata 'Red Dacca'",
    taxonomicFamily: 'Musaceae',
    lifecycle: 'perennial',
    tamilName: 'செவ்வாழை',
    description:
      'Striking red-skinned banana variety with creamy, slightly raspberry-flavoured flesh. Grown as a temple offering fruit in Tamil Nadu; same care as regular banana with slightly longer maturation.',
    daysToHarvest: { min: 300, max: 400 },
    yearsToFirstHarvest: 1,
    heightCm: { min: 200, max: 450 },
    spacingCm: 300,
    plantingDepthCm: 15,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 45, vegetative: 150, flowering: 30, fruiting: 95 },
  },
  [buildProfileKey('fruit_tree', 'Breadfruit')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Artocarpus altilis',
    taxonomicFamily: 'Moraceae',
    lifecycle: 'perennial',
    tamilName: 'பிரெட்ஃப்ரூட்',
    description:
      "Large tropical tree producing starchy fruits used as a carbohydrate staple. Related to jackfruit; thrives in Kanyakumari's humid coastal climate with minimal care once established.",
    daysToHarvest: { min: 60, max: 90 },
    yearsToFirstHarvest: 5,
    heightCm: { min: 500, max: 2000 },
    spacingCm: 1000,
    plantingDepthCm: 15,
    growingSeason: 'May–Sep',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 180, vegetative: 1645 },
    annualCycleDurations: { flowering: 45, fruiting: 120, dormant: 200 },
    floweringStartMonth: 1,
  },
  [buildProfileKey('fruit_tree', 'Pineapple')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'jeevamrutham',
    initialGrowthStage: 'vegetative',
    scientificName: 'Ananas comosus',
    taxonomicFamily: 'Bromeliaceae',
    lifecycle: 'perennial',
    tamilName: 'அன்னாசி',
    description:
      "Low-growing monocarpic bromeliad producing sweet, acidic tropical fruits. Planted from crown or suckers; thrives in Kanyakumari's red laterite soils with good drainage. Fruits in 18 months.",
    daysToHarvest: { min: 150, max: 180 },
    yearsToFirstHarvest: 2,
    heightCm: { min: 60, max: 120 },
    spacingCm: 60,
    plantingDepthCm: 8,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 4.5, max: 5.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 60, vegetative: 670 },
    annualCycleDurations: { flowering: 60, fruiting: 150, dormant: 155 },
    floweringStartMonth: 5,
  },
  [buildProfileKey('fruit_tree', 'Passion Fruit')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Passiflora edulis',
    taxonomicFamily: 'Passifloraceae',
    lifecycle: 'perennial',
    tamilName: 'பேஷன் ஃப்ரூட்',
    description:
      'Vigorous tropical vine producing aromatic, tangy-sweet fruits. Needs a strong trellis; grows rapidly and fruits within 12–18 months from seed in Kanyakumari. Prune hard after each harvest flush.',
    daysToHarvest: { min: 60, max: 90 },
    yearsToFirstHarvest: 1,
    heightCm: { min: 300, max: 800 },
    spacingCm: 300,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 10, max: 21 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 30, vegetative: 335 },
    annualCycleDurations: { flowering: 60, fruiting: 150, dormant: 155 },
    floweringStartMonth: 3,
  },
  [buildProfileKey('fruit_tree', 'Star Fruit')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Averrhoa carambola',
    taxonomicFamily: 'Oxalidaceae',
    lifecycle: 'perennial',
    tamilName: 'கமரகம்',
    description:
      'Small tropical evergreen tree producing distinctive star-shaped waxy fruits. Fruits prolifically year-round in Kanyakumari; compact enough for home gardens. Avoid in renal patients.',
    daysToHarvest: { min: 60, max: 90 },
    yearsToFirstHarvest: 4,
    heightCm: { min: 300, max: 800 },
    spacingCm: 500,
    plantingDepthCm: 3,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 150, vegetative: 1310 },
    annualCycleDurations: { flowering: 30, fruiting: 90, dormant: 245 },
    floweringStartMonth: 4,
  },
  [buildProfileKey('fruit_tree', 'Arecanut')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Areca catechu',
    taxonomicFamily: 'Arecaceae',
    lifecycle: 'perennial',
    tamilName: 'பாக்கு',
    description:
      "Tall, slender tropical palm cultivated for its betel nut. Widely grown in Kanyakumari's homestead gardens; needs consistent moisture and humidity. Starts bearing in 6–7 years.",
    daysToHarvest: { min: 180, max: 240 },
    yearsToFirstHarvest: 6,
    heightCm: { min: 1000, max: 2000 },
    spacingCm: 300,
    plantingDepthCm: 10,
    growingSeason: 'Year Round',
    germinationDays: { min: 30, max: 60 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 365, vegetative: 1825 },
    annualCycleDurations: { flowering: 45, fruiting: 180, dormant: 140 },
    floweringStartMonth: 11,
  },
};
