import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const HERB_SPICE_OVERRIDES: Record<string, PlantCareProfile> = {
  // ── New Herb / Spice Plants ─────────────────────────────────────────────
  [buildProfileKey('herb', 'Ajwain')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Trachyspermum ammi',
    taxonomicFamily: 'Apiaceae',
    lifecycle: 'annual',
    tamilName: 'ஓமம்',
    description:
      'Aromatic annual herb yielding carom seeds used in South Indian tempering and digestive remedies',
    daysToHarvest: { min: 45, max: 60 },
    heightCm: { min: 30, max: 90 },
    spacingCm: 20,
    plantingDepthCm: 1,
    growingSeason: 'Cool Dry (Oct–Feb)',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 18, max: 28 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 14, vegetative: 25, mature: 14 },
  },
  [buildProfileKey('herb', 'Cardamom')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 180,
    sunlight: 'shade',
    soilType: 'potting_mix',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Elettaria cardamomum',
    taxonomicFamily: 'Zingiberaceae',
    lifecycle: 'perennial',
    tamilName: 'ஏலக்காய்',
    description:
      'Shade-tolerant tropical rhizome producing the queen of spices; intercropped under forest canopy',
    daysToHarvest: { min: 900, max: 1095 },
    heightCm: { min: 150, max: 400 },
    spacingCm: 180,
    plantingDepthCm: 5,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 30, max: 60 },
    germinationTempC: { min: 22, max: 28 },
    soilPhRange: { min: 5.0, max: 6.5 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 180, vegetative: 540, mature: 365 },
  },
  // daysToHarvest is planting-to-first-crop, not the season length: a vine
  // bears from year 3 and only stabilises around year 7. The 6–8 month figure
  // this used to carry is the spike-to-ripe-berry window, which is a different
  // measurement — `fruiting` in growthStageDurations is where that belongs.
  [buildProfileKey('herb', 'Black Pepper')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 180,
    sunlight: 'partial_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Piper nigrum',
    taxonomicFamily: 'Piperaceae',
    lifecycle: 'perennial',
    tamilName: 'கருமிளகு',
    description: 'Climbing spice vine trained on coconut trunks producing the king of spices',
    daysToHarvest: { min: 1095, max: 1460 },
    yearsToFirstHarvest: 3,
    heightCm: { min: 200, max: 1000 },
    spacingCm: 270,
    plantingDepthCm: 15,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 30, max: 45 },
    germinationTempC: { min: 24, max: 32 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    // Quick wilt (Phytophthora foot rot) follows water standing at the collar
    // through the southwest monsoon — drainage matters more here than watering.
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 180, vegetative: 730, flowering: 60, fruiting: 210 },
  },
  [buildProfileKey('herb', 'Fennel')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Foeniculum vulgare',
    taxonomicFamily: 'Apiaceae',
    lifecycle: 'perennial',
    tamilName: 'சோம்பு',
    description:
      'Tall aromatic herb with feathery leaves and anise-flavoured seeds; allelopathic — plant away from most crops',
    daysToHarvest: { min: 65, max: 90 },
    heightCm: { min: 90, max: 200 },
    spacingCm: 45,
    plantingDepthCm: 1,
    growingSeason: 'Cool Dry (Oct–Feb)',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 14, vegetative: 40, mature: 20 },
  },
  [buildProfileKey('herb', 'Brahmi')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 21,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Bacopa monnieri',
    taxonomicFamily: 'Plantaginaceae',
    lifecycle: 'perennial',
    tamilName: 'பிரம்மி',
    description:
      'Low-growing medicinal creeper thriving in moist, shaded spots; revered in Ayurveda for cognitive health',
    daysToHarvest: { min: 30, max: 45 },
    heightCm: { min: 5, max: 20 },
    spacingCm: 20,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 14, vegetative: 30, mature: 20 },
  },
  [buildProfileKey('herb', 'Ashwagandha')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'coastal_sandy',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Withania somnifera',
    taxonomicFamily: 'Solanaceae',
    lifecycle: 'perennial',
    tamilName: 'அஷ்வகந்தா',
    description:
      'Drought-tolerant medicinal shrub producing adaptogenic roots; thrives in sandy well-drained soils',
    daysToHarvest: { min: 150, max: 180 },
    heightCm: { min: 30, max: 120 },
    spacingCm: 60,
    plantingDepthCm: 1,
    growingSeason: 'Cool Dry (Oct–Feb)',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 20, max: 35 },
    soilPhRange: { min: 7.5, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 21, vegetative: 90, mature: 60 },
  },
  [buildProfileKey('herb', 'Aloe Vera')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Aloe barbadensis miller',
    taxonomicFamily: 'Asphodelaceae',
    lifecycle: 'perennial',
    tamilName: 'கற்றாழை',
    description:
      'Succulent perennial with gel-filled leaves used in medicine, skincare, and soil conditioning',
    daysToHarvest: { min: 180, max: 365 },
    heightCm: { min: 30, max: 90 },
    spacingCm: 60,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 20, max: 32 },
    soilPhRange: { min: 7.0, max: 8.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 180, mature: 155 },
  },

};
