import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const HERB_OVERRIDES: Record<string, PlantCareProfile> = {
  // ── Herbs (14) ──────────────────────────────────────────────────────────
  [buildProfileKey('herb', 'Coriander')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Coriandrum sativum',
    taxonomicFamily: 'Apiaceae',
    lifecycle: 'annual',
    tamilName: 'கொத்தமல்லி',
    description:
      'Fast-growing cool-season herb prized for its aromatic leaves and seeds. Bolts quickly in Kanyakumari heat; grow in partial shade and succession-sow every 3 weeks.',
    daysToHarvest: { min: 40, max: 50 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 15,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.2, max: 6.8 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 10, vegetative: 20, mature: 10 },
  },
  [buildProfileKey('herb', 'Mint')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 21,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Mentha spicata',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'perennial',
    tamilName: 'புதினா',
    description:
      'Vigorous spreading herb that thrives in moist, partially shaded spots. Grow in containers to prevent invasive spread; harvest regularly to encourage bushy growth.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 30,
    plantingDepthCm: 0.5,
    growingSeason: 'Year Round',
    germinationDays: { min: 10, max: 15 },
    germinationTempC: { min: 20, max: 25 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 14, vegetative: 30, mature: 16 },
  },
  [buildProfileKey('herb', 'Curry Leaf')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Murraya koenigii',
    taxonomicFamily: 'Rutaceae',
    lifecycle: 'perennial',
    tamilName: 'கறிவேப்பிலை',
    description:
      'Essential South Indian culinary tree producing intensely aromatic leaves. Slow to establish from seed; once rooted, it is drought-hardy and produces year-round in Kanyakumari.',
    daysToHarvest: { min: 365, max: 730 },
    heightCm: { min: 200, max: 600 },
    spacingCm: 200,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 60, vegetative: 240, mature: 65 },
  },
  [buildProfileKey('herb', 'Lemongrass')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Cymbopogon citratus',
    taxonomicFamily: 'Poaceae',
    lifecycle: 'perennial',
    tamilName: 'எலுமிச்சைப்புல்',
    description:
      'Tall aromatic grass used in teas and South-East Asian cuisine. Propagated by dividing stalks; thrives in full sun with minimal care. Doubles as a mosquito-repellent border plant.',
    daysToHarvest: { min: 90, max: 120 },
    heightCm: { min: 90, max: 150 },
    spacingCm: 60,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 21 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 14, vegetative: 50, mature: 16 },
  },
  [buildProfileKey('herb', 'Tulsi')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 21,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Ocimum tenuiflorum',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'perennial',
    tamilName: 'துளசி',
    description:
      'Sacred herb of Indian households valued for medicinal and spiritual significance. Pinch flower buds regularly to keep the plant bushy and prolong leaf production.',
    daysToHarvest: { min: 35, max: 45 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 30,
    plantingDepthCm: 0.5,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 20, max: 25 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 14, vegetative: 30, mature: 16 },
  },
  [buildProfileKey('herb', 'Basil')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Ocimum basilicum',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'annual',
    tamilName: 'திருநீற்றுப்பச்சிலை',
    description:
      'Aromatic culinary herb used in Italian and Thai cooking. Pinch growing tips frequently to delay flowering and encourage bushy side-shoots.',
    daysToHarvest: { min: 50, max: 60 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 20,
    plantingDepthCm: 0.5,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 20, max: 25 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 12, vegetative: 25, mature: 13 },
  },
  [buildProfileKey('herb', 'Dill')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Anethum graveolens',
    taxonomicFamily: 'Apiaceae',
    lifecycle: 'annual',
    tamilName: 'சதகுப்பை',
    description:
      'Feathery herb with a mild anise flavour, popular in pickles and rice dishes. Direct-sow in place; dill has a taproot and does not transplant well.',
    daysToHarvest: { min: 60, max: 70 },
    heightCm: { min: 60, max: 90 },
    spacingCm: 25,
    plantingDepthCm: 0.5,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 10, vegetative: 25, mature: 10 },
  },
  [buildProfileKey('herb', 'Parsley')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Petroselinum crispum',
    taxonomicFamily: 'Apiaceae',
    lifecycle: 'biennial',
    tamilName: 'பார்சிலி',
    description:
      'Slow-germinating biennial herb used as a garnish and flavouring. Soak seeds overnight before sowing to speed germination. Grows best in partial shade in Kanyakumari heat.',
    daysToHarvest: { min: 60, max: 70 },
    heightCm: { min: 30, max: 45 },
    spacingCm: 20,
    plantingDepthCm: 0.5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 10, max: 25 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 20, vegetative: 40, mature: 15 },
  },
  [buildProfileKey('herb', 'Rosemary')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Salvia rosmarinus',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'perennial',
    tamilName: 'ரோஸ்மேரி',
    description:
      "Woody Mediterranean perennial with needle-like leaves and a piney fragrance. Needs excellent drainage; prone to root rot in Kanyakumari's humid monsoon if over-watered.",
    daysToHarvest: { min: 180, max: 365 },
    heightCm: { min: 60, max: 120 },
    spacingCm: 60,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 90, mature: 60 },
  },
  [buildProfileKey('herb', 'Thyme')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Thymus vulgaris',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'perennial',
    tamilName: 'தைம்',
    description:
      'Low-growing perennial herb with tiny aromatic leaves. Prefers lean, well-drained soil; overfeeding reduces essential oil concentration. Trim after flowering to maintain shape.',
    daysToHarvest: { min: 180, max: 365 },
    heightCm: { min: 15, max: 30 },
    spacingCm: 30,
    plantingDepthCm: 0.5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.0, max: 8.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 21, vegetative: 60, mature: 30 },
  },
  [buildProfileKey('herb', 'Oregano')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Origanum vulgare',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'perennial',
    tamilName: 'ஓரிகானோ',
    description:
      'Hardy perennial with peppery, slightly bitter leaves essential for Mediterranean cooking. Cut stems back to 10 cm after flowering to stimulate fresh aromatic growth.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 20, max: 40 },
    spacingCm: 25,
    plantingDepthCm: 0.5,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.0, max: 8.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 14, vegetative: 45, mature: 21 },
  },
  [buildProfileKey('herb', 'Turmeric')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 30,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Curcuma longa',
    taxonomicFamily: 'Zingiberaceae',
    lifecycle: 'perennial',
    tamilName: 'மஞ்சள்',
    description:
      'Tropical rhizomatous herb yielding the golden spice of Indian cooking. Plant finger-sized rhizome pieces with buds in loose, humus-rich soil; harvest when leaves turn yellow.',
    daysToHarvest: { min: 240, max: 270 },
    heightCm: { min: 60, max: 100 },
    spacingCm: 30,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 30, vegetative: 120, mature: 90, dormant: 30 },
  },
  [buildProfileKey('herb', 'Ginger')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 30,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Zingiber officinale',
    taxonomicFamily: 'Zingiberaceae',
    lifecycle: 'perennial',
    tamilName: 'இஞ்சி',
    description:
      'Pungent rhizome staple in South Indian cooking and Ayurvedic medicine. Plant rhizome pieces with 2–3 eye buds in filtered shade; mulch heavily to retain moisture.',
    daysToHarvest: { min: 210, max: 240 },
    heightCm: { min: 60, max: 120 },
    spacingCm: 25,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 30, vegetative: 120, mature: 80, dormant: 25 },
  },
  [buildProfileKey('herb', 'Betel Leaf')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 30,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Piper betle',
    taxonomicFamily: 'Piperaceae',
    lifecycle: 'perennial',
    tamilName: 'வெற்றிலை',
    description:
      'Tropical climbing vine prized for its glossy heart-shaped leaves used in paan and traditional ceremonies. Provide a trellis or support post; thrives in humid, shaded conditions.',
    daysToHarvest: { min: 150, max: 180 },
    heightCm: { min: 150, max: 300 },
    spacingCm: 45,
    plantingDepthCm: 3,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 25, max: 30 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 30, vegetative: 90, mature: 60 },
  },
};
