import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const INTERCROP_FRUIT_TREE_OVERRIDES: Record<string, PlantCareProfile> = {
  // ── New Fruit Trees (Coconut Intercrop) ────────────────────────────────
  [buildProfileKey('fruit_tree', 'Cocoa')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 90,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Theobroma cacao',
    taxonomicFamily: 'Malvaceae',
    lifecycle: 'permanent',
    tamilName: 'கொக்கோ',
    description:
      'Shade-tolerant understorey tree producing pods of prized chocolate beans; intercropped with banana and coconut',
    yearsToFirstHarvest: 4,
    heightCm: { min: 400, max: 800 },
    spacingCm: 300,
    plantingDepthCm: 10,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 24, max: 28 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 180, vegetative: 1270 },
    annualCycleDurations: { flowering: 60, fruiting: 120, dormant: 185 },
    floweringStartMonth: 4,
  },
  [buildProfileKey('fruit_tree', 'Nutmeg')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Myristica fragrans',
    taxonomicFamily: 'Myristicaceae',
    lifecycle: 'permanent',
    tamilName: 'ஜாதிக்காய்',
    description:
      'Aromatic tropical tree yielding two spices — nutmeg seed and mace aril; 7–8 years to first harvest',
    yearsToFirstHarvest: 8,
    heightCm: { min: 500, max: 2000 },
    spacingCm: 600,
    plantingDepthCm: 10,
    growingSeason: 'Southwest Monsoon (Jun–Sep)',
    germinationDays: { min: 30, max: 60 },
    germinationTempC: { min: 24, max: 32 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 365, vegetative: 2555 },
    annualCycleDurations: { flowering: 60, fruiting: 180, dormant: 125 },
    floweringStartMonth: 3,
  },
};
