import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const NEW_SHRUB_OVERRIDES: Record<string, PlantCareProfile> = {
  // ── New Shrub Plants ────────────────────────────────────────────────────
  [buildProfileKey('shrub', 'Agathi')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 45,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Sesbania grandiflora',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'perennial',
    tamilName: 'அகத்தி',
    description:
      'Fast-growing nitrogen-fixing shrub with edible leaves and flowers; dynamic accumulator for chop-and-drop',
    daysToHarvest: { min: 45, max: 90 },
    heightCm: { min: 300, max: 800 },
    spacingCm: 200,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 22, max: 35 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 21, vegetative: 45, mature: 24 },
  },
  [buildProfileKey('shrub', 'Castor')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Ricinus communis',
    taxonomicFamily: 'Euphorbiaceae',
    lifecycle: 'perennial',
    tamilName: 'ஆமணக்கு',
    description:
      'Tall fast-growing shrub with repellent properties; pest-deterrent companion around vegetable beds',
    daysToHarvest: { min: 90, max: 120 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 150,
    plantingDepthCm: 3,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 5.0, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 21, vegetative: 60, mature: 39 },
  },
  [buildProfileKey('shrub', 'Coleus')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 30,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Plectranthus amboinicus',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'perennial',
    tamilName: 'கொல்லியஸ்',
    description:
      'Ornamental shade-tolerant shrub used as living mulch in coconut intercrop systems',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 30, max: 80 },
    spacingCm: 40,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 21, vegetative: 45, mature: 24 },
  },

};
