import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

/**
 * Tamil Nadu homestead shrubs and medicinals.
 *
 * Split by how the gardener uses the plant, which is how this catalog files
 * everything else: `herb` already holds Curry Leaf (a tree), Black Pepper (a
 * vine) and Ashwagandha (a shrub), so a plant harvested for its leaves belongs
 * there whatever its growth habit. `shrub` keeps the woody perennials grown
 * for the plant itself — hedges, boundaries and companions.
 *
 * `daysToHarvest` on these perennials means planting-to-first-usable-harvest,
 * not the length of a picking season — see `docs/DOMAIN_LOGIC.md`. Neither
 * type is exempt from the midpoint rule the way fruit trees are, so a
 * season-length figure here would promise a first harvest far too early.
 */
export const TAMIL_NADU_SHRUB_OVERRIDES: Record<string, PlantCareProfile> = {
  [buildProfileKey('shrub', 'Maruthani')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 6,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Lawsonia inermis',
    taxonomicFamily: 'Lythraceae',
    lifecycle: 'perennial',
    tamilName: 'மருதாணி',
    description:
      'The classic Tamil boundary hedge; leaves ground for henna, and it takes hard clipping. Dye strength is highest from a sunny, unwatered plant, so resist feeding it heavily.',
    daysToHarvest: { min: 300, max: 420 },
    heightCm: { min: 150, max: 500 },
    spacingCm: 75,
    plantingDepthCm: 10,
    growingSeason: 'Year Round',
    germinationDays: { min: 15, max: 30 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 45, vegetative: 240, flowering: 60, mature: 120 },
  },
  [buildProfileKey('shrub', 'Aavaram')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Senna auriculata',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'perennial',
    tamilName: 'ஆவாரம்',
    description:
      'Dryland-hardy shrub grown for its yellow aavarampoo flowers; fixes nitrogen and holds bunds together. Thrives on the poor red soil where little else will, and resents wet feet.',
    daysToHarvest: { min: 240, max: 330 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 120,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 15 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 180, flowering: 75, mature: 120 },
  },
  [buildProfileKey('shrub', 'Nochi')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 6,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Vitex negundo',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'perennial',
    tamilName: 'நொச்சி',
    description:
      'Aromatic shrub whose leaves are layered into stored grain and steeped as a leaf-extract pest spray. Roots readily from a cut stake pushed straight into monsoon ground.',
    daysToHarvest: { min: 180, max: 270 },
    heightCm: { min: 200, max: 500 },
    spacingCm: 150,
    plantingDepthCm: 15,
    growingSeason: 'Year Round',
    germinationDays: { min: 15, max: 30 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 150, flowering: 60, mature: 120 },
  },
  [buildProfileKey('shrub', 'Arali')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Nerium oleander',
    taxonomicFamily: 'Apocynaceae',
    lifecycle: 'perennial',
    tamilName: 'அரளி',
    description:
      'Temple flowering shrub, drought-hardy and long-blooming. Every part is toxic if eaten and the milky sap irritates skin — wear gloves to prune, never burn the trimmings, and keep it away from children, pets and the vegetable beds.',
    daysToHarvest: { min: 210, max: 300 },
    heightCm: { min: 150, max: 400 },
    spacingCm: 150,
    plantingDepthCm: 10,
    growingSeason: 'Year Round',
    germinationDays: { min: 15, max: 30 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 180, flowering: 60, mature: 120 },
  },
};

/** Medicinals grown for a leaf harvest — shrubby, succulent or scrambling. */
export const TAMIL_NADU_HERB_OVERRIDES: Record<string, PlantCareProfile> = {
  [buildProfileKey('herb', 'Adathodai')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 90,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Justicia adhatoda',
    taxonomicFamily: 'Acanthaceae',
    lifecycle: 'perennial',
    tamilName: 'ஆடாதொடை',
    description:
      'Hardy medicinal shrub of the Tamil homestead; leaves brewed for coughs and also cut as green-leaf manure. Struck easily from hardwood cuttings and tolerates the shade under a coconut canopy.',
    daysToHarvest: { min: 180, max: 270 },
    heightCm: { min: 120, max: 300 },
    spacingCm: 100,
    plantingDepthCm: 10,
    growingSeason: 'Year Round',
    germinationDays: { min: 15, max: 25 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 150, flowering: 45, mature: 90 },
  },
  [buildProfileKey('herb', 'Nithyakalyani')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'coastal_sandy',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Catharanthus roseus',
    taxonomicFamily: 'Apocynaceae',
    lifecycle: 'perennial',
    tamilName: 'நித்தியகல்யாணி',
    description:
      'Tough evergreen flowering year-round on poor soil; self-seeds freely and needs almost no care. Sap is bitter and toxic if eaten, so keep it out of the salad beds.',
    daysToHarvest: { min: 90, max: 120 },
    heightCm: { min: 30, max: 90 },
    spacingCm: 40,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 10, max: 20 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 25, vegetative: 45, flowering: 60, mature: 90 },
  },
  [buildProfileKey('herb', 'Thoothuvalai')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 60,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Solanum trilobatum',
    taxonomicFamily: 'Solanaceae',
    lifecycle: 'perennial',
    tamilName: 'தூதுவளை',
    description:
      'Scrambling prickly climber of the kitchen doorway, cooked as a cough and cold remedy. Give it a low support to sprawl over; the thorns make an unclipped plant hard to pick from.',
    daysToHarvest: { min: 100, max: 150 },
    heightCm: { min: 60, max: 200 },
    spacingCm: 90,
    plantingDepthCm: 2,
    growingSeason: 'Year Round',
    germinationDays: { min: 12, max: 25 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 25, vegetative: 75, flowering: 45, mature: 90 },
  },
  [buildProfileKey('herb', 'Karpooravalli')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 45,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Plectranthus amboinicus',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'perennial',
    tamilName: 'கற்பூரவல்லி',
    description:
      'Thick-leaved aromatic plant kept by the kitchen door; leaves used fresh for coughs and colds. Grows from a snapped-off stem in a pot and rots if the soil stays wet.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 30, max: 100 },
    spacingCm: 45,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 10, max: 20 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 20, vegetative: 55, flowering: 40, mature: 90 },
  },

};
