import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

/**
 * Tamil Nadu / Kanyakumari edible plants the catalog had never carried.
 *
 * Grouped by category rather than split across the per-category override files
 * so the pass stays reviewable in one place, following `tamilNaduPlants.ts`.
 *
 * `daysToHarvest` is planting-to-first-usable-harvest throughout, never season
 * length — the distinction the Black Pepper correction turned on. For the
 * perennials it is stated in days *and* mirrored by `yearsToFirstHarvest`, so
 * neither the vegetable-style nor the tree-style harvest-date path promises a
 * first crop in the first season.
 */

export const TAMIL_NADU_EDIBLE_VEGETABLE_OVERRIDES: Record<string, PlantCareProfile> = {
  // Grown from stem cuttings, not seed: `germinationDays` is 0 and the plant
  // starts at `vegetative`, the same shape the other cutting-grown rows use.
  [buildProfileKey('vegetable', 'Ivy Gourd')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Coccinia grandis',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'perennial',
    tamilName: 'கோவைக்காய்',
    description:
      'Perennial pandal vine grown from cuttings; crops for years with almost no replanting. Plant female cuttings — a seedling-raised vine may be male and never fruit.',
    daysToHarvest: { min: 90, max: 120 },
    heightCm: { min: 200, max: 500 },
    spacingCm: 200,
    plantingDepthCm: 15,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { vegetative: 60, flowering: 30, fruiting: 30 },
  },
  [buildProfileKey('vegetable', 'Turkey Berry')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Solanum torvum',
    taxonomicFamily: 'Solanaceae',
    lifecycle: 'perennial',
    tamilName: 'சுண்டைக்காய்',
    description:
      'Hardy perennial bearing clustered green berries for sundakkai vathal and kuzhambu. Also the standard bacterial-wilt-resistant rootstock for grafted brinjal.',
    daysToHarvest: { min: 150, max: 210 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 150,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 25, max: 32 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    waterloggingTolerance: 'low',
    // Solanaceae: raw berries and foliage are not safe fodder, as with Tomato.
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 90, flowering: 30, fruiting: 40 },
  },
  [buildProfileKey('vegetable', 'Sesame')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 6,
    fertilisingFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'red_loam',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Sesamum indicum',
    taxonomicFamily: 'Pedaliaceae',
    lifecycle: 'annual',
    tamilName: 'எள்ளு',
    description:
      'Short-duration oilseed for gingelly oil and ellu urundai; tolerates poor, dry soil. Very sensitive to standing water — sow on a raised bed and harvest before the capsules split.',
    daysToHarvest: { min: 80, max: 95 },
    heightCm: { min: 60, max: 120 },
    spacingCm: 15,
    plantingDepthCm: 2,
    growingSeason: 'Rabi (Oct–Jan)',
    germinationDays: { min: 3, max: 6 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 12, vegetative: 30, flowering: 25, mature: 20 },
  },
};

export const TAMIL_NADU_EDIBLE_GREENS_OVERRIDES: Record<string, PlantCareProfile> = {
  [buildProfileKey('spinach', 'Roselle')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Hibiscus sabdariffa',
    taxonomicFamily: 'Malvaceae',
    lifecycle: 'annual',
    tamilName: 'புளிச்சக்கீரை',
    description:
      'Sour-leaved hibiscus green for kuzhambu and thokku; known elsewhere as gongura. Pick the tender top leaves repeatedly and pinch out flower buds to keep the plant in leaf.',
    daysToHarvest: { min: 45, max: 60 },
    heightCm: { min: 90, max: 200 },
    spacingCm: 45,
    plantingDepthCm: 1,
    growingSeason: 'Kharif (Jun–Sep)',
    germinationDays: { min: 4, max: 8 },
    germinationTempC: { min: 24, max: 32 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 12, vegetative: 40, flowering: 30 },
  },
  [buildProfileKey('spinach', 'False Daisy')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 30,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Eclipta prostrata',
    taxonomicFamily: 'Asteraceae',
    lifecycle: 'annual',
    tamilName: 'கரிசலாங்கண்ணி',
    description:
      'Creeping marshy green cooked as keerai and long used in Siddha hair and liver preparations. Spreads from rooting nodes in a permanently damp corner; cut, never uproot.',
    daysToHarvest: { min: 30, max: 45 },
    heightCm: { min: 15, max: 40 },
    spacingCm: 20,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 12 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    waterloggingTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 10, vegetative: 25 },
  },
  [buildProfileKey('spinach', 'Madras Pea Pumpkin')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Mukia maderaspatana',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'annual',
    tamilName: 'முசுமுசுக்கை',
    description:
      'Rough-leaved trailing vine of Tamil hedgerows, cooked as keerai for coughs and colds. Self-seeds along a fence or hedge and needs no support beyond it.',
    daysToHarvest: { min: 40, max: 55 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 60,
    plantingDepthCm: 2,
    growingSeason: 'Kharif (Jun–Sep)',
    germinationDays: { min: 6, max: 12 },
    germinationTempC: { min: 24, max: 34 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 12, vegetative: 30, flowering: 15 },
  },
};

/**
 * Spices filed under `herb` because that is the spice tab — Curry Leaf is a
 * tree and Black Pepper a vine for the same reason. Clove and Cinnamon follow
 * the Black Pepper pattern: `daysToHarvest` in planting-to-first-crop days with
 * a matching `yearsToFirstHarvest`, so neither promises a first-season harvest.
 */
export const TAMIL_NADU_EDIBLE_SPICE_OVERRIDES: Record<string, PlantCareProfile> = {
  [buildProfileKey('herb', 'Adamant Creeper')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 6,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 120,
    sunlight: 'partial_sun',
    soilType: 'sandy_loam',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Cissus quadrangularis',
    taxonomicFamily: 'Vitaceae',
    lifecycle: 'perennial',
    tamilName: 'பிரண்டை',
    description:
      'Square-stemmed succulent climber grown from cuttings on a fence or tree. Tender tips are made into thuvaiyal and pickle — handle with care, since raw sap irritates skin and mouth and the tips are always cooked or salted first.',
    daysToHarvest: { min: 120, max: 180 },
    heightCm: { min: 150, max: 500 },
    spacingCm: 100,
    plantingDepthCm: 10,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 24, max: 35 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { vegetative: 120, mature: 60 },
  },
  [buildProfileKey('herb', 'Clove')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'partial_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Syzygium aromaticum',
    taxonomicFamily: 'Myrtaceae',
    lifecycle: 'perennial',
    tamilName: 'கிராம்பு',
    description:
      'Evergreen hill spice tree harvested for its unopened flower buds. Wants shade, shelter from wind, and high humidity — a Kanyakumari hill-slope crop rather than a plains one; yields build from about year six.',
    daysToHarvest: { min: 2190, max: 2920 },
    yearsToFirstHarvest: 6,
    heightCm: { min: 500, max: 1200 },
    spacingCm: 600,
    plantingDepthCm: 30,
    growingSeason: 'Kharif (Jun–Sep)',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 365, vegetative: 1825 },
    annualCycleDurations: { flowering: 90, fruiting: 60, dormant: 215 },
    floweringStartMonth: 12,
  },
  [buildProfileKey('herb', 'Cinnamon')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 365,
    sunlight: 'partial_sun',
    soilType: 'sandy_loam',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Cinnamomum verum',
    taxonomicFamily: 'Lauraceae',
    lifecycle: 'perennial',
    tamilName: 'கருவாப்பட்டை',
    description:
      'Coppiced spice tree harvested for its inner bark, not left to grow tall. Cut the stool back hard once established and peel the straight re-shoots; leaves are also used whole as bay-like flavouring.',
    daysToHarvest: { min: 1095, max: 1460 },
    yearsToFirstHarvest: 3,
    heightCm: { min: 200, max: 800 },
    spacingCm: 200,
    plantingDepthCm: 20,
    growingSeason: 'Kharif (Jun–Sep)',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 22, max: 33 },
    soilPhRange: { min: 5.0, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 180, vegetative: 915 },
  },
  [buildProfileKey('herb', 'Mango Ginger')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    sunlight: 'partial_sun',
    soilType: 'sandy_loam',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'seedling',
    scientificName: 'Curcuma amada',
    taxonomicFamily: 'Zingiberaceae',
    lifecycle: 'annual',
    tamilName: 'மாஇஞ்சி',
    description:
      'Raw-mango-scented rhizome of the turmeric family, used fresh in pachadi and pickle. Grown exactly like turmeric — planted with the pre-monsoon rains and lifted once the foliage dies back.',
    daysToHarvest: { min: 210, max: 270 },
    heightCm: { min: 60, max: 100 },
    spacingCm: 30,
    plantingDepthCm: 6,
    growingSeason: 'Kharif (Jun–Sep)',
    germinationDays: { min: 15, max: 30 },
    germinationTempC: { min: 24, max: 32 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 30, vegetative: 120, mature: 90 },
  },
};

export const TAMIL_NADU_EDIBLE_FRUIT_TREE_OVERRIDES: Record<string, PlantCareProfile> = {
  [buildProfileKey('fruit_tree', 'Tamarind')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'red_loam',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Tamarindus indica',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'perennial',
    tamilName: 'புளி',
    description:
      'Long-lived shade tree of every Tamil village; pods give the souring pulp for sambar and rasam. Grafted PKM 1 bears from about year four, a seedling tree not before eight — plant it where a very large canopy is welcome.',
    daysToHarvest: { min: 1460, max: 2920 },
    yearsToFirstHarvest: 4,
    heightCm: { min: 800, max: 2500 },
    spacingCm: 1000,
    plantingDepthCm: 30,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 21 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 365, vegetative: 1095 },
    annualCycleDurations: { flowering: 60, fruiting: 210, dormant: 95 },
    floweringStartMonth: 5,
  },
  [buildProfileKey('fruit_tree', 'Jamun')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Syzygium cumini',
    taxonomicFamily: 'Myrtaceae',
    lifecycle: 'perennial',
    tamilName: 'நாவல்',
    description:
      'Monsoon-fruiting tree bearing astringent purple berries; leaves and bark are also used medicinally. Tolerates seasonally wet ground better than most fruit trees, which is why it is planted along tank bunds.',
    daysToHarvest: { min: 2190, max: 2920 },
    yearsToFirstHarvest: 6,
    heightCm: { min: 800, max: 2000 },
    spacingCm: 900,
    plantingDepthCm: 30,
    growingSeason: 'Year Round',
    germinationDays: { min: 10, max: 25 },
    germinationTempC: { min: 24, max: 34 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    waterloggingTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 365, vegetative: 1825 },
    annualCycleDurations: { flowering: 45, fruiting: 90, dormant: 230 },
    floweringStartMonth: 3,
  },
  [buildProfileKey('fruit_tree', 'Cashew')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'coastal_sandy',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Anacardium occidentale',
    taxonomicFamily: 'Anacardiaceae',
    lifecycle: 'perennial',
    tamilName: 'முந்திரி',
    description:
      'Salt- and drought-tolerant coastal tree yielding cashew nut and cashew apple; a major Kanyakumari crop on poor sandy ground. The shell liquid between the nut shells is caustic — roast in the open air and never handle raw shells bare-handed.',
    daysToHarvest: { min: 1095, max: 1825 },
    yearsToFirstHarvest: 3,
    heightCm: { min: 600, max: 1200 },
    spacingCm: 800,
    plantingDepthCm: 30,
    growingSeason: 'Year Round',
    germinationDays: { min: 15, max: 25 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    waterloggingTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 180, vegetative: 915 },
    annualCycleDurations: { flowering: 75, fruiting: 90, dormant: 200 },
    floweringStartMonth: 11,
  },
  [buildProfileKey('fruit_tree', 'Wood Apple')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'red_loam',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Limonia acidissima',
    taxonomicFamily: 'Rutaceae',
    lifecycle: 'perennial',
    tamilName: 'விளாம்பழம்',
    description:
      'Slow-growing hardy tree with woody-shelled fruit made into sherbet and chutney. Survives long dry spells and poor soil once established; the branches carry sharp spines, so site it away from paths.',
    daysToHarvest: { min: 2555, max: 3650 },
    yearsToFirstHarvest: 7,
    heightCm: { min: 600, max: 1200 },
    spacingCm: 800,
    plantingDepthCm: 30,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 30 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 8.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 365, vegetative: 2190 },
    annualCycleDurations: { flowering: 45, fruiting: 270, dormant: 50 },
    floweringStartMonth: 2,
  },
  [buildProfileKey('fruit_tree', 'Indian Jujube')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'red_loam',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Ziziphus mauritiana',
    taxonomicFamily: 'Rhamnaceae',
    lifecycle: 'perennial',
    tamilName: 'இலந்தை',
    description:
      'Thorny drought-hardy tree fruiting through the cool season; eaten fresh, dried, or salted. Unusual among fruit trees in wanting a hard annual cutback — it fruits on the current season’s growth.',
    daysToHarvest: { min: 730, max: 1095 },
    yearsToFirstHarvest: 2,
    heightCm: { min: 400, max: 1000 },
    spacingCm: 600,
    plantingDepthCm: 25,
    growingSeason: 'Rabi (Oct–Jan)',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 8.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 180, vegetative: 550 },
    annualCycleDurations: { flowering: 45, fruiting: 120, dormant: 200 },
    floweringStartMonth: 8,
  },
  [buildProfileKey('fruit_tree', 'Palm Tree')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 14,
    fertilisingFrequencyDays: 180,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'coastal_sandy',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Borassus flabellifer',
    taxonomicFamily: 'Arecaceae',
    lifecycle: 'perennial',
    tamilName: 'பனை',
    description:
      'Tamil Nadu’s state tree, tapped for padaneer and karupatti and cut young for nungu. Extremely long-lived and effectively maintenance-free once established, but slow: plant it as a legacy tree, not a crop for this decade.',
    daysToHarvest: { min: 4380, max: 5475 },
    yearsToFirstHarvest: 12,
    heightCm: { min: 1000, max: 3000 },
    spacingCm: 800,
    plantingDepthCm: 30,
    growingSeason: 'Year Round',
    germinationDays: { min: 60, max: 120 },
    germinationTempC: { min: 26, max: 36 },
    soilPhRange: { min: 6.0, max: 8.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    waterloggingTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 730, vegetative: 3650 },
    annualCycleDurations: { flowering: 60, fruiting: 150, dormant: 155 },
    floweringStartMonth: 1,
  },
  [buildProfileKey('fruit_tree', 'Sweet Lime')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'sandy_loam',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Citrus limetta',
    taxonomicFamily: 'Rutaceae',
    lifecycle: 'perennial',
    tamilName: 'சாத்துக்குடி',
    description:
      'Mild low-acid citrus grown for juice. Needs free-draining soil and steady, even watering — irregular watering splits the fruit, and water standing at the collar brings on foot rot.',
    daysToHarvest: { min: 1095, max: 1460 },
    yearsToFirstHarvest: 3,
    heightCm: { min: 300, max: 600 },
    spacingCm: 500,
    plantingDepthCm: 25,
    growingSeason: 'Year Round',
    germinationDays: { min: 0, max: 0 },
    germinationTempC: { min: 24, max: 34 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 180, vegetative: 915 },
    annualCycleDurations: { flowering: 45, fruiting: 240, dormant: 80 },
    floweringStartMonth: 2,
  },
};
