import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const TIMBER_COCONUT_SHRUB_OVERRIDES: Record<string, PlantCareProfile> = {
  // ── Timber Trees (7) + Coconut Trees (4) + Shrubs (8) ──────────────
  [buildProfileKey('timber_tree', 'Neem')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Azadirachta indica',
    taxonomicFamily: 'Meliaceae',
    lifecycle: 'perennial',
    tamilName: 'வேம்பு',
    description:
      "Fast-growing evergreen valued for pest-repellent properties and durable timber. Thrives in Kanyakumari's heat with minimal care. Neem cake and leaf extract are staples in organic gardening.",
    daysToHarvest: { min: 0, max: 0 },
    heightCm: { min: 500, max: 2000 },
    spacingCm: 500,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 21 },
    germinationTempC: { min: 20, max: 35 },
    soilPhRange: { min: 6.2, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 120, vegetative: 1095, mature: 545 },
  },
  [buildProfileKey('timber_tree', 'Teak')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Tectona grandis',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'perennial',
    tamilName: 'தேக்கு',
    description:
      'Premier hardwood timber tree with large deciduous leaves. Prefers well-drained laterite soils and seasonal dry spells. Young trees benefit from annual composting during monsoon.',
    daysToHarvest: { min: 0, max: 0 },
    heightCm: { min: 600, max: 3000 },
    spacingCm: 600,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Sep',
    germinationDays: { min: 10, max: 30 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 150, vegetative: 1460, mature: 730 },
  },
  [buildProfileKey('timber_tree', 'Mahogany')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 120,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Swietenia macrophylla',
    taxonomicFamily: 'Meliaceae',
    lifecycle: 'perennial',
    tamilName: 'மகாகனி',
    description:
      "High-value tropical timber with a straight trunk and broad canopy. Grows well in Kanyakumari's warm humid climate. Requires little care once established; stake young saplings against coastal wind.",
    daysToHarvest: { min: 0, max: 0 },
    heightCm: { min: 800, max: 3500 },
    spacingCm: 600,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Aug',
    germinationDays: { min: 10, max: 28 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 150, vegetative: 1460, mature: 730 },
  },
  [buildProfileKey('timber_tree', 'Rosewood')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 120,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Dalbergia latifolia',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'perennial',
    tamilName: 'ரோஸ்வுட்',
    description:
      'Prized hardwood with dark fragrant heartwood. A nitrogen-fixing legume that enriches surrounding soil. Slow-growing but extremely drought-hardy once established in laterite soils.',
    daysToHarvest: { min: 0, max: 0 },
    heightCm: { min: 600, max: 2500 },
    spacingCm: 500,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Sep',
    germinationDays: { min: 14, max: 30 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 180, vegetative: 1825, mature: 730 },
  },
  [buildProfileKey('timber_tree', 'Sandalwood')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'partial_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Santalum album',
    taxonomicFamily: 'Santalaceae',
    lifecycle: 'perennial',
    tamilName: 'சந்தனம்',
    description:
      'Aromatic heartwood tree and hemi-parasite that needs a host plant nearby. Very slow-growing; thrives in well-drained laterite or rocky soils. Protect saplings from cattle and full afternoon sun.',
    daysToHarvest: { min: 0, max: 0 },
    heightCm: { min: 400, max: 1200 },
    spacingCm: 400,
    plantingDepthCm: 3,
    growingSeason: 'Jun–Aug',
    germinationDays: { min: 30, max: 60 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 365, vegetative: 2190, mature: 1095 },
  },
  [buildProfileKey('timber_tree', 'Bamboo')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Bambusa bambos',
    taxonomicFamily: 'Poaceae',
    lifecycle: 'perennial',
    tamilName: 'மூங்கில்',
    description:
      "Giant clumping grass producing strong culms used for construction and crafts. Extremely fast-growing in Kanyakumari's monsoon months. Contain spread with a root barrier or trench.",
    daysToHarvest: { min: 0, max: 0 },
    heightCm: { min: 500, max: 2500 },
    spacingCm: 500,
    plantingDepthCm: 10,
    growingSeason: 'Jun–Sep',
    germinationDays: { min: 14, max: 30 },
    germinationTempC: { min: 22, max: 35 },
    soilPhRange: { min: 5.5, max: 6.8 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 60, vegetative: 365, mature: 305 },
  },
  [buildProfileKey('timber_tree', 'Wild Jack')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Artocarpus hirsutus',
    taxonomicFamily: 'Moraceae',
    lifecycle: 'perennial',
    tamilName: 'ஐயன்பலா',
    description:
      "Large evergreen tree native to the Western Ghats, yielding durable timber and edible fruit. Thrives in Kanyakumari's laterite-rich foothills with moderate rainfall. Low maintenance once established.",
    daysToHarvest: { min: 0, max: 0 },
    heightCm: { min: 600, max: 2500 },
    spacingCm: 600,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Sep',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 150, vegetative: 1460, mature: 730 },
  },
  [buildProfileKey('coconut_tree', 'Dwarf Coconut')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'coastal_sandy',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Cocos nucifera var. nana',
    taxonomicFamily: 'Arecaceae',
    lifecycle: 'perennial',
    tamilName: 'குட்டைத் தென்னை',
    description:
      'Compact coconut palm ideal for small plots. Bears early (3–4 years) and produces sweet tender coconuts. Needs consistent watering and bimonthly feeding with vermicompost or groundnut cake.',
    daysToHarvest: { min: 45, max: 60 },
    yearsToFirstHarvest: 3,
    heightCm: { min: 500, max: 800 },
    spacingCm: 500,
    plantingDepthCm: 15,
    growingSeason: 'Year Round',
    germinationDays: { min: 60, max: 120 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
  },
  [buildProfileKey('coconut_tree', 'Tall Coconut')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'coastal_sandy',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Cocos nucifera var. typica',
    taxonomicFamily: 'Arecaceae',
    lifecycle: 'perennial',
    tamilName: 'உயரத் தென்னை',
    description:
      'Traditional tall coconut grown along the Kanyakumari coast. Hardy and long-lived, yielding copra-quality nuts. Tolerates coastal wind and salt spray; apply salt around base annually to boost production.',
    daysToHarvest: { min: 60, max: 90 },
    yearsToFirstHarvest: 6,
    heightCm: { min: 1500, max: 3000 },
    spacingCm: 750,
    plantingDepthCm: 20,
    growingSeason: 'Year Round',
    germinationDays: { min: 90, max: 150 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
  },
  [buildProfileKey('coconut_tree', 'Hybrid Coconut')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'coastal_sandy',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Cocos nucifera (D × T hybrid)',
    taxonomicFamily: 'Arecaceae',
    lifecycle: 'perennial',
    tamilName: 'கலப்பினத் தென்னை',
    description:
      'Cross between Dwarf and Tall varieties combining early bearing with high copra yield. Responds well to regular feeding and irrigation. Popular choice for commercial plots in Kanyakumari district.',
    daysToHarvest: { min: 50, max: 75 },
    yearsToFirstHarvest: 4,
    heightCm: { min: 800, max: 2000 },
    spacingCm: 650,
    plantingDepthCm: 18,
    growingSeason: 'Year Round',
    germinationDays: { min: 75, max: 130 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'heavy',
  },
  [buildProfileKey('coconut_tree', 'King Coconut')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'coastal_sandy',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Cocos nucifera var. aurantiaca',
    taxonomicFamily: 'Arecaceae',
    lifecycle: 'perennial',
    tamilName: 'ராஜ தென்னை',
    description:
      "Orange-skinned coconut prized for its naturally sweet water. Ornamental and functional; grows well in Kanyakumari's coastal belt. Needs steady moisture and bimonthly organic feeding.",
    daysToHarvest: { min: 50, max: 70 },
    yearsToFirstHarvest: 4,
    heightCm: { min: 800, max: 1800 },
    spacingCm: 600,
    plantingDepthCm: 15,
    growingSeason: 'Year Round',
    germinationDays: { min: 70, max: 120 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
  },
  [buildProfileKey('shrub', 'Hibiscus')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Hibiscus rosa-sinensis',
    taxonomicFamily: 'Malvaceae',
    lifecycle: 'perennial',
    tamilName: 'செம்பருத்தி',
    description:
      'Bushy hedge variety producing showy blooms year-round. Used as a living fence and windbreak in Kanyakumari gardens. Prune hard in January for compact form and more flowering branches.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 100, max: 400 },
    spacingCm: 90,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 25, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 30, vegetative: 90, mature: 60 },
  },
  [buildProfileKey('shrub', 'Ixora')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Ixora coccinea',
    taxonomicFamily: 'Rubiaceae',
    lifecycle: 'perennial',
    tamilName: 'இட்லிப்பூ',
    description:
      'Dense evergreen shrub bearing clusters of scarlet flowers, commonly shaped into hedges and borders. Slow to recover from heavy pruning; trim lightly after each bloom cycle. Prefers acidic to neutral soil.',
    daysToHarvest: { min: 90, max: 120 },
    heightCm: { min: 80, max: 300 },
    spacingCm: 60,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 21, max: 42 },
    germinationTempC: { min: 25, max: 30 },
    soilPhRange: { min: 5.0, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 45, vegetative: 120, mature: 75 },
  },
  [buildProfileKey('shrub', 'Nandiyavattai')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Tabernaemontana divaricata',
    taxonomicFamily: 'Apocynaceae',
    lifecycle: 'perennial',
    tamilName: 'நந்தியாவட்டை',
    description:
      'Fragrant white-flowered shrub sacred in Tamil temple gardens. Blooms heavily after monsoon pruning. Tolerates light shade and coastal salt; milky sap can irritate skin.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 90,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 21, max: 35 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 45, vegetative: 120, mature: 75 },
  },
  [buildProfileKey('shrub', 'Bougainvillea')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Bougainvillea spectabilis',
    taxonomicFamily: 'Nyctaginaceae',
    lifecycle: 'perennial',
    tamilName: 'பூகன்வில்லியா',
    description:
      'Vigorous thorny shrub-vine smothered in papery bracts. Stress-blooms when water is withheld; overwatering reduces flowering. Hard-prune in January for compact hedge form in Kanyakumari gardens.',
    daysToHarvest: { min: 60, max: 120 },
    heightCm: { min: 100, max: 500 },
    spacingCm: 120,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 21, max: 30 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 90, mature: 60 },
  },
  [buildProfileKey('shrub', 'Jasmine')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'groundnut_cake',
    initialGrowthStage: 'vegetative',
    scientificName: 'Jasminum grandiflorum',
    taxonomicFamily: 'Oleaceae',
    lifecycle: 'perennial',
    tamilName: 'மல்லிகை',
    description:
      "Vigorous woody shrub producing intensely fragrant white flowers used in garlands and essential oil. Hard-prune after each flush and feed with groundnut cake for continuous blooms in Kanyakumari's warm climate.",
    daysToHarvest: { min: 60, max: 100 },
    heightCm: { min: 100, max: 400 },
    spacingCm: 100,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 45, vegetative: 120, mature: 75 },
  },
  [buildProfileKey('shrub', 'Crossandra')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 45,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Crossandra infundibuliformis',
    taxonomicFamily: 'Acanthaceae',
    lifecycle: 'perennial',
    tamilName: 'கனகாம்பரம்',
    description:
      'Low-growing evergreen hedge shrub bearing fan-shaped orange flowers prized for temple garlands. Blooms profusely in warm humid conditions; pinch tips regularly for bushy growth and more flower spikes.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 30, max: 120 },
    spacingCm: 45,
    plantingDepthCm: 3,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 30, vegetative: 90, mature: 60 },
  },
  [buildProfileKey('shrub', 'Lantana')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 45,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Lantana camara',
    taxonomicFamily: 'Verbenaceae',
    lifecycle: 'perennial',
    tamilName: 'உன்னிச்செடி',
    description:
      'Extremely hardy flowering shrub that thrives on neglect. Attracts butterflies but can become invasive — prune regularly and remove seed heads. Berries are toxic to pets and children.',
    daysToHarvest: { min: 45, max: 75 },
    heightCm: { min: 60, max: 200 },
    spacingCm: 90,
    plantingDepthCm: 3,
    growingSeason: 'Year Round',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 21, vegetative: 60, mature: 30 },
  },
  [buildProfileKey('shrub', 'Gardenia')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 90,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Gardenia jasminoides',
    taxonomicFamily: 'Rubiaceae',
    lifecycle: 'perennial',
    tamilName: 'கொண்டை கத்தரி',
    description:
      "Compact evergreen shrub with waxy, intensely fragrant white blooms. Prefers acidic soil and consistent moisture; sensitive to alkaline water. Mulch around the base to keep roots cool in Kanyakumari's heat.",
    daysToHarvest: { min: 90, max: 120 },
    heightCm: { min: 60, max: 200 },
    spacingCm: 90,
    plantingDepthCm: 5,
    growingSeason: 'Mar–Sep',
    germinationDays: { min: 30, max: 60 },
    germinationTempC: { min: 20, max: 28 },
    soilPhRange: { min: 5.0, max: 6.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 45, vegetative: 150, mature: 75 },
  },

};
