import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const TIMBER_COCONUT_SHRUB_OVERRIDES: Record<string, PlantCareProfile> = {
  // ── Timber Trees (7) + Coconut (1) + Shrubs (8) ──────────────
  [buildProfileKey('timber_tree', 'Neem')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Azadirachta indica',
    taxonomicFamily: 'Meliaceae',
    lifecycle: 'permanent',
    tamilName: 'வேம்பு',
    description:
      "Fast-growing evergreen valued for pest-repellent properties and durable timber. Thrives in Kanyakumari's heat with minimal care. Neem cake and leaf extract are staples in organic gardening.",
    heightCm: { min: 500, max: 2000 },
    spacingCm: 500,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 21 },
    germinationTempC: { min: 20, max: 35 },
    soilPhRange: { min: 6.2, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 120, vegetative: 1095, mature: 545 },
  },
  [buildProfileKey('timber_tree', 'Teak')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Tectona grandis',
    taxonomicFamily: 'Lamiaceae',
    lifecycle: 'permanent',
    tamilName: 'தேக்கு',
    description:
      'Premier hardwood timber tree with large deciduous leaves. Prefers well-drained laterite soils and seasonal dry spells. Young trees benefit from annual composting during monsoon.',
    heightCm: { min: 600, max: 3000 },
    spacingCm: 600,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Sep',
    germinationDays: { min: 10, max: 30 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 150, vegetative: 1460, mature: 730 },
  },
  [buildProfileKey('timber_tree', 'Mahogany')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 120,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Swietenia macrophylla',
    taxonomicFamily: 'Meliaceae',
    lifecycle: 'permanent',
    tamilName: 'மகாகனி',
    description:
      "High-value tropical timber with a straight trunk and broad canopy. Grows well in Kanyakumari's warm humid climate. Requires little care once established; stake young saplings against coastal wind.",
    heightCm: { min: 800, max: 3500 },
    spacingCm: 600,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Aug',
    germinationDays: { min: 10, max: 28 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 150, vegetative: 1460, mature: 730 },
  },
  [buildProfileKey('timber_tree', 'Rosewood')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 120,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Dalbergia latifolia',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'permanent',
    tamilName: 'ஈட்டி',
    description:
      'Prized hardwood with dark fragrant heartwood. A nitrogen-fixing legume that enriches surrounding soil. Slow-growing but extremely drought-hardy once established in laterite soils.',
    heightCm: { min: 600, max: 2500 },
    spacingCm: 500,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Sep',
    germinationDays: { min: 14, max: 30 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 180, vegetative: 1825, mature: 730 },
  },
  [buildProfileKey('timber_tree', 'Sandalwood')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'partial_sun',
    soilType: 'red_laterite',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Santalum album',
    taxonomicFamily: 'Santalaceae',
    lifecycle: 'permanent',
    tamilName: 'சந்தனம்',
    description:
      'Aromatic heartwood tree and hemi-parasite that needs a host plant nearby. Very slow-growing; thrives in well-drained laterite or rocky soils. Protect saplings from cattle and full afternoon sun.',
    heightCm: { min: 400, max: 1200 },
    spacingCm: 400,
    plantingDepthCm: 3,
    growingSeason: 'Jun–Aug',
    germinationDays: { min: 30, max: 60 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'medium',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 365, vegetative: 2190, mature: 1095 },
  },
  [buildProfileKey('timber_tree', 'Bamboo')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 60,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Bambusa bambos',
    taxonomicFamily: 'Poaceae',
    lifecycle: 'permanent',
    tamilName: 'மூங்கில்',
    description:
      "Giant clumping grass producing strong culms used for construction and crafts. Extremely fast-growing in Kanyakumari's monsoon months. Contain spread with a root barrier or trench.",
    heightCm: { min: 500, max: 2500 },
    spacingCm: 500,
    plantingDepthCm: 10,
    growingSeason: 'Jun–Sep',
    germinationDays: { min: 14, max: 30 },
    germinationTempC: { min: 22, max: 35 },
    soilPhRange: { min: 5.5, max: 6.8 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 60, vegetative: 365, mature: 305 },
  },
  [buildProfileKey('timber_tree', 'Wild Jack')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Artocarpus hirsutus',
    taxonomicFamily: 'Moraceae',
    lifecycle: 'permanent',
    tamilName: 'ஐயன்பலா',
    description:
      "Large evergreen tree native to the Western Ghats, yielding durable timber and edible fruit. Thrives in Kanyakumari's laterite-rich foothills with moderate rainfall. Low maintenance once established.",
    heightCm: { min: 600, max: 2500 },
    spacingCm: 600,
    plantingDepthCm: 5,
    growingSeason: 'Jun–Sep',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 150, vegetative: 1460, mature: 730 },
  },
  [buildProfileKey('coconut_tree', 'Coconut')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 7,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'coastal_sandy',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Cocos nucifera',
    taxonomicFamily: 'Arecaceae',
    lifecycle: 'permanent',
    tamilName: 'தென்னை',
    description:
      'Coconut palm, the Kanyakumari homestead staple. Tall types (West Coast Tall) are hardy and long-lived and bear in 6–7 years; dwarfs bear in 3–4 but need more care; hybrids fall between. Tolerates coastal wind and salt spray.',
    daysToHarvest: { min: 60, max: 90 },
    yearsToFirstHarvest: 6,
    heightCm: { min: 1500, max: 3000 },
    spacingCm: 750,
    plantingDepthCm: 20,
    growingSeason: 'Year Round',
    germinationDays: { min: 90, max: 150 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
  },
  [buildProfileKey('flower', 'Nandiyavattai')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Tabernaemontana divaricata',
    taxonomicFamily: 'Apocynaceae',
    lifecycle: 'perennial',
    tamilName: 'நந்தியாவட்டை',
    description:
      'Fragrant white-flowered shrub sacred in Tamil temple gardens. Blooms heavily after monsoon pruning. Tolerates light shade and coastal salt; milky sap can irritate skin.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 100, max: 300 },
    spacingCm: 90,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 21, max: 35 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 45, vegetative: 120, flowering: 60, mature: 75 },
  },
  [buildProfileKey('shrub', 'Bougainvillea')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Bougainvillea spectabilis',
    taxonomicFamily: 'Nyctaginaceae',
    lifecycle: 'perennial',
    tamilName: 'காகிதப்பூ',
    description:
      'Vigorous thorny shrub-vine smothered in papery bracts. Stress-blooms when water is withheld; overwatering reduces flowering. Hard-prune in January for compact hedge form in Kanyakumari gardens.',
    daysToHarvest: { min: 60, max: 120 },
    heightCm: { min: 100, max: 500 },
    spacingCm: 120,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 21, max: 30 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 90, flowering: 45, mature: 60 },
  },

};
