import type { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

/**
 * Source-reviewed corrections for crops eligible for the Today seasonal card.
 * These are applied after the historical Kanyakumari-biased shards so the
 * catalog detail and action-specific Today figures share one Tamil Nadu scope.
 */
export const TODAY_RECOMMENDATION_CROP_OVERRIDES: Record<
  string,
  Partial<PlantCareProfile>
> = {
  [buildProfileKey('vegetable', 'Amaranthus')]: {
    daysToHarvest: { min: 25, max: 30 },
    growingSeason: 'February–March and July–August',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Beetroot')]: {
    daysToHarvest: { min: 90, max: 100 },
    growingSeason: 'October–December',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Bitter Gourd')]: {
    daysToHarvest: { min: 55, max: 60 },
    spacingCm: 150,
    growingSeason: 'February–March',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Brinjal')]: {
    daysToHarvest: { min: 45, max: 60 },
    spacingCm: 60,
    growingSeason: 'January–February and July–August',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Chilli')]: {
    daysToHarvest: { min: 50, max: 60 },
    spacingCm: 60,
    growingSeason: 'January–February and July–August',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Cluster Beans')]: {
    daysToHarvest: { min: 30, max: 35 },
    spacingCm: 15,
    growingSeason: 'July–August',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Cowpea')]: {
    daysToHarvest: { min: 60, max: 65 },
    spacingCm: 45,
    growingSeason: 'January–February',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Cucumber')]: {
    daysToHarvest: { min: 45, max: 50 },
    growingSeason: 'February–March',
    description: 'Warm-season climbing vegetable grown for crisp fruits; provide support, even moisture, and free drainage.',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Fenugreek')]: {
    daysToHarvest: { min: 45, max: 50 },
    growingSeason: 'September–December',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Ladies Finger')]: {
    daysToHarvest: { min: 30, max: 35 },
    growingSeason: 'June–July',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Onion')]: {
    daysToHarvest: { min: 75, max: 80 },
    spacingCm: 10,
    growingSeason: 'June–July and October–November',
    description: 'Bulb vegetable for sunny, well-drained beds; transplant healthy seedlings without burying the neck.',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Radish')]: {
    daysToHarvest: { min: 25, max: 30 },
    spacingCm: 10,
    growingSeason: 'Year-round in a managed home garden',
    description: 'Fast root vegetable for loose, stone-free soil; steady moisture reduces tough or split roots.',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Tomato')]: {
    daysToHarvest: { min: 60, max: 65 },
    spacingCm: 60,
    growingSeason: 'December–January and June–July',
    waterloggingTolerance: 'low',
  },
  [buildProfileKey('vegetable', 'Turnip')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Brassica rapa subsp. rapa',
    taxonomicFamily: 'Brassicaceae',
    lifecycle: 'biennial',
    tamilName: 'டர்னிப்',
    description: 'Cool-season brassica grown for its swollen root and edible leaves in loose, well-drained soil.',
    daysToHarvest: { min: 40, max: 45 },
    heightCm: { min: 25, max: 45 },
    spacingCm: 10,
    plantingDepthCm: 1.5,
    growingSeason: 'September–October',
    germinationDays: { min: 3, max: 10 },
    germinationTempC: { min: 10, max: 30 },
    soilPhRange: { min: 5.5, max: 7.5 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
  },
  [buildProfileKey('spinach', 'Palak')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 14,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Spinacia oleracea',
    taxonomicFamily: 'Amaranthaceae',
    lifecycle: 'annual',
    tamilName: 'பாலக் கீரை',
    description: 'Cool-season leafy vegetable best harvested while leaves are tender and before heat encourages bolting.',
    daysToHarvest: { min: 50, max: 55 },
    heightCm: { min: 20, max: 30 },
    spacingCm: 10,
    plantingDepthCm: 1.5,
    growingSeason: 'September–October',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 10, max: 25 },
    soilPhRange: { min: 6, max: 7.5 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    waterloggingTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
  },
};
