import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const VEGETABLE_OVERRIDES_1: Record<string, PlantCareProfile> = {
  // ── Vegetables (34) ────────────────────────────────────────────────────
  [buildProfileKey('vegetable', 'Brinjal')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Solanum melongena',
    taxonomicFamily: 'Solanaceae',
    lifecycle: 'annual',
    tamilName: 'கத்தரிக்காய்',
    description:
      'Versatile tropical nightshade yielding glossy purple fruit for curries and grills',
    daysToHarvest: { min: 70, max: 90 },
    heightCm: { min: 45, max: 120 },
    spacingCm: 60,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 5.5, max: 6.8 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 21, vegetative: 25, flowering: 15, fruiting: 24 },
  },
  [buildProfileKey('vegetable', 'Long Brinjal')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Solanum melongena',
    taxonomicFamily: 'Solanaceae',
    lifecycle: 'annual',
    tamilName: 'நீள கத்தரிக்காய்',
    description: 'Elongated purple eggplant variety favoured in South Indian sambar and stir-fries',
    daysToHarvest: { min: 75, max: 95 },
    heightCm: { min: 45, max: 120 },
    spacingCm: 60,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 5.5, max: 6.8 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 21, vegetative: 28, flowering: 16, fruiting: 25 },
  },
  [buildProfileKey('vegetable', 'Ladies Finger')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Abelmoschus esculentus',
    taxonomicFamily: 'Malvaceae',
    lifecycle: 'annual',
    tamilName: 'வெண்டைக்காய்',
    description: 'Heat-loving mucilaginous pod vegetable essential in South Indian cooking',
    daysToHarvest: { min: 50, max: 70 },
    heightCm: { min: 90, max: 180 },
    spacingCm: 45,
    plantingDepthCm: 2,
    growingSeason: 'Summer (Mar-May)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 6.8 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 14, vegetative: 18, flowering: 10, fruiting: 15 },
  },
  [buildProfileKey('vegetable', 'Tomato')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Solanum lycopersicum',
    taxonomicFamily: 'Solanaceae',
    lifecycle: 'annual',
    tamilName: 'தக்காளி',
    description: 'Prolific warm-season fruit used fresh, in sambar, rasam, and chutneys',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 60, max: 180 },
    spacingCm: 60,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 6.0, max: 6.8 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    waterloggingTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 21, vegetative: 25, flowering: 14, fruiting: 20 },
  },
  [buildProfileKey('vegetable', 'Chilli')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Capsicum annuum',
    taxonomicFamily: 'Solanaceae',
    lifecycle: 'annual',
    tamilName: 'மிளகாய்',
    description: 'Pungent hot pepper central to South Indian spice blends and daily cooking',
    daysToHarvest: { min: 75, max: 95 },
    heightCm: { min: 45, max: 90 },
    spacingCm: 45,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 21, vegetative: 25, flowering: 14, fruiting: 20 },
  },
  [buildProfileKey('vegetable', 'Tapioca')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 90,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Manihot esculenta',
    taxonomicFamily: 'Euphorbiaceae',
    lifecycle: 'perennial',
    tamilName: 'மரவள்ளிக்கிழங்கு',
    description: 'Starchy root crop grown widely in Kanyakumari for kappa and traditional dishes',
    daysToHarvest: { min: 240, max: 300 },
    heightCm: { min: 150, max: 400 },
    spacingCm: 100,
    plantingDepthCm: 10,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 30, vegetative: 200, mature: 90 },
  },
  [buildProfileKey('vegetable', 'Drumstick')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 120,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Moringa oleifera',
    taxonomicFamily: 'Moringaceae',
    lifecycle: 'perennial',
    tamilName: 'முருங்கை',
    description: 'Fast-growing tropical tree providing nutrient-dense pods, leaves, and flowers',
    daysToHarvest: { min: 150, max: 210 },
    heightCm: { min: 300, max: 1000 },
    spacingCm: 300,
    plantingDepthCm: 5,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 30, vegetative: 90, flowering: 30, fruiting: 60 },
  },
  [buildProfileKey('vegetable', 'Amaranthus')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 10,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Amaranthus tricolor',
    taxonomicFamily: 'Amaranthaceae',
    lifecycle: 'annual',
    tamilName: 'அரைக்கீரை',
    description: 'Quick-growing leafy green rich in iron, popular as keerai in Tamil cuisine',
    daysToHarvest: { min: 25, max: 40 },
    heightCm: { min: 30, max: 90 },
    spacingCm: 15,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 3, max: 7 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 10, vegetative: 18, mature: 10 },
  },
  [buildProfileKey('vegetable', 'Methi')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 14,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Trigonella foenum-graecum',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'annual',
    tamilName: 'வெந்தயக்கீரை',
    description: 'Aromatic legume grown for its iron-rich leaves and bitter-sweet flavour',
    daysToHarvest: { min: 25, max: 35 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 10,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 3, max: 5 },
    germinationTempC: { min: 18, max: 28 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 7, vegetative: 13, mature: 8 },
  },
  [buildProfileKey('vegetable', 'Cowpea')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Vigna unguiculata',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'annual',
    tamilName: 'காராமணி',
    description: 'Heat-tolerant nitrogen-fixing legume yielding protein-rich pods and beans',
    daysToHarvest: { min: 45, max: 65 },
    heightCm: { min: 45, max: 80 },
    spacingCm: 30,
    plantingDepthCm: 3,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 8 },
    germinationTempC: { min: 22, max: 35 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'high',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 14, vegetative: 20, flowering: 12, fruiting: 14 },
  },
  [buildProfileKey('vegetable', 'Beans')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Phaseolus vulgaris',
    taxonomicFamily: 'Fabaceae',
    lifecycle: 'annual',
    tamilName: 'பீன்ஸ்',
    description: 'Versatile climbing legume producing tender pods for stir-fries and curries',
    daysToHarvest: { min: 50, max: 70 },
    heightCm: { min: 30, max: 200 },
    spacingCm: 30,
    plantingDepthCm: 3,
    growingSeason: 'Year Round',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 18, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 12, vegetative: 18, flowering: 12, fruiting: 13 },
  },
  [buildProfileKey('vegetable', 'Bitter Gourd')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Momordica charantia',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'annual',
    tamilName: 'பாகற்காய்',
    description: 'Warty-skinned climbing cucurbit prized for its medicinal bitter flavour',
    daysToHarvest: { min: 50, max: 70 },
    heightCm: { min: 150, max: 400 },
    spacingCm: 60,
    plantingDepthCm: 2,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 6.7 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 14, vegetative: 18, flowering: 12, fruiting: 16 },
  },
  [buildProfileKey('vegetable', 'Snake Gourd')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Trichosanthes cucumerina',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'annual',
    tamilName: 'புடலங்காய்',
    description: 'Long striped cucurbit vine producing mild-flavoured gourds for sambar',
    daysToHarvest: { min: 60, max: 80 },
    heightCm: { min: 200, max: 500 },
    spacingCm: 90,
    plantingDepthCm: 2,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 14, vegetative: 22, flowering: 14, fruiting: 18 },
  },
  [buildProfileKey('vegetable', 'Ridge Gourd')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Luffa acutangula',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'annual',
    tamilName: 'பீர்க்கங்காய்',
    description: 'Ridged climbing vine bearing tender gourds widely used in kootu and poriyal',
    daysToHarvest: { min: 55, max: 75 },
    heightCm: { min: 200, max: 500 },
    spacingCm: 90,
    plantingDepthCm: 2,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 12, vegetative: 18, flowering: 12, fruiting: 13 },
  },
  [buildProfileKey('vegetable', 'Bottle Gourd')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Lagenaria siceraria',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'annual',
    tamilName: 'சுரைக்காய்',
    description: 'Vigorous trailing vine producing mild watery gourds for kootu and sweets',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 200, max: 600 },
    spacingCm: 120,
    plantingDepthCm: 3,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 7, max: 12 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 14, vegetative: 22, flowering: 14, fruiting: 18 },
  },
  [buildProfileKey('vegetable', 'Pumpkin')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Cucurbita moschata',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'annual',
    tamilName: 'பரங்கிக்காய்',
    description: 'Sprawling cucurbit yielding large sweet-fleshed fruit for kootu and aviyal',
    daysToHarvest: { min: 90, max: 130 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 150,
    plantingDepthCm: 3,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 22, max: 32 },
    soilPhRange: { min: 6.0, max: 6.8 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 15, vegetative: 35, flowering: 20, fruiting: 35 },
  },
  [buildProfileKey('vegetable', 'Ash Gourd')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Benincasa hispida',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'annual',
    tamilName: 'வெள்ளைப்பூசணி',
    description: 'Wax-coated trailing cucurbit used in petha, kootu, and traditional medicine',
    daysToHarvest: { min: 100, max: 140 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 150,
    plantingDepthCm: 3,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 5, max: 10 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 15, vegetative: 35, flowering: 20, fruiting: 35 },
  },
};
