import { PlantCareProfile } from '@/types/database.types';
import { buildProfileKey } from '@/utils/plantCareDefaults/profileKey';

export const VEGETABLE_OVERRIDES_2: Record<string, PlantCareProfile> = {
  [buildProfileKey('vegetable', 'Cucumber')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Cucumis sativus',
    taxonomicFamily: 'Cucurbitaceae',
    lifecycle: 'annual',
    tamilName: 'வெள்ளரிக்காய்',
    description:
      "Fast-growing warm-season vine producing crisp, refreshing fruits. Thrives in Kanyakumari's tropical heat with consistent moisture and trellis support.",
    daysToHarvest: { min: 50, max: 60 },
    heightCm: { min: 30, max: 200 },
    spacingCm: 60,
    plantingDepthCm: 2,
    growingSeason: 'Summer (Mar-May)',
    germinationDays: { min: 3, max: 7 },
    germinationTempC: { min: 20, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 10, vegetative: 16, flowering: 12, fruiting: 14 },
  },
  [buildProfileKey('vegetable', 'Radish')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Raphanus sativus',
    taxonomicFamily: 'Brassicaceae',
    lifecycle: 'annual',
    tamilName: 'முள்ளங்கி',
    description:
      'One of the fastest-maturing root vegetables. Excellent beginner crop for Kanyakumari gardens, thriving in the cool dry season with loose, well-drained soil.',
    daysToHarvest: { min: 25, max: 35 },
    heightCm: { min: 15, max: 30 },
    spacingCm: 8,
    plantingDepthCm: 1,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 3, max: 5 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 7, vegetative: 15, mature: 8 },
  },
  [buildProfileKey('vegetable', 'Onion')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Allium cepa',
    taxonomicFamily: 'Amaryllidaceae',
    lifecycle: 'biennial',
    tamilName: 'வெங்காயம்',
    description:
      'Essential kitchen staple grown as a bulb crop. Requires well-drained soil and full sun during the cool dry season in Kanyakumari for proper bulb development.',
    daysToHarvest: { min: 90, max: 110 },
    heightCm: { min: 30, max: 50 },
    spacingCm: 12,
    plantingDepthCm: 2,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 7, max: 12 },
    germinationTempC: { min: 18, max: 25 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 20, vegetative: 50, mature: 35 },
  },
  [buildProfileKey('vegetable', 'Shallot')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Allium cepa var. aggregatum',
    taxonomicFamily: 'Amaryllidaceae',
    lifecycle: 'perennial',
    tamilName: 'சின்ன வெங்காயம்',
    description:
      "Small, pungent bulb onion widely used in South Indian cooking. Multiplies readily from sets and adapts well to Kanyakumari's coastal conditions.",
    daysToHarvest: { min: 80, max: 100 },
    heightCm: { min: 20, max: 40 },
    spacingCm: 10,
    plantingDepthCm: 2,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 18, max: 25 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'medium',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 15, vegetative: 35, mature: 25 },
  },
  [buildProfileKey('vegetable', 'Garlic')]: {
    waterRequirement: 'low',
    wateringFrequencyDays: 4,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Allium sativum',
    taxonomicFamily: 'Amaryllidaceae',
    lifecycle: 'perennial',
    tamilName: 'பூண்டு',
    description:
      'Pungent bulb with potent medicinal and culinary value. Requires well-drained soil and the cool dry season of Kanyakumari for bulb formation.',
    daysToHarvest: { min: 150, max: 200 },
    heightCm: { min: 30, max: 60 },
    spacingCm: 10,
    plantingDepthCm: 3,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 15, max: 22 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'low',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 20, vegetative: 70, mature: 45 },
  },
  [buildProfileKey('vegetable', 'Cabbage')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'seedling',
    scientificName: 'Brassica oleracea var. capitata',
    taxonomicFamily: 'Brassicaceae',
    lifecycle: 'biennial',
    tamilName: 'முட்டைக்கோஸ்',
    description:
      "Cool-season brassica forming dense leafy heads. Requires consistent moisture and fertile soil during Kanyakumari's cool dry months for tight head formation.",
    daysToHarvest: { min: 80, max: 100 },
    heightCm: { min: 25, max: 40 },
    spacingCm: 45,
    plantingDepthCm: 1,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 4, max: 7 },
    germinationTempC: { min: 18, max: 25 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 20, vegetative: 45, mature: 25 },
  },
  [buildProfileKey('vegetable', 'Cauliflower')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'seedling',
    scientificName: 'Brassica oleracea var. botrytis',
    taxonomicFamily: 'Brassicaceae',
    lifecycle: 'annual',
    tamilName: 'காலிஃபிளவர்',
    description:
      'Cool-season brassica producing compact white curds. Demands rich soil, consistent watering, and the cooler months in Kanyakumari for quality head development.',
    daysToHarvest: { min: 75, max: 100 },
    heightCm: { min: 30, max: 50 },
    spacingCm: 45,
    plantingDepthCm: 1,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 4, max: 7 },
    germinationTempC: { min: 18, max: 25 },
    soilPhRange: { min: 6.0, max: 7.5 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 20, vegetative: 45, mature: 25 },
  },
  [buildProfileKey('vegetable', 'Carrot')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Daucus carota subsp. sativus',
    taxonomicFamily: 'Apiaceae',
    lifecycle: 'biennial',
    tamilName: 'கேரட்',
    description:
      "Popular root vegetable rich in beta-carotene. Needs deep, loose, stone-free soil for straight root growth during Kanyakumari's cool dry season.",
    daysToHarvest: { min: 70, max: 90 },
    heightCm: { min: 20, max: 35 },
    spacingCm: 5,
    plantingDepthCm: 1,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 10, max: 18 },
    germinationTempC: { min: 15, max: 25 },
    soilPhRange: { min: 6.0, max: 6.8 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'light',
    growthStageDurations: { seedling: 14, vegetative: 40, mature: 26 },
  },
  [buildProfileKey('vegetable', 'Potato')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Solanum tuberosum',
    taxonomicFamily: 'Solanaceae',
    lifecycle: 'annual',
    tamilName: 'உருளைக்கிழங்கு',
    description:
      'Versatile tuberous crop grown worldwide. Requires loose, well-drained soil and hilling during the cool dry season in Kanyakumari for tuber development.',
    daysToHarvest: { min: 80, max: 100 },
    heightCm: { min: 40, max: 60 },
    spacingCm: 30,
    plantingDepthCm: 10,
    growingSeason: 'Cool Dry (Jan-Feb)',
    germinationDays: { min: 14, max: 21 },
    germinationTempC: { min: 15, max: 22 },
    soilPhRange: { min: 5.0, max: 6.5 },
    heatTolerance: 'low',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 15, vegetative: 45, mature: 28 },
  },
  [buildProfileKey('vegetable', 'Pepper')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    scientificName: 'Capsicum annuum',
    taxonomicFamily: 'Solanaceae',
    lifecycle: 'perennial',
    tamilName: 'குடைமிளகாய்',
    description:
      'Warm-season fruiting plant related to chilli, producing sweet or mildly hot fruits. Grows year-round in Kanyakumari with good drainage and regular feeding.',
    daysToHarvest: { min: 60, max: 90 },
    heightCm: { min: 40, max: 90 },
    spacingCm: 45,
    plantingDepthCm: 1,
    growingSeason: 'Year Round',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 6.0, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 21, vegetative: 24, flowering: 14, fruiting: 19 },
  },
  [buildProfileKey('vegetable', 'Taro')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 1,
    fertilisingFrequencyDays: 30,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Colocasia esculenta',
    taxonomicFamily: 'Araceae',
    lifecycle: 'perennial',
    tamilName: 'சேப்பங்கிழங்கு',
    description:
      "Tropical tuber crop with edible corms and leaves. Thrives in Kanyakumari's monsoon moisture with partial shade and consistently wet, humus-rich soil.",
    daysToHarvest: { min: 180, max: 270 },
    heightCm: { min: 60, max: 150 },
    spacingCm: 60,
    plantingDepthCm: 8,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 25, vegetative: 130, mature: 55 },
  },
  [buildProfileKey('vegetable', 'Elephant Yam')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Amorphophallus paeoniifolius',
    taxonomicFamily: 'Araceae',
    lifecycle: 'perennial',
    tamilName: 'கருணைக்கிழங்கு',
    description:
      "Large tropical tuber crop valued in South Indian cuisine. Requires minimal maintenance once established, thriving in Kanyakumari's monsoon season with rich organic soil.",
    daysToHarvest: { min: 200, max: 270 },
    heightCm: { min: 60, max: 120 },
    spacingCm: 90,
    plantingDepthCm: 15,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 21, max: 35 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: true,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 30, vegetative: 170, mature: 70 },
  },
  [buildProfileKey('vegetable', 'Sweet Potato')]: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    scientificName: 'Ipomoea batatas',
    taxonomicFamily: 'Convolvulaceae',
    lifecycle: 'perennial',
    tamilName: 'சர்க்கரைவள்ளிக்கிழங்கு',
    description:
      "Nutritious tropical vine producing sweet tuberous roots. Well-suited to Kanyakumari's warm monsoon season, spreading as ground cover in sandy or loamy soils.",
    daysToHarvest: { min: 100, max: 140 },
    heightCm: { min: 20, max: 40 },
    spacingCm: 30,
    plantingDepthCm: 8,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 7, max: 14 },
    germinationTempC: { min: 22, max: 30 },
    soilPhRange: { min: 5.5, max: 6.5 },
    heatTolerance: 'high',
    droughtTolerance: 'medium',
    petToxicity: false,
    feedingIntensity: 'medium',
    growthStageDurations: { seedling: 15, vegetative: 60, mature: 30 },
  },
  [buildProfileKey('vegetable', 'Ash Plantain')]: {
    waterRequirement: 'high',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 30,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'cow_dung_slurry',
    initialGrowthStage: 'vegetative',
    scientificName: 'Musa × paradisiaca',
    taxonomicFamily: 'Musaceae',
    lifecycle: 'perennial',
    tamilName: 'நேந்திரம் வாழை',
    description:
      "Starchy cooking banana widely used in South Indian cuisine. A robust perennial producing suckers freely in Kanyakumari's humid monsoon climate with rich, moist soil.",
    daysToHarvest: { min: 270, max: 365 },
    heightCm: { min: 200, max: 350 },
    spacingCm: 200,
    plantingDepthCm: 20,
    growingSeason: 'Southwest Monsoon (Jun-Sep)',
    germinationDays: { min: 14, max: 28 },
    germinationTempC: { min: 25, max: 35 },
    soilPhRange: { min: 5.5, max: 7.0 },
    heatTolerance: 'high',
    droughtTolerance: 'low',
    petToxicity: false,
    feedingIntensity: 'heavy',
    growthStageDurations: { seedling: 45, vegetative: 180, flowering: 30, fruiting: 60 },
  },
};
