import { BedType } from '@/types/database.types';

// Recommended plant names per bed type — matched against the app's plant catalog
export const BED_PLANT_CATALOG: Record<BedType, string[]> = {
  leafy: [
    'Amaranth',
    'Spinach',
    'Lettuce',
    'Fenugreek',
    'Coriander',
    'Mint',
    'Purslane',
    'Drumstick',
    'Curry Leaf',
    'Pasalai Keerai',
  ],
  fruiting: [
    'Tomato',
    'Brinjal',
    'Ladies Finger',
    'Pepper',
    'Chilli',
    'Bitter Gourd',
    'Snake Gourd',
    'Ridge Gourd',
    'Bottle Gourd',
    'Marigold',
  ],
  spice: [
    'Chilli',
    'Ginger',
    'Turmeric',
    'Curry Leaf',
    'Pepper',
    'Garlic',
    'Onion',
    'Cardamom',
    'Coriander',
    'Ajwain',
  ],
  root_legume: [
    'Cowpea',
    'French Beans',
    'Black Gram',
    'Pigeon Pea',
    'Groundnut',
    'Carrot',
    'Radish',
    'Beetroot',
    'Sweet Potato',
    'Yam',
    'Cluster Beans',
  ],
  climber_trellis: [
    'Bitter Gourd',
    'Snake Gourd',
    'Yardlong Beans',
    'Cucumber',
    'Bottle Gourd',
    'Ridge Gourd',
    'Passion Fruit',
    'Pepper',
  ],
  three_sisters: ['Maize', 'Beans', 'Pumpkin', 'Squash', 'Cowpea', 'Yardlong Beans'],
  medicinal_guild: [
    'Moringa',
    'Tulsi',
    'Aloe Vera',
    'Lemongrass',
    'Neem',
    'Brahmi',
    'Ashwagandha',
    'Castor',
    'Agathi',
  ],
};

export function getRecommendedPlantsForBed(type: BedType): string[] {
  return BED_PLANT_CATALOG[type] ?? [];
}
