import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    loadingContainer: { alignItems: 'center', justifyContent: 'center' },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 10,
      backgroundColor: theme.backgroundSecondary,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    closeButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      backgroundColor: theme.primary,
    },
    headerTitle: { flex: 1, fontSize: 17, fontWeight: '700', color: theme.text },
    headerSpacer: { width: 32 },
    progressContainer: {
      backgroundColor: theme.backgroundSecondary,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      paddingBottom: 10,
    },
    stepRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginHorizontal: 8,
      paddingTop: 12,
      paddingBottom: 4,
    },
    stepCol: { alignItems: 'center', width: 44 },
    stepCircle: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.borderLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    stepCircleActive: { backgroundColor: theme.primary },
    stepCircleComplete: {
      backgroundColor: theme.primaryLight,
      borderWidth: 2,
      borderColor: theme.primary,
    },
    stepCircleText: { fontSize: 12, fontWeight: '700' as const, color: theme.textTertiary },
    stepCircleTextActive: { color: theme.textInverse },
    stepConnector: {
      flex: 1,
      height: 2,
      backgroundColor: theme.borderLight,
      marginTop: 12,
      alignSelf: 'flex-start' as const,
    },
    stepConnectorFilled: { backgroundColor: theme.primary },
    progressLabel: { fontSize: 9, color: theme.textTertiary, textAlign: 'center' as const },
    progressLabelActive: { color: theme.primary, fontWeight: '600' as const },
    progressLabelComplete: { color: theme.textSecondary },
    stepContent: { flex: 1 },
    stepContainer: { padding: 16, paddingBottom: 40 },
    stepTitle: { fontSize: 20, fontWeight: '700', color: theme.text, marginBottom: 6 },
    stepSubtitle: { fontSize: 14, color: theme.textSecondary, marginBottom: 16 },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 8,
      backgroundColor: theme.backgroundSecondary,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    backButton: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingHorizontal: 16,
      height: 44,
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: theme.border,
      backgroundColor: theme.primary,
    },
    backText: { color: theme.textInverse, fontSize: 14, fontWeight: '600' as const },
    nextButton: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingHorizontal: 16,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.primary,
    },
    nextButtonDisabled: { backgroundColor: theme.textTertiary },
    nextText: { color: theme.textInverse, fontWeight: '700', fontSize: 14 },
    blockedBanner: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 8,
      marginHorizontal: 16,
      marginBottom: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 8,
      backgroundColor: theme.errorLight,
      borderWidth: 1,
      borderColor: theme.error,
    },
    blockedBannerText: { flex: 1, fontSize: 12, color: theme.error, lineHeight: 17 },
    stepCounterRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 6,
      paddingHorizontal: 16,
      paddingTop: 4,
    },
    stepCounterText: { fontSize: 11, fontWeight: '600' as const, color: theme.textSecondary },
    stepSubtitleText: { fontSize: 11, color: theme.textTertiary, flexShrink: 1 },
    // ── Discard-changes modal ─────────────────────────────────────────────────
    discardOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
      paddingHorizontal: 32,
    },
    discardCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 20,
      padding: 28,
      alignItems: 'center' as const,
      width: '100%',
      maxWidth: 340,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 24,
      elevation: 8,
    },
    discardIconWrap: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.errorLight,
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
      marginBottom: 16,
    },
    discardTitle: {
      fontSize: 19,
      fontWeight: '700' as const,
      color: theme.text,
      marginBottom: 8,
    },
    discardMessage: {
      fontSize: 14,
      color: theme.textSecondary,
      textAlign: 'center' as const,
      lineHeight: 20,
      marginBottom: 24,
    },
    discardActions: {
      flexDirection: 'row' as const,
      gap: 12,
      width: '100%',
    },
    discardKeepButton: {
      flex: 1,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 6,
      paddingVertical: 13,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    discardKeepText: {
      fontSize: 14,
      fontWeight: '600' as const,
      color: theme.primary,
    },
    discardButton: {
      flex: 1,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 6,
      paddingVertical: 13,
      borderRadius: 12,
      backgroundColor: theme.error,
    },
    discardButtonText: {
      fontSize: 14,
      fontWeight: '600' as const,
      color: theme.textInverse,
    },
    blockedText: {
      flex: 1,
      fontSize: 12,
      color: theme.error,
      backgroundColor: theme.errorLight,
      padding: 8,
      borderRadius: 6,
    },
    // Step 1 — type grid
    typeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    typeCard: {
      width: '47%',
      padding: 14,
      borderRadius: 10,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1.5,
      borderColor: theme.border,
      alignItems: 'center',
    },
    typeCardSelected: { borderColor: theme.primary, backgroundColor: theme.primaryLight },
    typeCardDimmed: { opacity: 0.5 },
    typeEmoji: { fontSize: 28, marginBottom: 6 },
    typeLabel: { fontSize: 13, fontWeight: '600', color: theme.text, textAlign: 'center' },
    typeLabelSelected: { color: theme.primary },
    typeDesc: { fontSize: 11, color: theme.textSecondary, textAlign: 'center', marginTop: 4 },
    typeInfoTag: {
      marginTop: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: theme.primaryLight,
      alignSelf: 'center' as const,
    },
    typeInfoTagText: { fontSize: 10, fontWeight: '600' as const, color: theme.primary },
    // Step 1 — Tamil label under card title
    btTamilLabel: {
      fontSize: 11,
      color: theme.textSecondary,
      textAlign: 'center' as const,
      marginTop: 2,
      fontStyle: 'italic' as const,
    },
    // Step 1 — Ideal season badge overlaid on card
    btIdealBadge: {
      position: 'absolute' as const,
      top: 6,
      right: 6,
      backgroundColor: theme.success,
      borderRadius: 8,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    btIdealBadgeText: { fontSize: 9, fontWeight: '700' as const, color: theme.textInverse },
    // Step 1 — Season context banner
    btSeasonBanner: {
      backgroundColor: theme.infoLight,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.info,
    },
    btSeasonBannerText: { fontSize: 12, color: theme.infoDark, fontWeight: '500' as const },
    // Step 1 — Quick-start goal chips
    btGoalLabel: {
      fontSize: 10,
      fontWeight: '700' as const,
      letterSpacing: 1.2,
      color: theme.textTertiary,
      marginBottom: 10,
    },
    btGoalRow: {
      flexDirection: 'row' as const,
      flexWrap: 'wrap' as const,
      gap: 8,
      marginBottom: 16,
    },
    btGoalChip: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    btGoalChipSelected: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    btGoalIcon: { fontSize: 16 },
    btGoalText: { fontSize: 13, fontWeight: '600' as const, color: theme.textSecondary },
    btGoalTextSelected: { color: theme.primary },
    // Step 1 — All types divider
    btAllTypesLabel: {
      fontSize: 10,
      fontWeight: '700' as const,
      letterSpacing: 1.2,
      color: theme.textTertiary,
      marginBottom: 10,
    },
    // Field groups
    fieldGroup: { marginBottom: 16 },
    fieldLabelRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 6,
      marginBottom: 8,
    },
    fieldLabel: { fontSize: 13, fontWeight: '600', color: theme.text },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    chip: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 18,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1.5,
      borderColor: theme.border,
      alignItems: 'center',
    },
    chipSelected: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    chipLabel: { fontSize: 12, fontWeight: '500' as const, color: theme.textTertiary },
    chipLabelSelected: { color: theme.primary, fontWeight: '700' as const },
    chipHint: { fontSize: 10, color: theme.textTertiary, marginTop: 1 },
    chipHintSelected: { color: theme.primary },
    switchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: theme.borderLight,
      marginTop: 4,
    },
    switchLabelBlock: { flex: 1, marginRight: 12 },
    switchHint: { fontSize: 11, color: theme.textSecondary, marginTop: 2 },
    switchTrack: {
      width: 44,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.border,
      justifyContent: 'center',
      paddingHorizontal: 3,
    },
    switchTrackActive: { backgroundColor: theme.primary },
    switchThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: theme.backgroundSecondary,
      alignSelf: 'flex-start' as const,
    },
    switchThumbActive: { alignSelf: 'flex-end' as const },
    blockAlert: {
      backgroundColor: theme.errorLight,
      borderRadius: 8,
      padding: 12,
      marginTop: 4,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: theme.error,
    },
    blockAlertText: { color: theme.error, fontSize: 13 },
    sunlightWarning: {
      backgroundColor: theme.warningLight,
      borderRadius: 8,
      padding: 10,
      marginTop: 8,
      borderWidth: 1,
      borderColor: theme.warning,
    },
    sunlightWarningText: { color: theme.warning, fontSize: 12 },
    // Step 3 — size
    recommendationCard: {
      backgroundColor: theme.primaryLight,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.primary,
    },
    recommendationTitle: { fontSize: 12, color: theme.primary, fontWeight: '600', marginBottom: 4 },
    recommendationValue: { fontSize: 18, fontWeight: '700', color: theme.primary },
    recommendationRationale: { fontSize: 12, color: theme.primary, marginTop: 4 },
    areaBadge: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 6,
      padding: 10,
      marginVertical: 8,
      alignItems: 'center',
    },
    areaText: { fontSize: 16, fontWeight: '700', color: theme.text },
    // Step 4 — guild
    infoBadge: {
      backgroundColor: theme.infoLight,
      borderRadius: 6,
      padding: 10,
      marginBottom: 12,
    },
    infoBadgeText: { color: theme.infoDark, fontSize: 12 },
    namePreviewRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
    },
    namePreviewText: {
      color: theme.primary,
      fontSize: 14,
      fontWeight: '600' as const,
      flex: 1,
    },
    nameAutoRevertText: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: '600' as const,
      marginTop: 6,
    },
    sequenceCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 8,
      padding: 12,
      marginBottom: 12,
    },
    sequenceTitle: { fontSize: 13, fontWeight: '600', color: theme.text, marginBottom: 8 },
    sequenceRow: { flexDirection: 'row', gap: 8, marginBottom: 4 },
    sequenceWeek: { fontSize: 12, color: theme.primary, fontWeight: '600', width: 48 },
    sequenceAction: { flex: 1, fontSize: 12, color: theme.textSecondary },
    sectionLabel: { fontSize: 14, fontWeight: '700', color: theme.text, marginBottom: 8 },
    plantRowCard: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      marginBottom: 8,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
    },
    plantRowCardSelected: { borderColor: theme.primary, backgroundColor: theme.primaryLight },
    plantRowCardBlocked: { borderColor: theme.border, opacity: 0.6 },
    plantRowInfo: { flex: 1 },
    plantRowName: { fontSize: 14, fontWeight: '600', color: theme.text },
    plantRowNameBlocked: { color: theme.textSecondary },
    plantRowMeta: { fontSize: 11, color: theme.textSecondary, marginTop: 2 },
    antagonistWarning: { fontSize: 11, color: theme.error, marginTop: 3 },
    selectedCheck: { fontSize: 18, color: theme.primary },
    accumulatorCard: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 8,
      padding: 12,
      marginBottom: 8,
    },
    accumulatorName: { fontSize: 14, fontWeight: '600', color: theme.text },
    accumulatorDesc: { fontSize: 12, color: theme.textSecondary, marginTop: 2 },
    accumulatorMeta: { fontSize: 11, color: theme.primary, marginTop: 4 },
    // Step 6 — confirm
    textInput: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      padding: 12,
      color: theme.text,
      backgroundColor: theme.backgroundSecondary,
    },
    textArea: { minHeight: 80, textAlignVertical: 'top' },
    summaryCard: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 8,
      padding: 12,
      marginTop: 16,
    },
    summaryTitle: { fontSize: 14, fontWeight: '700', color: theme.text, marginBottom: 8 },
    summaryRow: { fontSize: 13, color: theme.textSecondary, marginBottom: 4 },
    summaryItemRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
    summaryItemIcon: { width: 18, textAlign: 'center' },
    summaryItemValue: { flex: 1, fontSize: 13, color: theme.text },
    autoTasksCard: {
      backgroundColor: theme.primaryLight,
      borderRadius: 8,
      padding: 12,
      marginTop: 12,
      borderWidth: 1,
      borderColor: theme.primary,
    },
    autoTasksTitle: { fontSize: 13, fontWeight: '600', color: theme.primary, marginBottom: 6 },
    autoTaskRow: { fontSize: 12, color: theme.primary, marginBottom: 3 },
    // Stepper (legacy — kept for other steps)
    stepperRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 6 },
    stepperLabel: { flex: 1, color: theme.text },
    stepperButton: {
      padding: 8,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 4,
      marginHorizontal: 4,
    },
    stepperBtnText: { color: theme.text, fontWeight: 'bold' },
    stepperValue: { color: theme.text, minWidth: 40, textAlign: 'center' },
    sectionLabelMt: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 8,
      marginTop: 16,
    },
    loadingSpinner: { marginTop: 32 },
    diagramSectionLabel: { marginTop: 16, marginBottom: 8 },
    // Step 3 — redesigned size controls
    szRecCard: {
      backgroundColor: theme.primaryLight,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.primary,
      padding: 16,
      marginBottom: 20,
    },
    szRecHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 12,
    },
    szRecTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.primary,
      flex: 1,
      marginRight: 8,
    },
    szRecTags: {
      fontSize: 11,
      color: theme.textSecondary,
      textAlign: 'right',
      flexShrink: 1,
    },
    szOptimalLabel: {
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 1.2,
      color: theme.textTertiary,
      marginBottom: 4,
    },
    szSizeRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      marginBottom: 8,
    },
    szSizeValue: { fontSize: 40, fontWeight: '800', color: theme.primary },
    szSizeSep: { fontSize: 28, fontWeight: '400', color: theme.primary },
    szSizeUnit: { fontSize: 16, fontWeight: '400', color: theme.primary, marginLeft: 2 },
    szRationale: {
      fontSize: 12,
      color: theme.textSecondary,
      lineHeight: 17,
      marginBottom: 14,
    },
    szMetricsRow: {
      flexDirection: 'row',
      backgroundColor: theme.primary,
      borderRadius: 8,
      overflow: 'hidden',
    },
    szMetricChip: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 10,
    },
    szMetricDivider: { width: 1, backgroundColor: theme.primaryDark },
    szMetricValue: { fontSize: 14, fontWeight: '700', color: theme.textInverse },
    szMetricLabel: { fontSize: 10, color: theme.textInverse, marginTop: 2 },
    szSectionLabel: {
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 1.2,
      color: theme.textTertiary,
      marginBottom: 12,
    },
    szSectionLabelSpaced: {
      fontSize: 10,
      fontWeight: '700' as const,
      letterSpacing: 1.2,
      color: theme.textTertiary,
      marginBottom: 12,
      marginTop: 20,
    },
    // Step 3 — unit toggle + arm's reach hint
    szCustomHeader: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      marginBottom: 8,
    },
    szUnitToggle: {
      flexDirection: 'row' as const,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      overflow: 'hidden' as const,
    },
    szUnitBtn: {
      paddingHorizontal: 14,
      paddingVertical: 5,
      backgroundColor: theme.backgroundSecondary,
    },
    szUnitBtnActive: { backgroundColor: theme.primary },
    szUnitBtnText: { fontSize: 13, fontWeight: '600' as const, color: theme.textSecondary },
    szUnitBtnTextActive: { color: theme.textInverse },
    szArmReachHint: {
      backgroundColor: theme.warningLight,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 7,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.warning,
    },
    szArmReachText: { fontSize: 11, color: theme.warning, fontWeight: '500' as const },
    szStepperRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    szStepperLabel: { fontSize: 15, color: theme.text, fontWeight: '500' },
    szStepperControls: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    szCircleBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
    },
    szCircleBtnMinus: { backgroundColor: theme.backgroundTertiary },
    szCircleBtnPlus: { backgroundColor: theme.primary },
    szCircleBtnDisabled: { opacity: 0.3 },
    szCircleBtnText: { fontSize: 20, fontWeight: '400', color: theme.text, lineHeight: 24 },
    szCircleBtnTextPlus: { color: theme.textInverse },
    szCircleBtnTextDisabled: {},
    szStepperValue: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.text,
      minWidth: 52,
      textAlign: 'center',
    },
    szStepperUnit: { fontSize: 13, fontWeight: '400', color: theme.textSecondary },
    // ── Guild Template Step (gt*) ─────────────────────────────────────────────
    gtSectionHeader: {
      fontSize: 10,
      fontWeight: '700' as const,
      letterSpacing: 1.2,
      color: theme.textTertiary,
      marginBottom: 10,
      marginTop: 4,
    },
    gtSectionHeaderMt: { marginTop: 24 },
    // Plant row card
    gtPlantCard: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      padding: 12,
      marginBottom: 8,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    gtPlantCardSelected: { borderColor: theme.primary, backgroundColor: theme.primaryLight },
    gtPlantCardBlocked: { opacity: 0.5 },
    gtEmojiCircle: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      marginRight: 12,
    },
    gtEmojiCircleSelected: { backgroundColor: theme.primary },
    gtEmoji: { fontSize: 22 },
    gtPlantMeta: { flex: 1 },
    gtPlantNameRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 6,
      flexWrap: 'wrap' as const,
    },
    gtPlantName: { fontSize: 14, fontWeight: '700' as const, color: theme.text, flexShrink: 1 as const },
    gtPlantNameBlocked: { color: theme.textTertiary },
    gtTamilName: {
      fontSize: 11,
      color: theme.textSecondary,
      fontStyle: 'italic' as const,
      marginBottom: 3,
      marginTop: 1,
    },
    gtMarketBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      backgroundColor: theme.accent,
    },
    gtMarketBadgeText: { fontSize: 9, fontWeight: '700' as const, color: theme.textInverse },
    gtHarvestBadge: {
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 8,
      backgroundColor: theme.successLight,
      borderWidth: 1,
      borderColor: theme.success,
    },
    gtHarvestBadgeText: { fontSize: 9, fontWeight: '600' as const, color: theme.success },
    gtBadgeRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      flexWrap: 'wrap' as const,
      gap: 6,
      rowGap: 4,
      marginTop: 5,
    },
    gtLayerBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: theme.backgroundTertiary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    gtLayerBadgeSelected: { backgroundColor: theme.primary, borderColor: theme.primary },
    gtLayerBadgeText: { fontSize: 10, fontWeight: '600' as const, color: theme.textSecondary },
    gtLayerBadgeTextSelected: { color: theme.textInverse },
    gtNFixerBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: theme.successLight,
      borderWidth: 1,
      borderColor: theme.success,
    },
    gtNFixerBadgeText: { fontSize: 10, fontWeight: '600' as const, color: theme.success },
    gtAntagonistText: { fontSize: 11, color: theme.error, marginTop: 5 },
    gtPlantRight: { alignItems: 'flex-end' as const, gap: 6, marginLeft: 10, flexShrink: 0 as const },
    gtSpacingBlock: { alignItems: 'flex-end' as const },
    gtSpacingLabel: {
      fontSize: 8,
      fontWeight: '700' as const,
      letterSpacing: 0.8,
      color: theme.textTertiary,
      textAlign: 'right' as const,
    },
    gtSpacingTag: { fontSize: 11, fontWeight: '600' as const, color: theme.textSecondary },
    gtSpacingCompact: {
      fontSize: 11,
      color: theme.accent,
      fontWeight: '500' as const,
      letterSpacing: 0.1,
    },
    gtSelectCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: theme.border,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    gtSelectCircleActive: { borderColor: theme.primary, backgroundColor: theme.primary },
    gtCountText: { fontSize: 11, fontWeight: '700' as const, color: theme.textInverse },
    // ── Quantity stepper (Guild step) ─────────────────────────────────────────
    gtQtyStepper: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 6,
    },
    gtQtyBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    gtQtyBtnMinus: {
      backgroundColor: theme.backgroundTertiary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    gtQtyBtnPlus: { backgroundColor: theme.primary },
    gtQtyBtnDisabled: { opacity: 0.3 },
    gtQtyBtnText: { fontSize: 16, fontWeight: '600' as const, color: theme.text, lineHeight: 18 },
    gtQtyBtnTextPlus: { color: theme.textInverse },
    gtQtyValue: {
      fontSize: 13,
      fontWeight: '700' as const,
      color: theme.text,
      minWidth: 18,
      textAlign: 'center' as const,
    },
    gtQtyValueZero: { color: theme.textTertiary, fontWeight: '500' as const },
    // Placeholder/template banner on Guild step
    gtTemplateBanner: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 8,
      backgroundColor: theme.infoLight,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: theme.info,
    },
    gtTemplateBannerText: {
      flex: 1,
      fontSize: 12,
      color: theme.infoDark,
      lineHeight: 17,
    },
    // Companion section
    gtCompanionRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 10,
      paddingVertical: 9,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    gtCompanionEmoji: { fontSize: 18, width: 24, textAlign: 'center' as const },
    gtCompanionName: { fontSize: 13, fontWeight: '500' as const, color: theme.text },
    gtCompanionNameBlock: { flex: 1 },
    gtCompanionFitText: {
      fontSize: 10,
      color: theme.textTertiary,
      marginTop: 2,
    },
    gtAccFitText: {
      fontSize: 10,
      color: theme.textTertiary,
      marginTop: 4,
    },
    // Add / Added pill button (shared by companions + accumulators)
    gtAddBtn: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: theme.primary,
    },
    gtAddedBtn: { backgroundColor: theme.primary },
    gtAddBtnText: { fontSize: 12, fontWeight: '700' as const, color: theme.primary },
    gtAddedBtnText: { color: theme.textInverse },
    // Accumulator card
    gtAccSubtitle: { fontSize: 13, color: theme.textSecondary, marginBottom: 12, marginTop: -4 },
    gtAccCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 10,
      padding: 12,
      marginBottom: 10,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    gtAccCardSelected: { borderColor: theme.primary, backgroundColor: theme.primaryLight },
    gtAccHeader: {
      flexDirection: 'row' as const,
      alignItems: 'flex-start' as const,
      justifyContent: 'space-between' as const,
      marginBottom: 8,
    },
    gtAccNameBlock: { flex: 1, marginRight: 10 },
    gtAccName: { fontSize: 14, fontWeight: '700' as const, color: theme.text },
    gtAccNameSelected: { color: theme.primary },
    gtAccTamil: { fontSize: 12, color: theme.textSecondary, marginTop: 2 },
    gtIntervalText: { fontSize: 12, color: theme.textSecondary, marginBottom: 8 },
    gtIntervalTextSelected: { color: theme.primary },
    gtNutrientRow: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 5 },
    gtNutrientChip: {
      paddingHorizontal: 9,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: theme.primaryLight,
    },
    gtNutrientChipSelected: { backgroundColor: theme.borderLight },
    gtNutrientText: { fontSize: 10, fontWeight: '700' as const, color: theme.primary },
    gtNutrientTextSelected: { color: theme.primary },
    // Plant count chip (beside spacing tag)
    gtPlantCountTag: { fontSize: 10, color: theme.textTertiary, textAlign: 'right' as const },
    // Drainage warning badge
    gtDrainageBadge: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
      backgroundColor: theme.warning,
      marginTop: 4,
      alignSelf: 'flex-start' as const,
    },
    gtDrainageBadgeText: { fontSize: 9, fontWeight: '700' as const, color: theme.textInverse },
    // Rotation hint banner
    gtRotationHint: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 8,
      paddingVertical: 9,
      paddingHorizontal: 12,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    gtRotationHintText: { fontSize: 12, color: theme.textSecondary },
    // ── Size presets row ─────────────────────────────────────────────────────
    szPresetRow: {
      flexDirection: 'row' as const,
      gap: 8,
      marginBottom: 20,
    },
    szPresetChip: {
      flex: 1,
      padding: 10,
      borderRadius: 10,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1.5,
      borderColor: theme.border,
      alignItems: 'center' as const,
    },
    szPresetChipSelected: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    szPresetChipSize: {
      fontSize: 13,
      fontWeight: '700' as const,
      color: theme.textSecondary,
      marginBottom: 2,
    },
    szPresetChipSizeSelected: { color: theme.primary },
    szPresetChipName: {
      fontSize: 11,
      fontWeight: '600' as const,
      color: theme.textTertiary,
    },
    szPresetChipNameSelected: { color: theme.primary },
    szPresetChipHint: {
      fontSize: 10,
      color: theme.textTertiary,
      marginTop: 2,
    },
    szPresetChipHintSelected: { color: theme.primary },
    szPresetCheck: { fontSize: 10, color: theme.primary, marginTop: 2 },
    // ── Prep card ────────────────────────────────────────────────────────────
    szPrepCard: {
      borderWidth: 1.5,
      borderColor: theme.warning,
      borderRadius: 12,
      padding: 14,
      marginTop: 20,
      backgroundColor: theme.warningLight,
    },
    szPrepCardTitle: {
      fontSize: 13,
      fontWeight: '700' as const,
      color: theme.warning,
      flex: 1,
    },
    szPrepStepRow: {
      flexDirection: 'row' as const,
      gap: 10,
      marginBottom: 10,
      alignItems: 'flex-start' as const,
    },
    szPrepStepNumber: {
      minWidth: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: theme.warning,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    szPrepStepNumberText: {
      fontSize: 10,
      fontWeight: '800' as const,
      color: theme.textInverse,
    },
    szPrepToggleRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
    },
    szPrepFirstStep: { marginTop: 12 },
    szPrepChevron: {
      fontSize: 11,
      fontWeight: '700' as const,
      color: theme.warning,
    },
    szPrepStepContent: { flex: 1 },
    szPrepStepText: {
      fontSize: 13,
      fontWeight: '600' as const,
      color: theme.text,
    },
    szPrepStepDetail: {
      fontSize: 11,
      color: theme.textSecondary,
      marginTop: 2,
      lineHeight: 16,
    },

    // Guild step — use full crop plan button
    gtUseFullPlanBtn: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      backgroundColor: theme.primaryLight,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.primary,
    },
    gtUseFullPlanBtnApplied: {
      backgroundColor: theme.successLight,
      borderColor: theme.success,
    },
    // Quick Start — compact two-line card
    gtQuickStartTextCol: {
      flex: 1,
      marginRight: 10,
    },
    gtQuickStartTitle: {
      fontSize: 13,
      fontWeight: '700' as const,
      color: theme.primary,
    },
    gtQuickStartTitleApplied: {
      color: theme.success,
    },
    gtQuickStartSubtitle: {
      fontSize: 11,
      color: theme.textSecondary,
      marginTop: 1,
    },
    gtQuickStartPill: {
      backgroundColor: theme.primary,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    gtQuickStartPillApplied: {
      backgroundColor: theme.success,
    },
    gtQuickStartPillText: {
      fontSize: 12,
      fontWeight: '700' as const,
      color: theme.textInverse,
    },
    gtQuickStartIconBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1.5,
      borderColor: theme.error,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    gtEmptyHint: {
      fontSize: 12,
      color: theme.textSecondary,
      marginBottom: 12,
      marginTop: -4,
    },
    // Guild step — benefit explanation line
    gtBenefitLine: {
      fontSize: 11,
      color: theme.primary,
      marginTop: 3,
      lineHeight: 15,
    },
    // Guild step — benefit tag badge (non-legume)
    gtBenefitTagBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: theme.infoLight,
      borderWidth: 1,
      borderColor: theme.info,
    },
    gtBenefitTagBadgeText: {
      fontSize: 10,
      fontWeight: '600' as const,
      color: theme.infoDark,
    },
    gtBedTypeChip: {
      alignSelf: 'flex-start' as const,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      backgroundColor: theme.primaryLight,
      borderWidth: 1,
      borderColor: theme.primary,
      marginBottom: 12,
    },
    gtBedTypeChipText: {
      fontSize: 12,
      fontWeight: '600' as const,
      color: theme.primary,
    },
    gtBedBanner: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      backgroundColor: theme.primaryLight,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.successBorder,
      marginBottom: 10,
    },
    gtBedBannerLabel: {
      fontSize: 15,
      fontWeight: '700' as const,
      color: theme.primary,
      lineHeight: 20,
    },
    gtBedBannerDims: {
      fontSize: 11,
      color: theme.textTertiary,
      marginTop: 2,
      letterSpacing: 0.2,
    },
    // Guild step — harvest mini timeline
    gtHarvestRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      marginBottom: 8,
    },
    gtHarvestLabelCol: {
      width: 120,
    },
    gtHarvestName: {
      fontSize: 12,
      fontWeight: '600' as const,
      color: theme.text,
    },
    gtHarvestBarTrack: {
      flex: 1,
      height: 8,
      backgroundColor: theme.borderLight,
      borderRadius: 4,
      overflow: 'hidden' as const,
    },
    gtHarvestBar: {
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.success,
    },
    gtHarvestDays: {
      fontSize: 11,
      color: theme.textSecondary,
      fontWeight: '600' as const,
      marginLeft: 8,
      width: 34,
    },
    // Layout step — top-down bed map (Step 5 hero)
    tdmCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      padding: 10,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    tdmHeader: {
      flexDirection: 'row' as const,
      justifyContent: 'space-between' as const,
      alignItems: 'baseline' as const,
      marginBottom: 10,
    },
    tdmEyebrow: {
      fontSize: 10,
      fontWeight: '700' as const,
      letterSpacing: 0.9,
      color: theme.textTertiary,
    },
    tdmMeta: {
      fontSize: 10,
      color: theme.textTertiary,
      letterSpacing: 0.2,
    },
    tdmMapWrap: {
      flexDirection: 'column' as const,
      alignItems: 'stretch' as const,
      gap: 6,
    },
    // Ruler + canvas live in this row so the ruler stretches to the canvas
    // height only (not the compass/legend), keeping meter ticks aligned to the
    // grid at base zoom.
    tdmPlotRow: {
      flexDirection: 'row' as const,
      alignItems: 'stretch' as const,
      gap: 6,
    },
    tdmPlotCol: {
      flex: 1,
    },
    tdmRuler: {
      width: 26,
      position: 'relative' as const,
    },
    tdmRulerTick: {
      position: 'absolute' as const,
      right: 0,
      fontSize: 10,
      color: theme.textTertiary,
      transform: [{ translateY: -6 }],
      textAlign: 'right' as const,
    },
    tdmCompass: {
      flexDirection: 'row' as const,
      justifyContent: 'space-between' as const,
      alignItems: 'center' as const,
      // Indent past the ruler (width 26 + row gap 6) so the N/S markers sit over
      // the canvas, matching where they sat when nested inside the frame.
      paddingLeft: 32,
    },
    tdmCompassN: {
      fontSize: 10,
      color: theme.primary,
      fontWeight: '600' as const,
      letterSpacing: 0.3,
    },
    tdmCompassS: {
      fontSize: 10,
      color: theme.accent,
      fontWeight: '500' as const,
      letterSpacing: 0.3,
    },
    tdmCompassDim: {
      fontSize: 10,
      color: theme.textTertiary,
      letterSpacing: 0.2,
    },
    tdmCanvasFrame: {
      position: 'relative' as const,
      overflow: 'hidden' as const,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: theme.borderDark,
      backgroundColor: theme.accentLight,
    },
    tdmCanvas: {
      position: 'absolute' as const,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    tdmGridLineH: {
      position: 'absolute' as const,
      left: 0,
      right: 0,
      height: 1,
      backgroundColor: theme.borderDark,
      opacity: 0.55,
    },
    tdmGridLineV: {
      position: 'absolute' as const,
      top: 0,
      bottom: 0,
      width: 1,
      backgroundColor: theme.borderDark,
      opacity: 0.55,
    },
    tdmRowCenterline: {
      position: 'absolute' as const,
      left: 0,
      right: 0,
      height: 1,
      borderBottomWidth: 1,
      borderBottomColor: theme.primary,
      borderStyle: 'dashed' as const,
      opacity: 0.55,
      transform: [{ translateY: -0.5 }],
    },
    tdmRowTag: {
      position: 'absolute' as const,
      left: 2,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.primary,
      paddingHorizontal: 6,
      paddingVertical: 1,
      borderRadius: 999,
      // Centre the pill on the row centerline (≈17px tall → lift half its height).
      // Rendered after the pins so the opaque pill reads cleanly on top of the
      // westmost pin at the bed edge.
      transform: [{ translateY: -9 }],
    },
    tdmRowTagText: {
      fontSize: 11,
      color: theme.primary,
      fontWeight: '700' as const,
      letterSpacing: 0.2,
    },
    tdmRowTagWarn: {
      fontSize: 11,
      color: theme.warning,
      fontWeight: '700' as const,
    },
    tdmPathStrip: {
      position: 'absolute' as const,
      left: 0,
      right: 0,
      backgroundColor: theme.borderDark,
      opacity: 0.12,
    },
    tdmPathStripTop: {
      top: 0,
    },
    tdmPathStripBottom: {
      bottom: 0,
    },
    tdmEdgeStrip: {
      position: 'absolute' as const,
      left: 0,
      right: 0,
      backgroundColor: theme.borderDark,
      opacity: 0.12,
    },
    tdmEdgeStripTop: { top: 0 },
    tdmEdgeStripBottom: { bottom: 0 },
    tdmStripLabel: {
      position: 'absolute' as const,
      fontSize: 9,
      color: theme.textTertiary,
      fontWeight: '600' as const,
      letterSpacing: 0.2,
    },
    tdmStripLabelN: {
      top: 1,
      left: 0,
      right: 0,
      textAlign: 'center' as const,
    },
    tdmStripLabelS: {
      bottom: 1,
      left: 0,
      right: 0,
      textAlign: 'center' as const,
    },
    // Zero-width anchor placed at the gap midpoint; alignItems centers the chip
    // exactly on that point regardless of digit count. Sits just below the line.
    tdmGapCaret: {
      position: 'absolute' as const,
      width: 0,
      alignItems: 'center' as const,
      transform: [{ translateY: 7 }],
    },
    tdmGapCaretText: {
      color: theme.accent,
      fontWeight: '600' as const,
      letterSpacing: 0.1,
      paddingHorizontal: 2,
      borderRadius: 3,
      overflow: 'hidden' as const,
      backgroundColor: theme.backgroundSecondary,
    },
    tdmZoomHint: {
      position: 'absolute' as const,
      top: 6,
      right: 6,
      backgroundColor: theme.backgroundSecondary,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 4,
    },
    tdmZoomHintText: {
      fontSize: 10,
      color: theme.textSecondary,
      fontWeight: '500' as const,
    },
    tdmZoomReset: {
      position: 'absolute' as const,
      top: 6,
      left: 6,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    tdmZoomControls: {
      position: 'absolute' as const,
      right: 6,
      top: '50%' as const,
      transform: [{ translateY: -52 }],
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 16,
      paddingVertical: 4,
      paddingHorizontal: 2,
      gap: 4,
      alignItems: 'center' as const,
    },
    tdmZoomBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    tdmZoomBtnDisabled: {
      opacity: 0.35,
    },
    tdmExpandButton: {
      position: 'absolute' as const,
      top: 6,
      right: 6,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      paddingHorizontal: 8,
      gap: 4,
    },
    tdmExpandButtonText: {
      fontSize: 10,
      color: theme.textSecondary,
      fontWeight: '500' as const,
    },
    tdmModalGestureRoot: {
      flex: 1,
    },
    tdmModalRoot: {
      flex: 1,
      backgroundColor: theme.background,
    },
    tdmModalHeader: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
    },
    tdmModalTitle: {
      fontSize: 16,
      fontWeight: '600' as const,
      color: theme.text,
    },
    tdmModalClose: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    tdmModalCanvasWrap: {
      flex: 1,
      padding: 12,
    },
    tdmPinWrap: {
      position: 'absolute' as const,
      alignItems: 'center' as const,
      marginLeft: -16,
      marginTop: -11,
      width: 32,
    },
    tdmPin: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1.5,
      borderColor: theme.primary,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    tdmPinCompanion: {
      borderStyle: 'dashed' as const,
      borderColor: theme.purpleDark,
      backgroundColor: theme.purpleLight,
    },
    tdmPinGround: {
      borderColor: theme.accent,
      backgroundColor: theme.accentLight,
      width: 18,
      height: 18,
      borderRadius: 9,
    },
    tdmPinEmoji: {
      fontSize: 11,
      lineHeight: 13,
    },
    tdmPinLabel: {
      fontSize: 6,
      color: theme.textSecondary,
      marginTop: 1,
      textAlign: 'center' as const,
      letterSpacing: 0.1,
      // Allow short names to center under the pin without being clipped to the
      // narrow pin-wrap width.
      maxWidth: 56,
    },
    tdmOverflowBadge: {
      position: 'absolute' as const,
      bottom: 4,
      left: 4,
      backgroundColor: theme.warningLight,
      borderWidth: 1,
      borderColor: theme.warning,
      paddingHorizontal: 5,
      paddingVertical: 1,
      borderRadius: 4,
    },
    tdmOverflowText: {
      fontSize: 8,
      color: theme.warning,
      fontWeight: '700' as const,
    },
    tdmLegend: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      flexWrap: 'wrap' as const,
      gap: 8,
      marginTop: 6,
      // Align under the canvas (past the ruler gutter), matching the compass.
      paddingLeft: 32,
    },
    tdmLegendItem: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 4,
    },
    tdmLegendSwatch: {
      width: 10,
      height: 10,
      borderRadius: 5,
      borderWidth: 1.5,
    },
    tdmLegendSwatchMain: {
      borderColor: theme.primary,
      backgroundColor: theme.backgroundSecondary,
    },
    tdmLegendSwatchCompanion: {
      borderStyle: 'dashed' as const,
      borderColor: theme.purpleDark,
      backgroundColor: theme.purpleLight,
    },
    tdmLegendText: {
      fontSize: 10,
      color: theme.textSecondary,
    },
    tdmLegendHint: {
      fontSize: 9,
      color: theme.textTertiary,
      marginLeft: 'auto' as const,
      fontStyle: 'italic' as const,
    },
    tdmScaleBar: {
      position: 'absolute' as const,
      bottom: 4,
      right: 4,
      backgroundColor: theme.backgroundSecondary,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    tdmScaleBarText: {
      fontSize: 10,
      color: theme.textTertiary,
      letterSpacing: 0.2,
    },
    blTrellisCard: {
      backgroundColor: theme.warningLight,
      borderRadius: 10,
      padding: 12,
      marginTop: 10,
      borderWidth: 1,
      borderColor: theme.warning,
    },
    blTrellisText: {
      fontSize: 13,
      color: theme.text,
      lineHeight: 19,
    },
    // Step 4 — collapsible section headers
    gtCollapsibleHeader: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
    },
    gtSlotStatus: {
      fontSize: 11,
      color: theme.textSecondary,
      marginTop: 2,
      marginBottom: 6,
    },
    // Layout step — planting schedule
    blScheduleCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      padding: 14,
      marginTop: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    blScheduleTitle: {
      fontSize: 10,
      fontWeight: '700' as const,
      letterSpacing: 1.2,
      color: theme.textTertiary,
      marginBottom: 10,
    },
    blScheduleWeekRow: {
      flexDirection: 'row' as const,
      alignItems: 'flex-start' as const,
      marginBottom: 8,
      gap: 10,
    },
    blScheduleWeekLabel: {
      fontSize: 12,
      fontWeight: '700' as const,
      color: theme.primary,
      width: 56,
    },
    blSchedulePlantNames: {
      flex: 1,
      fontSize: 12,
      color: theme.text,
      lineHeight: 18,
    },

    // ── BedLayoutStep interactive grid ────────────────────────────────────────
    blRemoveBtn: {
      position: 'absolute' as const,
      top: 4,
      right: 4,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: theme.error,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    blRemoveBtnText: {
      fontSize: 10,
      fontWeight: '800' as const,
      color: theme.textInverse,
    },
    // Guild step — auto-companion notification banner
    gtAutoAddedBanner: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      backgroundColor: theme.successLight,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.success,
    },
    gtAutoAddedBannerText: {
      flex: 1,
      fontSize: 12,
      color: theme.success,
      fontWeight: '500' as const,
      lineHeight: 17,
    },
    gtAutoAddedBannerDismiss: {
      fontSize: 18,
      color: theme.success,
      fontWeight: '700' as const,
      marginLeft: 8,
    },

    // Step 5 — Name / Plot tabs at the top of the layout designer
    blLayoutTabs: {
      flexDirection: 'row' as const,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 22,
      padding: 4,
      marginBottom: 12,
      alignSelf: 'stretch' as const,
    },
    blLayoutTab: {
      flex: 1,
      paddingVertical: 9,
      paddingHorizontal: 18,
      borderRadius: 18,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    blLayoutTabActive: {
      backgroundColor: theme.primary,
    },
    blLayoutTabText: {
      fontSize: 14,
      fontWeight: '600' as const,
      color: theme.textSecondary,
    },
    blLayoutTabTextActive: {
      color: theme.textInverse,
      fontWeight: '700' as const,
    },

    // ── Crops tab — companion antagonist warning banner ───────────────────────
    blCompanionWarningBanner: {
      backgroundColor: theme.warningLight,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.warning,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 8,
      gap: 4,
    },
    blCompanionWarningText: {
      fontSize: 12,
      color: theme.warningDark,
      lineHeight: 17,
    },
  });
