import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    scrollArea: { flex: 1 },
    content: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 40 },
    centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
    errorText: { color: theme.error, marginBottom: 12 },
    retryText: { color: theme.primary },
    editButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.card,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    typeBadge: {
      fontSize: 12,
      color: theme.primary,
      borderWidth: 1,
      borderColor: theme.primary,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 3,
      textTransform: 'capitalize',
    },
    restingBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.warningLight ?? '#fef3c7',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 12,
    },
    restingText: { flex: 1, fontSize: 13, color: theme.warning ?? '#f59e0b', fontWeight: '600' },
    endRestText: { fontSize: 12, color: theme.primary, fontWeight: '600' },
    infoRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
    infoText: { fontSize: 14, color: theme.textSecondary },
    raisedBadge: {
      backgroundColor: theme.primaryLight,
      borderRadius: 4,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    raisedBadgeText: { fontSize: 11, color: theme.primary },
    section: { marginTop: 20 },
    sectionTitle: { fontSize: 16, fontWeight: '700', color: theme.text, marginBottom: 10 },
    emptyText: { color: theme.textSecondary, fontStyle: 'italic' },
    // Soil Input Log
    inputLogGrid: { flexDirection: 'row', gap: 8, marginBottom: 12 },
    inputLogItem: {
      flex: 1,
      alignItems: 'center',
      gap: 4,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 8,
      padding: 10,
      borderWidth: 1,
      borderColor: theme.border,
    },
    inputLogLabel: { fontSize: 11, color: theme.textSecondary, textAlign: 'center' },
    inputLogValue: { fontSize: 12, fontWeight: '600', color: theme.text, textAlign: 'center' },
    inputLogHint: { fontSize: 11, color: theme.textTertiary, fontStyle: 'italic' },
    logInputButtons: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    logInputChip: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
    },
    logInputChipText: { fontSize: 12, color: theme.text },
    // Plants
    plantRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    plantName: { fontSize: 14, color: theme.text },
    layerBadge: {
      fontSize: 11,
      color: theme.textSecondary,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 4,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    addPlantButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 12,
      padding: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.primary,
      borderStyle: 'dashed',
    },
    addPlantText: { color: theme.primary, fontSize: 14 },
    // Transition inputs
    transitionRow: { flexDirection: 'row', gap: 6, marginBottom: 6, paddingRight: 12 },
    transitionBullet: { color: theme.primary, fontSize: 14, lineHeight: 20 },
    transitionText: { flex: 1, fontSize: 13, color: theme.text, lineHeight: 20 },
    // Actions
    actions: { flexDirection: 'row', gap: 12, marginTop: 16 },
    actionButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      padding: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
    },
    restButton: { borderColor: theme.warning ?? '#f59e0b' },
    actionText: { color: theme.primary, fontWeight: '600', fontSize: 13 },
    // RotationStatusCard
    rotationCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 10,
      padding: 14,
      borderWidth: 1,
      borderColor: theme.border,
    },
    violationBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.error,
      borderRadius: 6,
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginBottom: 10,
    },
    violationText: { color: theme.textInverse, fontSize: 13, flex: 1 },
    legumeRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    legumeLabel: { color: theme.textSecondary, fontSize: 13 },
    legumeValue: { fontSize: 13, fontWeight: '700' },
    greenManureBanner: {
      flexDirection: 'row',
      gap: 8,
      alignItems: 'flex-start',
      backgroundColor: theme.primaryLight,
      borderRadius: 6,
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginBottom: 10,
    },
    greenManureText: { color: theme.primary, fontSize: 12, flex: 1 },
    checklistTitle: { fontSize: 13, fontWeight: '600', color: theme.text, marginBottom: 8 },
    checklistRow: { flexDirection: 'row', gap: 10, marginBottom: 8, alignItems: 'flex-start' },
    checklistInfo: { flex: 1 },
    checklistRule: { fontSize: 13, fontWeight: '600', color: theme.text },
    checklistDesc: { fontSize: 11, color: theme.textSecondary, marginTop: 1 },
    // Harvest gap alerts
    warningCard: {
      flexDirection: 'row',
      gap: 8,
      alignItems: 'center',
      backgroundColor: theme.warningLight ?? '#fef3c7',
      borderRadius: 6,
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginBottom: 8,
    },
    warningText: { flex: 1, fontSize: 12, color: theme.warning ?? '#f59e0b' },
    // Next-crop chips
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    nextCropChip: {
      backgroundColor: theme.primaryLight,
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    nextCropChipText: { fontSize: 12, color: theme.primary, fontWeight: '600' },
    // Progress bar
    progressBarContainer: {
      height: 6,
      backgroundColor: theme.border,
      borderRadius: 3,
      marginBottom: 4,
      overflow: 'hidden',
    },
    progressBarFill: {
      height: 6,
      backgroundColor: theme.success ?? '#22c55e',
      borderRadius: 3,
    },
    progressLabel: { fontSize: 11, color: theme.textSecondary, marginBottom: 10 },
  });
