import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingBottom: 12,
      backgroundColor: theme.backgroundSecondary,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    backButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    headerTitle: { fontSize: 20, fontWeight: '700', color: theme.text },
    body: { flex: 1 },
    bodyContent: { padding: 16, paddingBottom: 40 },
    fieldLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 6,
      textTransform: 'uppercase',
    },
    fieldInput: {
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: theme.text,
      marginBottom: 16,
    },
    fieldInputMultiline: {
      minHeight: 80,
      textAlignVertical: 'top',
    },
    divider: {
      height: 1,
      backgroundColor: theme.border,
      marginVertical: 8,
    },
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      marginBottom: 4,
    },
    toggleLabel: { fontSize: 15, color: theme.text },
    segmentedRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 16,
    },
    segmentButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      backgroundColor: theme.backgroundSecondary,
    },
    segmentButtonActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    segmentText: { fontSize: 13, color: theme.textSecondary },
    segmentTextActive: { color: theme.primary, fontWeight: '600' },
    saveButton: {
      marginTop: 24,
      backgroundColor: theme.primary,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
    },
    saveButtonDisabled: { opacity: 0.5 },
    saveButtonText: { fontSize: 16, fontWeight: '700', color: theme.textInverse },
    loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    errorText: { color: theme.error, textAlign: 'center', padding: 24 },
  });
