import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingBottom: 12,
      backgroundColor: theme.backgroundSecondary,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    title: { fontSize: 22, fontWeight: '700', color: theme.text },
    bedCount: { fontSize: 13, color: theme.textSecondary },
    errorText: { color: theme.error, marginBottom: 12, textAlign: 'center' },
    retryButton: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      backgroundColor: theme.primary,
      borderRadius: 8,
    },
    retryText: { color: theme.textInverse, fontWeight: '600' },
    legumeBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.warningLight,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    legumeBannerText: { color: theme.warning, fontSize: 13 },
    list: { padding: 12, gap: 12, paddingBottom: 120 },
    emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 40 },
    emptyTitle: { fontSize: 18, fontWeight: '600', color: theme.text, marginTop: 16 },
    emptySubtitle: { color: theme.textSecondary, marginTop: 8, textAlign: 'center' },
    // BedCard styles
    card: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: theme.border,
    },
    cardHeader: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
    cardEmoji: { fontSize: 28, marginRight: 12 },
    cardTitleBlock: { flex: 1 },
    cardName: { fontSize: 16, fontWeight: '700', color: theme.text },
    cardType: { fontSize: 12, color: theme.textSecondary, marginTop: 2 },
    cardMetaBlock: { alignItems: 'flex-end' },
    cardArea: { fontSize: 12, color: theme.textTertiary },
    raisedTag: {
      fontSize: 10,
      color: theme.primary,
      borderWidth: 1,
      borderColor: theme.primary,
      borderRadius: 4,
      paddingHorizontal: 4,
      paddingVertical: 1,
      marginTop: 2,
    },
    barContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 4, gap: 8 },
    barLabel: { fontSize: 11, color: theme.textSecondary, width: 64 },
    barTrack: {
      flex: 1,
      height: 6,
      backgroundColor: theme.border,
      borderRadius: 3,
      overflow: 'hidden',
    },
    barFill: { height: '100%', borderRadius: 3 },
    barValue: { fontSize: 11, color: theme.textSecondary, width: 32, textAlign: 'right' },
  });
