import { StyleSheet, Dimensions } from 'react-native';
import type { Theme } from '@/theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingBottom: 12,
      backgroundColor: theme.backgroundSecondary,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    title: { fontSize: 22, fontWeight: '700', color: theme.text },
    bedCount: { fontSize: 13, color: theme.textSecondary },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    headerIconBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchActiveDot: {
      position: 'absolute',
      bottom: 6,
      right: 6,
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.accent,
    },
    searchExpandedRow: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    searchBackBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchExpandedWrapper: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.background,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.primary,
      paddingHorizontal: 14,
      paddingVertical: 8,
      gap: 8,
    },
    searchExpandedInput: {
      flex: 1,
      fontSize: 16,
      color: theme.text,
      padding: 0,
    },
    errorText: { color: theme.error, marginBottom: 12, textAlign: 'center' },
    retryButton: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      backgroundColor: theme.primary,
      borderRadius: 8,
    },
    retryText: { color: theme.textInverse, fontWeight: '600' },
    legumeBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.warningLight,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    legumeBannerText: { color: theme.warning, fontSize: 13 },
    list: { padding: 12, gap: 12, paddingBottom: 120 },
    emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 40 },
    emptyTitle: { fontSize: 18, fontWeight: '600', color: theme.text, marginTop: 16 },
    emptySubtitle: { color: theme.textSecondary, marginTop: 8, textAlign: 'center' },
    // BedCard — compact row
    card: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      paddingVertical: 12,
      paddingRight: 12,
      paddingLeft: 14,
      borderWidth: 1,
      borderColor: theme.border,
      overflow: 'hidden',
    },
    cardStripe: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: 4,
    },
    cardEmoji: { fontSize: 26, marginRight: 12 },
    cardContent: { flex: 1 },
    cardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    cardName: { flexShrink: 1, fontSize: 16, fontWeight: '700', color: theme.text },
    cardType: {
      fontSize: 12,
      color: theme.textSecondary,
      marginTop: 1,
      textTransform: 'capitalize',
    },
    raisedTag: {
      fontSize: 10,
      color: theme.primary,
      borderWidth: 1,
      borderColor: theme.primary,
      borderRadius: 4,
      paddingHorizontal: 4,
      paddingVertical: 1,
    },
    cardMetaRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 12, marginTop: 6 },
    metaChip: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    metaChipText: { fontSize: 11, color: theme.textSecondary, fontWeight: '500' },
    // Swipe actions
    swipeActions: { flexDirection: 'row' },
    swipeEditAction: {
      width: 72,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    swipeDeleteAction: {
      width: 72,
      backgroundColor: theme.error,
      alignItems: 'center',
      justifyContent: 'center',
      borderTopRightRadius: 12,
      borderBottomRightRadius: 12,
    },
    swipeActionText: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.textInverse,
      marginTop: 2,
    },
    // Undo toast
    undoToast: {
      position: 'absolute',
      left: 16,
      right: 16,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 4,
      elevation: 6,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.16,
      shadowRadius: 8,
      zIndex: 100,
    },
    undoToastRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    undoToastLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    undoToastText: { fontSize: 14, color: theme.text, fontWeight: '500' },
    undoToastAction: { fontSize: 14, fontWeight: '700', color: theme.primary },
    undoProgressTrack: {
      height: 3,
      backgroundColor: theme.border,
      borderRadius: 2,
      overflow: 'hidden',
      marginBottom: 8,
    },
    undoProgressBar: { height: 3, backgroundColor: theme.primary, borderRadius: 2 },
    // Results toolbar
    resultsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
      backgroundColor: theme.background,
    },
    resultsLeft: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    resultsRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    resultsCount: { fontSize: 16, fontWeight: '700', color: theme.text },
    resultsLabel: { fontSize: 14, color: theme.textSecondary, fontWeight: '500' },
    resultsFilteredBadge: {
      backgroundColor: theme.primaryLight,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.primary,
    },
    resultsFilteredText: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.primary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    sortPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 14,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    sortPillText: { fontSize: 13, fontWeight: '600', color: theme.text },
    filterToggleButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterToggleButtonActive: { backgroundColor: theme.primary },
    filterBadge: {
      position: 'absolute',
      top: 1,
      right: 1,
      minWidth: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 2,
    },
    filterBadgeText: {
      fontSize: 9,
      color: theme.buttonText,
      fontWeight: '700',
      lineHeight: 14,
    },
    // Empty-state clear button
    clearFiltersEmptyButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 20,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: theme.primaryLight,
    },
    clearFiltersEmptyText: { fontSize: 14, fontWeight: '600', color: theme.primary },
    // Filter sheet
    sheetOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'flex-end',
      zIndex: 1000,
      elevation: 1000,
    },
    sheetContainer: {
      backgroundColor: theme.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    sheetHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: theme.border },
    sheetHandleArea: { alignItems: 'center', paddingTop: 10, paddingBottom: 8 },
    sheetHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    sheetTitle: { fontSize: 18, fontWeight: '700', color: theme.text },
    sheetClearBtn: {
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 14,
      backgroundColor: theme.errorLight,
    },
    sheetClearText: { fontSize: 13, fontWeight: '600', color: theme.error },
    sheetScroll: { paddingHorizontal: 20, maxHeight: Dimensions.get('window').height * 0.55 },
    sheetSectionTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginTop: 16,
      marginBottom: 8,
    },
    sheetSubSectionTitle: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
      marginTop: 8,
      marginBottom: 6,
    },
    sheetChipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    sheetChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    sheetChipActive: { backgroundColor: theme.primaryLight, borderColor: theme.primary },
    sheetChipText: { fontSize: 14, color: theme.textSecondary, fontWeight: '500' },
    sheetChipTextActive: { color: theme.primary, fontWeight: '600' },
    filterBottomSpacer: { height: 12 },
  });
