import { StyleSheet } from 'react-native';
import type { Theme } from '../theme/colors';

export function getStartOfWeek(date: Date): Date {
  const d = new Date(date);
  const day = d.getDay();
  const diff = d.getDate() - day;
  d.setDate(diff);
  d.setHours(0, 0, 0, 0);
  return d;
}

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: theme.tabBarBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.text,
    },
    searchIconBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchActiveDot: {
      position: 'absolute',
      bottom: 6,
      right: 6,
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.accent,
    },
    searchExpandedRow: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    searchBackBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchExpandedWrapper: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.background,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.primary,
      paddingHorizontal: 14,
      paddingVertical: 8,
      gap: 8,
    },
    searchExpandedInput: {
      flex: 1,
      fontSize: 16,
      color: theme.text,
      padding: 0,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    viewToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 6,
      paddingHorizontal: 12,
      backgroundColor: theme.primary,
      borderRadius: 16,
    },
    viewToggleText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textInverse,
    },
    todayButton: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 16,
      backgroundColor: theme.warning + '20',
      borderWidth: 1,
      borderColor: theme.warning,
    },
    todayButtonText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.warning,
    },
    groupMenuButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    groupMenuButtonActive: {
      backgroundColor: theme.accent,
    },
    filterBadge: {
      position: 'absolute',
      top: 1,
      right: 1,
      minWidth: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: theme.accent,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 2,
    },
    filterBadgeText: {
      fontSize: 9,
      color: theme.buttonText,
      fontWeight: '700',
      lineHeight: 14,
    },
    sheetOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'flex-end',
      zIndex: 1000,
      elevation: 1000,
    },
    sheetContainer: {
      backgroundColor: theme.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    sheetHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.border,
    },
    sheetHandleArea: {
      alignItems: 'center',
      paddingTop: 10,
      paddingBottom: 8,
    },
    sheetHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    sheetTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.text,
    },
    sheetClearBtn: {
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 14,
      backgroundColor: theme.errorLight,
    },
    sheetClearText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.error,
    },
    sheetScroll: {
      paddingHorizontal: 20,
    },
    sheetScrollContent: {
      paddingBottom: 20,
    },
    sheetSectionTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginTop: 16,
      marginBottom: 8,
    },
    sheetChipWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    sheetChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    sheetChipActive: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    sheetChipText: {
      fontSize: 14,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    sheetChipTextActive: {
      color: theme.primary,
      fontWeight: '600',
    },
    weekView: {
      backgroundColor: theme.card,
      marginHorizontal: 12,
      marginVertical: 6,
      borderRadius: 16,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    weekNavBtn: {
      width: 28,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    weekDaysRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 4,
      paddingVertical: 8,
      gap: 2,
    },
    weekDay: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: 2,
      borderRadius: 10,
      backgroundColor: theme.background,
    },
    weekDayToday: {
      backgroundColor: theme.primary,
    },
    weekDaySelected: {
      backgroundColor: theme.accent,
    },
    weekDayName: {
      fontSize: 10,
      color: theme.textSecondary,
      marginBottom: 2,
    },
    weekDayNameToday: {
      color: theme.textInverse,
    },
    weekDayNameSelected: {
      color: theme.textInverse,
    },
    weekDayNumber: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 2,
    },
    weekDayNumberToday: {
      color: theme.textInverse,
    },
    weekDayNumberSelected: {
      color: theme.textInverse,
    },
    weekDayDots: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 2,
      minHeight: 8,
    },
    weekDayDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
    },
    weekDayMore: {
      fontSize: 8,
      color: theme.textTertiary,
    },
    monthView: {
      backgroundColor: theme.card,
      marginHorizontal: 12,
      marginVertical: 6,
      borderRadius: 16,
      padding: 10,
      paddingBottom: 8,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    monthHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 6,
      paddingBottom: 6,
      borderBottomWidth: 1,
      borderBottomColor: theme.border + '30',
    },
    monthTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.text,
    },
    monthWeekdays: {
      flexDirection: 'row',
      marginBottom: 2,
    },
    monthWeekday: {
      flexBasis: '13.5%',
      flexGrow: 0,
      flexShrink: 0,
      marginHorizontal: '0.35%',
      textAlign: 'center',
      fontSize: 10,
      fontWeight: '700',
      color: theme.textSecondary,
      textTransform: 'uppercase',
    },
    monthGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    monthCell: {
      flexBasis: '13.5%',
      flexGrow: 0,
      flexShrink: 0,
      height: 32,
      padding: 2,
      marginHorizontal: '0.35%',
      marginVertical: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      backgroundColor: undefined,
    },
    monthCellToday: {
      backgroundColor: theme.primary + '20',
      borderWidth: 1.5,
      borderColor: theme.primary,
    },
    monthCellSelected: {
      backgroundColor: theme.primary,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 2,
    },
    monthCellNumber: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.text,
    },
    monthCellNumberToday: {
      color: theme.primary,
      fontWeight: '700',
    },
    monthCellNumberSelected: {
      color: theme.textInverse,
      fontWeight: '700',
    },
    monthCellBar: {
      width: 14,
      height: 3,
      borderRadius: 1.5,
      marginTop: 1,
    },
    monthCellBarDefault: {
      backgroundColor: theme.primary,
    },
    monthCellBarSelected: {
      backgroundColor: theme.textInverse,
    },
    content: {
      flex: 1,
      paddingBottom: 120,
    },
    collapsedStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      gap: 8,
      backgroundColor: theme.card,
      borderBottomWidth: 1,
      borderBottomColor: theme.border + '40',
    },
    collapsedStripText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.text,
      flex: 1,
    },
    collapsedStripCount: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.primary,
      backgroundColor: theme.primaryLight,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
      overflow: 'hidden',
    },
    section: {
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 8,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      gap: 8,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    sectionCount: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.primary,
      backgroundColor: theme.primaryLight,
      paddingHorizontal: 7,
      paddingVertical: 1,
      borderRadius: 8,
      overflow: 'hidden',
    },
    selectedDateActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    completeAllBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: theme.primary,
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 8,
      minHeight: 36,
    },
    completeAllBtnDisabled: {
      opacity: 0.6,
    },
    completeAllText: {
      color: theme.textInverse,
      fontSize: 12,
      fontWeight: '600',
    },
    completeAllProgress: {
      color: theme.textInverse,
      fontSize: 12,
      fontWeight: '700',
    },
    completeAllOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 32,
    },
    completeAllCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 20,
      padding: 24,
      width: '100%',
      maxWidth: 340,
      alignItems: 'center',
    },
    completeAllIconRow: {
      marginBottom: 12,
    },
    completeAllIconCircle: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    completeAllTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 16,
      textAlign: 'center',
    },
    progressBarOuter: {
      width: '100%',
      height: 6,
      backgroundColor: theme.border,
      borderRadius: 3,
      overflow: 'hidden',
      marginBottom: 16,
    },
    progressBarInner: {
      height: 6,
      backgroundColor: theme.primary,
      borderRadius: 3,
    },
    completeAllActions: {
      flexDirection: 'row',
      gap: 12,
      width: '100%',
    },
    completeAllCancelBtn: {
      flex: 1,
      padding: 14,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    completeAllCancelText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    completeAllConfirmBtn: {
      flex: 1,
      padding: 14,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: theme.primary,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 6,
    },
    completeAllConfirmText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textInverse,
    },
    // Complete-all checklist styles
    caSelectAllRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 10,
      alignSelf: 'flex-start',
    },
    caSelectAllText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.primary,
    },
    caTaskList: {
      width: '100%',
      maxHeight: 260,
      marginBottom: 16,
    },
    caTaskRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 9,
      paddingHorizontal: 8,
      borderRadius: 10,
      marginBottom: 4,
      backgroundColor: theme.background,
    },
    caTaskRowDeselected: {
      opacity: 0.45,
    },
    caCheckboxMuted: {
      color: theme.textSecondary,
    },
    caTaskEmoji: {
      fontSize: 16,
    },
    caTaskInfo: {
      flex: 1,
    },
    caTaskName: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.text,
    },
    caTaskNameDeselected: {
      textDecorationLine: 'line-through',
    },
    caTaskType: {
      fontSize: 11,
      color: theme.textSecondary,
      textTransform: 'capitalize',
    },
    emptyState: {
      alignItems: 'center',
      padding: 32,
      backgroundColor: theme.background,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      borderStyle: 'dashed',
    },
    emptyStateText: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.text,
      marginTop: 16,
      textAlign: 'center',
    },
    emptyStateSubtext: {
      fontSize: 14,
      color: theme.textSecondary,
      marginTop: 8,
      marginBottom: 16,
      textAlign: 'center',
    },
    clearSearchButton: {
      marginTop: 8,
      paddingVertical: 10,
      paddingHorizontal: 20,
      backgroundColor: theme.primary,
      borderRadius: 8,
    },
    clearSearchText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textInverse,
    },
    addTaskButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 8,
      paddingHorizontal: 16,
      backgroundColor: theme.primaryLight,
      borderRadius: 20,
    },
    addTaskButtonText: {
      fontSize: 14,
      color: theme.primary,
      fontWeight: '600',
    },
    taskCard: {
      flexDirection: 'row',
      backgroundColor: theme.card,
      borderRadius: 16,
      marginBottom: 12,
      overflow: 'hidden',
      borderWidth: 1.5,
      borderColor: theme.card,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    taskCardOverdue: {
      borderColor: theme.error + '60',
      backgroundColor: theme.errorLight,
    },
    taskColorBar: {
      width: 5,
    },
    taskContent: {
      flex: 1,
      padding: 16,
    },
    taskHeader: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    taskIconContainer: {
      width: 44,
      height: 44,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    taskIconEmoji: {
      fontSize: 22,
    },
    taskInfo: {
      flex: 1,
    },
    taskTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 2,
    },
    taskPlant: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    taskLocation: {
      fontSize: 12,
      color: theme.textTertiary,
      marginTop: 2,
    },
    taskBed: {
      fontSize: 12,
      color: theme.primary,
      marginTop: 2,
    },
    taskRight: {
      alignItems: 'flex-end',
    },
    taskTime: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    taskTimeOverdue: {
      color: theme.error,
      fontWeight: '600',
    },
    swipeAction: {
      backgroundColor: theme.success,
      justifyContent: 'center',
      alignItems: 'center',
      width: 100,
      borderRadius: 16,
      marginBottom: 12,
    },
    swipeActionContent: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    swipeActionText: {
      color: theme.backgroundSecondary,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 4,
    },
    swipeHintBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.primaryLight,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 14,
      marginHorizontal: 16,
      marginBottom: 8,
      gap: 10,
    },
    swipeHintBannerContent: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    swipeHintBannerText: {
      fontSize: 13,
      color: theme.text,
      flex: 1,
    },
    harvestCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.border + '40',
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    harvestCardReady: {
      borderColor: theme.success,
      backgroundColor: theme.success + '10',
      borderWidth: 2,
      shadowColor: theme.success,
      shadowOpacity: 0.15,
    },
    harvestIcon: {
      marginRight: 16,
    },
    harvestEmoji: {
      fontSize: 36,
    },
    harvestInfo: {
      flex: 1,
    },
    harvestPlant: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 4,
    },
    harvestDate: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: theme.backgroundSecondary,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '85%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 24,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
    },
    modalCloseButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.text,
    },
    modalBody: {
      padding: 24,
      paddingBottom: 40,
    },
    label: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 8,
    },

    input: {
      backgroundColor: theme.inputBackground,
      padding: 16,
      borderRadius: 12,
      fontSize: 16,
      color: theme.inputText,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      marginBottom: 12,
    },
    dateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: theme.inputBackground,
      padding: 16,
      borderRadius: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.inputBorder,
    },
    dateButtonText: {
      fontSize: 16,
      color: theme.text,
      fontWeight: '500',
    },
    timeButtons: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 16,
    },
    timeButton: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
      alignItems: 'center',
    },
    timeButtonActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    timeButtonText: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    timeButtonTextActive: {
      color: theme.primary,
      fontWeight: '600',
    },
    taskTypeToggle: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 16,
    },
    toggleButton: {
      flex: 1,
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
      alignItems: 'center',
    },
    toggleButtonActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    toggleButtonText: {
      fontSize: 14,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    toggleButtonTextActive: {
      color: theme.primary,
      fontWeight: '600',
    },
    presets: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 12,
      flexWrap: 'wrap',
    },
    presetButton: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    presetButtonActive: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    presetText: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: '600',
    },
    presetTextActive: {
      color: theme.primary,
    },
    preview: {
      backgroundColor: theme.accentLight,
      padding: 16,
      borderRadius: 12,
      marginTop: 8,
      marginBottom: 16,
      borderLeftWidth: 4,
      borderLeftColor: theme.accent,
    },
    previewTitle: {
      fontSize: 14,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 8,
    },
    previewText: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 4,
      lineHeight: 20,
    },
    helperText: {
      fontSize: 12,
      color: theme.textTertiary,
      marginBottom: 24,
    },
    createButton: {
      backgroundColor: theme.primary,
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
    },
    createButtonDisabled: {
      opacity: 0.6,
    },
    createButtonText: {
      color: theme.backgroundSecondary,
      fontSize: 16,
      fontWeight: '600',
    },
    selectedTaskInfo: {
      backgroundColor: theme.background,
      padding: 16,
      borderRadius: 12,
      marginBottom: 16,
    },
    selectedTaskTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 4,
    },
    selectedTaskPlant: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    notesInput: {
      minHeight: 80,
    },
    modalActions: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 8,
    },
    actionButton: {
      flex: 1,
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
    },
    actionButtonDisabled: {
      opacity: 0.6,
    },
    skipButton: {
      backgroundColor: theme.primary,
    },
    skipButtonText: {
      color: theme.backgroundSecondary,
      fontSize: 16,
      fontWeight: '600',
    },
    // Swipe left actions (Snooze + Skip)
    swipeLeftActions: {
      flexDirection: 'row',
      marginBottom: 12,
    },
    swipeSnoozeAction: {
      backgroundColor: theme.info,
      justifyContent: 'center',
      alignItems: 'center',
      width: 80,
      borderTopLeftRadius: 16,
      borderBottomLeftRadius: 16,
    },
    swipeSkipAction: {
      backgroundColor: theme.warning,
      justifyContent: 'center',
      alignItems: 'center',
      width: 80,
      borderTopRightRadius: 16,
      borderBottomRightRadius: 16,
    },
    // Skip Modal (Calendar)
    skipModalOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    skipModalContent: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 20,
      padding: 24,
      width: '100%',
      maxWidth: 400,
    },
    skipModalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 8,
    },
    skipModalSubtext: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 16,
    },
    skipModalInput: {
      backgroundColor: theme.inputBackground,
      borderRadius: 12,
      padding: 12,
      fontSize: 15,
      color: theme.inputText,
      minHeight: 80,
      textAlignVertical: 'top',
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.inputBorder,
    },
    skipReasonChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 20,
    },
    skipReasonChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: theme.primaryLight,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.primary,
    },
    skipReasonChipText: {
      fontSize: 13,
      color: theme.primary,
      fontWeight: '500',
    },
    skipModalButtons: {
      flexDirection: 'row',
      gap: 12,
    },
    skipModalBtn: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
    },
    skipModalBtnCancel: {
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    skipModalBtnConfirm: {
      backgroundColor: theme.warning,
    },
    skipModalBtnText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textInverse,
    },
    skipModalBtnCancelText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    selectedDateTaskBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: theme.primaryLight,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    selectedDateTaskCount: {
      fontSize: 13,
      color: theme.primary,
      fontWeight: '700',
    },
    taskCardSelected: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    taskCheckbox: {
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 6,
      width: 28,
      height: 28,
    },
    taskCheckboxSelected: {},
    selectionBar: {
      position: 'absolute',
      left: 16,
      right: 16,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.card,
      borderRadius: 16,
      paddingVertical: 10,
      paddingHorizontal: 14,
      gap: 10,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
      zIndex: 100,
      borderWidth: 1,
      borderColor: theme.border,
    },
    selectionBarCancel: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.backgroundSecondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    selectionBarText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '600',
      color: theme.text,
    },
    selectionBarBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: theme.primary,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 12,
    },
    selectionBarBtnDisabled: {
      opacity: 0.6,
    },
    selectionBarBtnText: {
      color: theme.textInverse,
      fontSize: 13,
      fontWeight: '700',
    },
    taskPriorityBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      marginTop: 3,
      alignSelf: 'flex-start',
    },
    taskPriorityBadgeText: {
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    taskPreferredTime: {
      fontSize: 11,
      color: theme.textTertiary,
      marginTop: 2,
    },
    taskRainBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      marginTop: 3,
      alignSelf: 'flex-start',
      backgroundColor: theme.info + '22',
    },
    taskRainBadgeText: {
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.3,
      color: theme.info,
    },
    taskHarvestHint: {
      fontSize: 11,
      color: theme.success,
      marginTop: 2,
    },
    weekDoneChip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 2,
      backgroundColor: theme.success + '20',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.success + '60',
    },
    weekDoneChipText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.success,
    },
    taskDetailOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'flex-end',
    },
    taskDetailSheet: {
      backgroundColor: theme.backgroundSecondary,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingTop: 12,
    },
    taskDetailHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.border,
      alignSelf: 'center',
      marginBottom: 16,
    },
    taskDetailHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      gap: 14,
    },
    taskDetailEmoji: {
      width: 52,
      height: 52,
      fontSize: 30,
      textAlign: 'center',
      lineHeight: 52,
      backgroundColor: theme.background,
      borderRadius: 14,
      overflow: 'hidden',
    },
    taskDetailTitleBlock: {
      flex: 1,
    },
    taskDetailTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 2,
    },
    taskDetailSubtitle: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    taskDetailBody: {
      paddingHorizontal: 20,
      paddingTop: 12,
    },
    taskDetailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
    },
    taskDetailLabel: {
      fontSize: 13,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    taskDetailValue: {
      fontSize: 13,
      color: theme.text,
      fontWeight: '600',
      textAlign: 'right',
      flex: 1,
      marginLeft: 16,
    },
    taskDetailActions: {
      flexDirection: 'row',
      gap: 10,
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 8,
    },
    taskDetailActionBtn: {
      flex: 1,
      paddingVertical: 13,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
    },
    taskDetailActionBtnText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textInverse,
    },
    selectionBarSecondaryBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    selectionBarSecondaryBtnText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    skipDaysRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 16,
    },
    skipDayChip: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      alignItems: 'center',
      backgroundColor: theme.background,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    skipDayChipActive: {
      backgroundColor: theme.warningLight,
      borderColor: theme.warning,
    },
    skipDayChipText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    skipDayChipTextActive: {
      color: theme.warning,
    },
    weekProgressRow: {
      paddingHorizontal: 16,
      paddingBottom: 4,
      alignItems: 'flex-start',
    },
    flexOne: {
      flex: 1,
    },
    rowCenter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
    },
    rowCenterGap8: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    animatedCalendarWrap: {
      overflow: 'hidden',
    },
    chipWrapMarginTop: {
      marginTop: 8,
    },
    sheetSectionTitleMarginTop: {
      marginTop: 20,
    },
    sectionTitleOverdue: {
      color: theme.error,
      flex: 1,
    },
    sectionTitleFlex: {
      flex: 1,
    },
    // All / Beds / Pots & Ground segmented control (mirrors plantsStyles)
    segmentRow: {
      flexDirection: 'row',
      alignSelf: 'flex-start',
      flexShrink: 1,
      gap: 2,
      marginHorizontal: 12,
      marginBottom: 8,
      padding: 2,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
      overflow: 'hidden',
    },
    segmentChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
    },
    segmentChipActive: {
      backgroundColor: theme.primaryLight,
    },
    segmentChipText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    segmentChipTextActive: {
      color: theme.primary,
    },
    segmentBadge: {
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    segmentBadgeActive: {
      backgroundColor: theme.primary,
    },
    segmentBadgeText: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.textTertiary,
    },
    segmentBadgeTextActive: {
      color: theme.textInverse,
    },
    // Single removable pill shown when a bed filter arrives via deep-link
    activeBedPillRow: {
      flexDirection: 'row',
      paddingHorizontal: 12,
      marginBottom: 8,
    },
    activeBedPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: theme.primary,
    },
    activeBedPillText: {
      fontSize: 13,
      color: theme.textInverse,
      fontWeight: '600',
    },
  });
