import { StyleSheet } from 'react-native';
import type { Theme } from '../theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    loadingContainer: {
      flex: 1,
      backgroundColor: theme.background,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    loadingText: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 16,
      backgroundColor: theme.tabBarBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    headerActionSlot: {
      width: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    backButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.text,
      textAlign: 'center',
      width: '100%',
    },
    headerContent: {
      flex: 1,
      minWidth: 0,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    headerMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
      minWidth: 0,
      gap: 6,
    },
    headerMetaText: {
      fontSize: 11,
      color: theme.textSecondary,
      fontWeight: '600',
      flexShrink: 1,
    },
    headerStatePill: {
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 999,
      borderWidth: 1,
    },
    headerStatePillCustom: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary + '40',
    },
    headerStatePillDefault: {
      backgroundColor: theme.background,
      borderColor: theme.border,
    },
    headerStatePillText: {
      fontSize: 10,
      fontWeight: '700',
    },
    headerStatePillTextCustom: {
      color: theme.primary,
    },
    headerStatePillTextDefault: {
      color: theme.textSecondary,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      padding: 16,
      gap: 10,
    },
    nameSection: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
    },
    nameSectionLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      marginBottom: 8,
    },
    fieldGroup: {
      marginBottom: 8,
    },
    fieldGroupLast: {
      marginBottom: 0,
    },
    addRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    addButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      gap: 6,
    },
    addButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textInverse,
    },
    input: {
      flex: 1,
      backgroundColor: theme.inputBackground,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      paddingHorizontal: 12,
      height: 42,
      fontSize: 15,
      color: theme.inputText,
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 9,
      paddingVertical: 5,
      borderRadius: 14,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    chipText: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: '600',
    },
    readChip: {
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 14,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    readChipText: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    emptyText: {
      fontSize: 13,
      color: theme.textTertiary,
      fontStyle: 'italic',
    },
    fieldLabelRow: {
      marginBottom: 6,
    },
    rangeRow: {
      flexDirection: 'row',
      gap: 10,
    },
    rangeField: {
      flex: 1,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 6,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    infoRowLast: {
      borderBottomWidth: 0,
    },
    infoLabel: {
      fontSize: 13,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    infoValue: {
      fontSize: 13,
      color: theme.text,
      fontWeight: '600',
      textAlign: 'right',
      flex: 1,
      marginLeft: 16,
    },
    toxicBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: theme.error,
    },
    safeBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: theme.primaryLight,
    },
    badgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textInverse,
    },
    safeBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.primary,
    },
    descriptionInput: {
      borderWidth: 1,
      borderColor: theme.borderLight,
      borderRadius: 8,
      padding: 10,
      minHeight: 72,
      color: theme.text,
      fontSize: 14,
      textAlignVertical: 'top',
      backgroundColor: theme.backgroundSecondary,
    },
    pruningTipsLabel: {
      fontSize: 12,
      color: theme.textTertiary,
      marginBottom: 6,
    },
    pruningTipsInput: {
      borderWidth: 1,
      borderColor: theme.borderLight,
      borderRadius: 8,
      padding: 10,
      minHeight: 80,
      color: theme.text,
      fontSize: 14,
      textAlignVertical: 'top',
      backgroundColor: theme.backgroundSecondary,
    },
    careStatus: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 4,
    },
    careStatusBanner: {
      marginBottom: 10,
      padding: 12,
      borderRadius: 12,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    careStatusText: {
      fontSize: 13,
      color: theme.textSecondary,
      fontWeight: '600',
    },
    careStatusNote: {
      fontSize: 12,
      lineHeight: 18,
      color: theme.textTertiary,
      marginTop: 4,
    },
    footer: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
    },
    footerRow: {
      flexDirection: 'row',
      gap: 10,
    },
    footerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    btnPrimary: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 11,
      borderRadius: 12,
      backgroundColor: theme.primary,
    },
    btnPrimaryText: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.textInverse,
    },
    btnSecondary: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 13,
      borderRadius: 12,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    btnSecondaryText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    btnDanger: {
      alignItems: 'center',
      paddingVertical: 12,
      borderRadius: 12,
    },
    btnDangerText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.error,
    },
    btnDangerIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.background,
    },
    btnResetPill: {
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.background,
    },
    btnResetPillText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textTertiary,
    },
    sectionHeaderAction: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primaryLight,
      borderWidth: 1,
      borderColor: theme.primary + '30',
    },
    savingOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    savingText: {
      fontSize: 14,
      color: theme.textInverse,
      fontWeight: '600',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
    },
    modalContent: {
      width: '100%',
      maxWidth: 420,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.text,
    },
    modalHint: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 12,
    },
    modalActions: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 8,
    },
    modalButton: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 12,
      borderRadius: 10,
    },
    modalButtonSecondary: {
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalButtonDanger: {
      backgroundColor: theme.error,
    },
    modalButtonTextSecondary: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    modalButtonTextPrimary: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textInverse,
    },
    reassignList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 12,
    },
    reassignItem: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    reassignItemActive: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    reassignText: {
      fontSize: 13,
      color: theme.textSecondary,
      fontWeight: '600',
    },
    reassignTextActive: {
      color: theme.primary,
    },
    addPickerBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary,
      marginTop: 10,
    },
    addPickerBtnText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.primary,
    },
    pickerModalContent: {
      maxHeight: '75%',
      padding: 16,
    },
    pickerSearch: {
      backgroundColor: theme.inputBackground,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      paddingHorizontal: 14,
      height: 42,
      fontSize: 14,
      color: theme.inputText,
      marginBottom: 10,
    },
    pickerList: {
      flexGrow: 0,
    },
    pickerRow: {
      paddingVertical: 12,
      paddingHorizontal: 4,
    },
    pickerRowText: {
      fontSize: 15,
      color: theme.text,
    },
    pickerSeparator: {
      height: 0,
    },
    feedingHint: {
      fontSize: 12,
      color: theme.textTertiary,
      marginTop: 4,
      fontStyle: 'italic',
    },
    nutritionSection: {
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: theme.borderLight,
    },
    nutritionGroup: {
      marginBottom: 10,
    },
    nutritionGroupLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 6,
    },
    modalButtonPrimary: {
      backgroundColor: theme.primary,
    },
    chipDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.primary,
    },
    chipLabelArea: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    seasonPillRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginBottom: 12,
    },
    seasonPill: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 14,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    seasonPillActive: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    seasonPillText: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    seasonPillTextActive: {
      color: theme.primary,
      fontWeight: '600',
    },
    modalCloseButton: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    varietyNotesInput: {
      borderWidth: 1,
      borderColor: theme.borderLight,
      borderRadius: 8,
      padding: 10,
      minHeight: 72,
      color: theme.text,
      fontSize: 14,
      textAlignVertical: 'top',
      backgroundColor: theme.backgroundSecondary,
      marginBottom: 4,
    },
  });
