import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    centered: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    content: { flex: 1 },
    scrollContent: { paddingBottom: 24 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 16,
      backgroundColor: theme.tabBarBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    backButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerSpacer: { width: 36 },
    title: { flex: 1, fontSize: 20, fontWeight: '700', color: theme.text, textAlign: 'center' },
    // Tab bar
    tabBar: {
      flexDirection: 'row',
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 10,
      padding: 4,
      marginHorizontal: 16,
      marginTop: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    tab: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      borderRadius: 8,
    },
    tabActive: { backgroundColor: theme.primary },
    tabText: { fontSize: 12, fontWeight: '600', color: theme.textSecondary },
    tabTextActive: { fontSize: 12, fontWeight: '600', color: theme.textInverse },
    // Recipe card
    recipeHeader: { paddingHorizontal: 16, paddingTop: 16, marginBottom: 16 },
    recipeName: { fontSize: 18, fontWeight: '700', color: theme.text },
    recipeTamilName: { fontSize: 13, color: theme.textTertiary, marginTop: 2 },
    recipeDescription: { fontSize: 14, color: theme.textSecondary, marginTop: 8, lineHeight: 20 },
    // Ingredients section
    section: { marginBottom: 24, paddingHorizontal: 16 },
    sectionTitle: { fontSize: 16, fontWeight: '700', color: theme.text, marginBottom: 12 },
    ingredientRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 14,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: theme.border,
    },
    ingredientName: { flex: 1, fontSize: 14, color: theme.text },
    ingredientQty: { fontSize: 14, fontWeight: '700', color: theme.primary, marginLeft: 8 },
    ingredientNote: { fontSize: 11, color: theme.textTertiary, marginTop: 2, marginLeft: 14 },
    // Scaling info
    scalingBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.primaryLight,
      borderRadius: 8,
      padding: 12,
      marginHorizontal: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.border,
    },
    scalingText: { fontSize: 13, color: theme.primary, flex: 1 },
    // Steps
    stepRow: { flexDirection: 'row', marginBottom: 10, paddingRight: 8 },
    stepNumber: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
      marginTop: 2,
    },
    stepNumberText: { fontSize: 12, fontWeight: '700', color: theme.textInverse },
    stepText: { flex: 1, fontSize: 14, color: theme.textSecondary, lineHeight: 20 },
    // When to apply
    applyCard: {
      backgroundColor: theme.accentLight,
      borderRadius: 10,
      padding: 14,
      borderWidth: 1,
      borderColor: theme.border,
    },
    applyLabel: { fontSize: 12, fontWeight: '600', color: theme.accent, marginBottom: 4 },
    applyText: { fontSize: 14, color: theme.text, lineHeight: 20 },
    // Season badges
    seasonRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 12 },
    seasonBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      backgroundColor: theme.primaryLight,
      borderWidth: 1,
      borderColor: theme.border,
    },
    seasonBadgeText: { fontSize: 11, color: theme.primary, fontWeight: '600' },
    // Frequency badge
    frequencyBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      marginTop: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    frequencyText: { fontSize: 13, color: theme.textSecondary },
    frequencyValue: { fontSize: 13, fontWeight: '700', color: theme.primary },
  });
