import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme/colors';

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 16,
      backgroundColor: theme.tabBarBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    backButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    title: { flex: 1, fontSize: 20, fontWeight: '700', color: theme.text },
    content: { padding: 16 },
    loadingState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
    loadingText: { fontSize: 14, color: theme.textSecondary },
    // Section headers
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
      marginTop: 8,
    },
    sectionHeaderText: { flex: 1 },
    sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    sectionTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    sectionAddButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.18,
      shadowRadius: 4,
      elevation: 3,
    },
    // Plot rows
    locationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      paddingHorizontal: 12,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 8,
    },
    locationInfo: { flex: 1 },
    locationNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
    locationName: { fontSize: 15, fontWeight: '600', color: theme.text },
    shortNameBadge: {
      backgroundColor: theme.primary + '20',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
    },
    shortNameBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.primary,
      letterSpacing: 0.5,
    },
    sizeBadge: {
      backgroundColor: theme.backgroundSecondary,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: theme.border,
    },
    sizeBadgeText: { fontSize: 11, fontWeight: '600', color: theme.textSecondary },
    coordBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      backgroundColor: theme.primaryLight,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
    },
    coordBadgeText: { fontSize: 11, fontWeight: '600', color: theme.primary },
    locationMeta: { fontSize: 12, color: theme.textSecondary, marginTop: 4 },
    profileSummaryStrip: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
    profileBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.background,
      borderRadius: 6,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderWidth: 1,
      borderColor: theme.border,
      gap: 4,
    },
    profileBadgeText: { fontSize: 11, color: theme.textSecondary, fontWeight: '600' },
    npkDotRow: { flexDirection: 'row', alignItems: 'center', gap: 2 },
    npkDot: { width: 7, height: 7, borderRadius: 4 },
    locationActions: { flexDirection: 'row', alignItems: 'center', gap: 8, marginLeft: 12 },
    iconButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: theme.background,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
    },
    // Aggregate capacity row
    capacityRow: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      backgroundColor: theme.primaryLight,
      borderRadius: 10,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.border,
    },
    capacityStat: { alignItems: 'center' },
    capacityValue: { fontSize: 16, fontWeight: '700', color: theme.primary },
    capacityLabel: { fontSize: 11, color: theme.textSecondary, marginTop: 2 },
    capacityEmpty: {
      fontSize: 13,
      color: theme.textTertiary,
      textAlign: 'center',
      marginBottom: 12,
      fontStyle: 'italic',
    },
    // Empty states
    emptyStateCard: {
      alignItems: 'center',
      paddingVertical: 24,
      paddingHorizontal: 16,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      borderStyle: 'dashed',
    },
    emptyStateIcon: { marginBottom: 10 },
    emptyStateTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 4,
      textAlign: 'center',
    },
    emptyStateSubtitle: {
      fontSize: 13,
      color: theme.textSecondary,
      textAlign: 'center',
      lineHeight: 18,
    },
    headerSpacer: { width: 36 },
    childSection: { marginTop: 8 },
    // Saving overlay
    savingOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    savingText: { fontSize: 14, color: theme.textInverse, fontWeight: '600' },
  });
