import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme/colors';

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    header: { paddingHorizontal: 20, paddingBottom: 8 },
    progressRow: { flexDirection: 'row', gap: 6, marginBottom: 20 },
    progressDot: {
      flex: 1,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.border,
    },
    progressDotActive: { backgroundColor: theme.primary },
    content: { flex: 1 },
    scrollContent: { paddingHorizontal: 20, paddingBottom: 16 },
    heroIcon: { alignSelf: 'center', marginTop: 12, marginBottom: 16 },
    stepTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: theme.text,
      marginBottom: 8,
    },
    stepDescription: {
      fontSize: 15,
      lineHeight: 22,
      color: theme.textSecondary,
      marginBottom: 20,
    },
    // Welcome bullets
    bulletRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 16 },
    bulletIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bulletTextWrap: { flex: 1 },
    bulletTitle: { fontSize: 15, fontWeight: '700', color: theme.text, marginBottom: 2 },
    bulletText: { fontSize: 13, lineHeight: 19, color: theme.textSecondary },
    // District list
    districtRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
      marginBottom: 8,
    },
    districtRowActive: { borderColor: theme.primary, backgroundColor: theme.primaryLight },
    districtText: { fontSize: 15, color: theme.text },
    districtTextActive: { fontSize: 15, color: theme.primary, fontWeight: '700' },
    // Household stepper
    sectionLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginTop: 8,
      marginBottom: 10,
    },
    stepperRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 10,
      padding: 14,
      borderWidth: 1,
      borderColor: theme.border,
    },
    stepperLabel: { fontSize: 14, color: theme.text, flex: 1 },
    stepperControls: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    stepperButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperButtonText: { fontSize: 18, fontWeight: '700', color: theme.primary },
    stepperValue: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.primary,
      minWidth: 32,
      textAlign: 'center',
    },
    helperText: {
      fontSize: 12,
      color: theme.textSecondary,
      marginTop: 6,
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    chip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
    },
    chipActive: { backgroundColor: theme.primaryLight, borderColor: theme.primary },
    chipText: { fontSize: 13, color: theme.textSecondary, fontWeight: '500' },
    chipTextActive: { fontSize: 13, color: theme.primary, fontWeight: '600' },
    // First bed
    recommendCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 18,
      marginBottom: 16,
    },
    recommendBadge: {
      alignSelf: 'flex-start',
      backgroundColor: theme.primaryLight,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 4,
      marginBottom: 12,
    },
    recommendBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.primary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    recommendTitle: { fontSize: 18, fontWeight: '800', color: theme.text, marginBottom: 6 },
    recommendText: { fontSize: 14, lineHeight: 21, color: theme.textSecondary },
    // Footer
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 20,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    primaryButton: {
      flex: 1,
      backgroundColor: theme.primary,
      borderRadius: 12,
      paddingVertical: 15,
      alignItems: 'center',
    },
    primaryButtonText: { color: theme.textInverse, fontSize: 16, fontWeight: '700' },
    secondaryButton: {
      paddingVertical: 15,
      paddingHorizontal: 18,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
    },
    secondaryButtonText: { color: theme.text, fontSize: 16, fontWeight: '600' },
    skipButton: { alignItems: 'center', paddingVertical: 14 },
    skipText: { fontSize: 14, color: theme.textTertiary, fontWeight: '600' },
  });
