import { StyleSheet } from 'react-native';
import type { Theme } from '../theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 12,
      backgroundColor: theme.tabBarBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    headerIconButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      backgroundColor: theme.primary,
    },
    title: {
      fontSize: 17,
      fontWeight: '700' as const,
      color: theme.text,
      // Ellipsize a long plant name instead of shoving the unsaved dot off-screen.
      flexShrink: 1,
    },
    headerCenter: {
      flex: 1,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 6,
    },
    unsavedDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.warning,
    },
    saveText: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.buttonText,
    },
    saveButton: {
      backgroundColor: theme.primary,
      paddingHorizontal: 18,
      paddingVertical: 8,
      borderRadius: 20,
    },
    saveButtonDisabled: {
      backgroundColor: theme.borderDark,
    },
    saveTextDisabled: {
      color: theme.textTertiary,
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 10,
    },
    scrollContent: {
      paddingBottom: 100,
    },
    noteCounter: {
      fontSize: 12,
      color: theme.textTertiary,
      textAlign: 'right',
      marginTop: 6,
    },
    label: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 8,
      marginTop: 4,
    },
    locationDefaultsHint: {
      fontSize: 12,
      color: theme.primary,
      marginTop: 6,
      marginBottom: 4,
      marginHorizontal: 2,
      fontStyle: 'italic',
    },
    settingToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.backgroundSecondary,
      padding: 14,
      borderRadius: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    settingToggleActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    settingToggleLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
    },
    settingToggleIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      marginRight: 10,
    },
    settingToggleIconWrapActive: {
      borderColor: theme.primary,
      backgroundColor: theme.backgroundSecondary,
    },
    settingToggleLabel: {
      fontSize: 16,
      color: theme.text,
      fontWeight: '600',
      flexShrink: 1,
    },
    settingToggleLabelActive: {
      color: theme.primary,
    },
    settingSwitchTrack: {
      width: 44,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.border,
      justifyContent: 'center',
      paddingHorizontal: 3,
      marginLeft: 12,
    },
    settingSwitchTrackActive: {
      backgroundColor: theme.primary,
    },
    settingSwitchThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: theme.backgroundSecondary,
      alignSelf: 'flex-start',
    },
    settingSwitchThumbActive: {
      alignSelf: 'flex-end',
    },
    helperText: {
      fontSize: 12,
      color: theme.textTertiary,
      marginTop: -2,
      marginBottom: 12,
      marginLeft: 4,
    },
    // --- Wizard step section cards (icon-headed groups, DetailCard language) ---
    sectionCard: {
      backgroundColor: theme.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
      padding: 14,
      marginBottom: 14,
    },
    sectionCardTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    sectionCardIconWrap: {
      width: 26,
      height: 26,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primaryLight,
    },
    sectionCardTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.text,
    },
    sectionCardIconWrapError: {
      backgroundColor: theme.errorLight,
    },
    sectionCardErrorDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.error,
      marginLeft: 'auto',
    },
    // --- Field group visual divider ---
    fieldGroupDivider: {
      height: 1,
      backgroundColor: theme.borderLight,
      marginVertical: 16,
      marginHorizontal: 4,
    },
    fieldGroupLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 10,
      marginTop: 2,
    },
    // --- Date Card ---
    dateCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
      overflow: 'hidden',
    },
    dateCardTouchable: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
    },
    dateCardIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    dateCardContent: {
      flex: 1,
    },
    dateCardLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textTertiary,
      letterSpacing: 0.5,
      marginBottom: 2,
    },
    dateCardValue: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
    },
    dateCardPlaceholder: {
      fontSize: 15,
      color: theme.inputPlaceholder,
    },
    optionalBadge: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 6,
      paddingHorizontal: 6,
      paddingVertical: 1,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    optionalBadgeText: {
      fontSize: 10,
      fontWeight: '600' as const,
      color: theme.textTertiary,
      letterSpacing: 0.3,
    },
    // --- Frequency Row (Water/Feed/Prune inline cards) ---
    frequencyRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 12,
    },
    frequencyCard: {
      flex: 1,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      padding: 12,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    frequencyIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
    },
    frequencyCardLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    frequencyInputWrap: {
      backgroundColor: theme.inputBackground,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      width: '100%',
      alignItems: 'center',
      marginBottom: 4,
    },
    frequencyInput: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.text,
      textAlign: 'center',
      paddingVertical: 6,
      paddingHorizontal: 8,
      minWidth: 50,
    },
    frequencyUnit: {
      fontSize: 11,
      color: theme.textTertiary,
      fontWeight: '600',
    },
    // --- Stat Cards (Coconut metrics) ---
    statCardsRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 8,
    },
    statCard: {
      flex: 1,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      padding: 10,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    statCardIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    statCardLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 4,
    },
    statCardInputWrap: {
      backgroundColor: theme.inputBackground,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      width: '100%',
      alignItems: 'center',
    },
    statCardInput: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.text,
      textAlign: 'center',
      paddingVertical: 4,
      paddingHorizontal: 4,
      minWidth: 40,
    },
    // --- Notes Card ---
    notesCardInput: {
      backgroundColor: theme.inputBackground,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      padding: 12,
      fontSize: 15,
      color: theme.inputText,
      minHeight: 80,
      textAlignVertical: 'top',
    },
    infoCard: {
      backgroundColor: theme.backgroundSecondary,
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderDark,
    },
    infoCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    infoCardTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      flex: 1,
    },
    infoCardText: {
      fontSize: 16,
      color: theme.primary,
      fontWeight: '600',
      marginBottom: 4,
    },
    infoCardSubtext: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 8,
    },
    varietySuggestions: {
      marginBottom: 12,
    },
    discardOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 32,
    },
    discardCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 20,
      padding: 28,
      alignItems: 'center',
      width: '100%',
      maxWidth: 340,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 24,
      elevation: 12,
    },
    discardIconWrap: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.errorLight,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    discardTitle: {
      fontSize: 19,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 8,
    },
    discardMessage: {
      fontSize: 14,
      color: theme.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 24,
    },
    discardActions: {
      flexDirection: 'row',
      gap: 12,
      width: '100%',
    },
    discardKeepButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 13,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    discardKeepText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.primary,
    },
    discardButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 13,
      borderRadius: 12,
      backgroundColor: theme.error,
    },
    discardButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textInverse,
    },

    // --- #2 Photo Hero ---
    photoHeroContainer: {
      width: '100%',
      height: 180,
      borderRadius: 14,
      overflow: 'hidden' as const,
      marginBottom: 12,
      backgroundColor: theme.primaryLight,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    photoHeroImage: {
      width: '100%',
      height: '100%',
    },
    photoHeroPlaceholder: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    photoHeroPlaceholderText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.primary,
    },
    photoHeroEditBadge: {
      position: 'absolute' as const,
      bottom: 10,
      right: 10,
      backgroundColor: theme.overlay,
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 5,
      flexDirection: 'row' as const,
      alignItems: 'center',
      gap: 5,
    },
    photoHeroEditBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textInverse,
    },

    // --- #9 Auto-Name Preview Inline ---
    namePreviewRow: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      backgroundColor: theme.inputBackground,
      borderRadius: 12,
      paddingHorizontal: 16,
      minHeight: 52,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      gap: 8,
    },
    namePreviewFloatingLabel: {
      position: 'absolute' as const,
      top: -9,
      left: 12,
      paddingHorizontal: 4,
      fontSize: 12,
      fontWeight: '500' as const,
      color: theme.textSecondary,
      backgroundColor: theme.backgroundSecondary,
    },
    namePreviewValue: {
      fontSize: 14,
      color: theme.text,
      fontWeight: '600' as const,
      flex: 1,
    },
    namePreviewValuePending: {
      fontSize: 13,
      color: theme.textTertiary,
      fontStyle: 'italic',
      flex: 1,
    },
    nameCustomRow: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      backgroundColor: theme.inputBackground,
      borderRadius: 12,
      paddingLeft: 16,
      paddingRight: 10,
      minHeight: 52,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.inputBorder,
    },
    nameCustomInput: {
      flex: 1,
      fontSize: 14,
      fontWeight: '600' as const,
      color: theme.inputText,
      paddingVertical: 14,
      paddingRight: 8,
    },
    nameCustomActions: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      gap: 6,
      flexShrink: 0,
    },
    nameCustomClear: {
      padding: 4,
    },
    namePreviewActionUse: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
      backgroundColor: theme.primaryLight,
    },
    namePreviewActionCustom: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    namePreviewActionText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.primary,
    },
    namePreviewActionTextMuted: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textTertiary,
    },

    // Compact single-row segmented control for the growing-space picker.
    spaceSegmentRow: {
      flexDirection: 'row' as const,
      borderWidth: 1,
      borderColor: theme.pickerBorder,
      borderRadius: 12,
      overflow: 'hidden' as const,
      backgroundColor: theme.pickerBackground,
      marginBottom: 12,
    },
    spaceSegmentItem: {
      flex: 1,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 6,
      paddingVertical: 12,
      paddingHorizontal: 4,
    },
    spaceSegmentItemActive: {
      backgroundColor: theme.primary,
    },
    spaceSegmentDivider: {
      width: 1,
      backgroundColor: theme.pickerBorder,
    },
    spaceSegmentLabel: {
      fontSize: 13,
      fontWeight: '600' as const,
      color: theme.textSecondary,
    },
    spaceSegmentLabelActive: {
      color: theme.textInverse,
    },

    // --- D: Chip Grid (replaces horizontal ScrollView) ---
    // Read-only plant identity under the hero photo, echoing the detail hero
    // (PlantKeyInfoSection) scaled for this form's shorter 180px photo.
    heroCaptionName: {
      fontSize: 24,
      fontWeight: '700' as const,
      color: theme.text,
      marginBottom: 2,
    },
    heroCaptionCategory: {
      fontSize: 14,
      fontStyle: 'italic' as const,
      color: theme.textSecondary,
    },
    // Equal-width 2x2 grid for the health-status chips so both rows align
    // cleanly on narrow screens (unlike a wrapping row of variable-width chips).
    healthGrid: {
      flexDirection: 'row' as const,
      flexWrap: 'wrap' as const,
      gap: 8,
      marginBottom: 10,
    },
    healthGridItem: {
      flexBasis: '47%' as const,
      flexGrow: 1,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 6,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    healthGridItemText: {
      fontSize: 13,
      fontWeight: '600' as const,
      color: theme.textTertiary,
    },
    // Tone variants so a selected health chip reads at a glance without parsing
    // the label. Keyed off HEALTH_STATUS_TONE in utils/plantLabels.
    healthGridItemActiveSuccess: {
      backgroundColor: theme.successLight,
      borderColor: theme.successBorder,
    },
    healthGridItemActiveWarning: {
      backgroundColor: theme.warningLight,
      borderColor: theme.warningBorder,
    },
    healthGridItemActiveInfo: {
      backgroundColor: theme.infoLight,
      borderColor: theme.infoBorder,
    },
    healthGridItemActiveError: {
      backgroundColor: theme.errorLight,
      borderColor: theme.errorBorder,
    },
    healthGridItemTextSuccess: {
      color: theme.successDark,
      fontWeight: '700' as const,
    },
    healthGridItemTextWarning: {
      color: theme.warningDark,
      fontWeight: '700' as const,
    },
    healthGridItemTextInfo: {
      color: theme.infoDark,
      fontWeight: '700' as const,
    },
    healthGridItemTextError: {
      color: theme.errorDark,
      fontWeight: '700' as const,
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    statusDotSuccess: { backgroundColor: theme.success },
    statusDotWarning: { backgroundColor: theme.warning },
    statusDotInfo: { backgroundColor: theme.info },
    statusDotError: { backgroundColor: theme.error },
    // Tone-tinted callout for the health-status description, so it visually
    // binds to the selected chip's color instead of reading as generic gray text.
    healthCallout: {
      borderRadius: 10,
      padding: 10,
      marginBottom: 14,
    },
    healthCalloutSuccess: { backgroundColor: theme.successLight },
    healthCalloutWarning: { backgroundColor: theme.warningLight },
    healthCalloutInfo: { backgroundColor: theme.infoLight },
    healthCalloutError: { backgroundColor: theme.errorLight },
    healthCalloutText: {
      fontSize: 12,
      lineHeight: 17,
    },
    healthCalloutTextSuccess: { color: theme.successDark },
    healthCalloutTextWarning: { color: theme.warningDark },
    healthCalloutTextInfo: { color: theme.infoDark },
    healthCalloutTextError: { color: theme.errorDark },

    // --- E: Frequency Stepper ---
    stepperCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    stepperIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: theme.primaryLight,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    stepperLabel: {
      fontSize: 14,
      fontWeight: '700' as const,
      color: theme.text,
    },
    stepperRow: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      justifyContent: 'center' as const,
      gap: 16,
    },
    stepperButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.background,
      borderWidth: 2,
      borderColor: theme.primary,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    stepperValueWrap: {
      alignItems: 'center' as const,
      minWidth: 80,
    },
    stepperValueInput: {
      fontSize: 28,
      fontWeight: '800' as const,
      color: theme.text,
      textAlign: 'center' as const,
      paddingVertical: 2,
      paddingHorizontal: 8,
      minWidth: 60,
    },
    stepperUnit: {
      fontSize: 12,
      fontWeight: '600' as const,
      color: theme.textTertiary,
      marginTop: 2,
    },
    stepperHint: {
      fontSize: 12,
      fontWeight: '700' as const,
      textAlign: 'center' as const,
      marginTop: 8,
    },
  });
