import { StyleSheet, Dimensions } from 'react-native';
import type { Theme } from '../theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 12,
      backgroundColor: theme.tabBarBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.text,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    headerIconBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerIconBtnActive: {
      backgroundColor: theme.accent,
    },
    searchActiveDot: {
      position: 'absolute',
      bottom: 6,
      right: 6,
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.accent,
    },
    searchExpandedRow: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    searchBackBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchExpandedWrapper: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.background,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.primary,
      paddingHorizontal: 14,
      paddingVertical: 8,
      gap: 8,
    },
    searchExpandedInput: {
      flex: 1,
      fontSize: 16,
      color: theme.text,
      padding: 0,
    },
    filterBadge: {
      position: 'absolute',
      top: 1,
      right: 1,
      minWidth: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 2,
    },
    filterBadgeText: {
      fontSize: 9,
      color: theme.buttonText,
      fontWeight: '700',
      lineHeight: 14,
    },
    filterToggleButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterToggleButtonActive: {
      backgroundColor: theme.primary,
    },

    sortMenu: {
      backgroundColor: theme.backgroundSecondary,
      marginHorizontal: 16,
      marginTop: 4,
      marginBottom: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    sortOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      gap: 12,
    },
    sortOptionActive: {
      backgroundColor: theme.background,
    },
    sortText: {
      flex: 1,
      fontSize: 15,
      color: theme.text,
    },
    sortTextActive: {
      fontWeight: '600',
      color: theme.primary,
    },
    sheetOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'flex-end',
      zIndex: 1000,
      elevation: 1000,
    },
    sheetContainer: {
      backgroundColor: theme.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    sheetHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    sheetTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.text,
    },
    sheetClearBtn: {
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 14,
      backgroundColor: theme.errorLight,
    },
    sheetClearText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.error,
    },
    sheetScroll: {
      paddingHorizontal: 20,
      maxHeight: Dimensions.get('window').height * 0.55,
    },
    sheetSectionTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginTop: 16,
      marginBottom: 8,
    },
    sheetSubSectionTitle: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
      marginTop: 8,
      marginBottom: 6,
    },
    sheetChipWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    sheetChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    sheetChipActive: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    // Repeated icons (e.g. water droplets) read as one glyph, so they sit tighter
    // together than the chip's own icon-to-label gap.
    sheetChipIconGroup: {
      flexDirection: 'row',
      gap: 1,
    },
    sheetChipText: {
      fontSize: 14,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    sheetChipTextActive: {
      color: theme.primary,
      fontWeight: '600',
    },
    // A facet that would empty the list still shows its "(0)", muted.
    sheetChipCountZero: {
      color: theme.textTertiary,
    },
    // Health-status tone quartet — mirrors the edit form's chips (plantFormStyles)
    // so a status reads identically wherever it appears.
    sheetChipActiveSuccess: {
      backgroundColor: theme.successLight,
      borderColor: theme.successBorder,
    },
    sheetChipActiveWarning: {
      backgroundColor: theme.warningLight,
      borderColor: theme.warningBorder,
    },
    sheetChipActiveInfo: {
      backgroundColor: theme.infoLight,
      borderColor: theme.infoBorder,
    },
    sheetChipActiveError: {
      backgroundColor: theme.errorLight,
      borderColor: theme.errorBorder,
    },
    sheetChipTextSuccess: {
      color: theme.successDark,
      fontWeight: '600',
    },
    sheetChipTextWarning: {
      color: theme.warningDark,
      fontWeight: '600',
    },
    sheetChipTextInfo: {
      color: theme.infoDark,
      fontWeight: '600',
    },
    sheetChipTextError: {
      color: theme.errorDark,
      fontWeight: '600',
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    statusDotSuccess: { backgroundColor: theme.success },
    statusDotWarning: { backgroundColor: theme.warning },
    statusDotInfo: { backgroundColor: theme.info },
    statusDotError: { backgroundColor: theme.error },

    resultsHeader: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 8,
      backgroundColor: theme.background,
    },
    segmentRow: {
      flexDirection: 'row',
      flex: 1,
      gap: 2,
      padding: 2,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
      overflow: 'hidden',
    },
    segmentChip: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
    },
    segmentChipActive: {
      backgroundColor: theme.primaryLight,
    },
    segmentChipText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    segmentChipTextActive: {
      color: theme.primary,
    },
    segmentBadge: {
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    segmentBadgeActive: {
      backgroundColor: theme.primary,
    },
    segmentBadgeText: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.textTertiary,
    },
    segmentBadgeTextActive: {
      color: theme.textInverse,
    },
    resultsShowing: {
      fontSize: 12,
      color: theme.textTertiary,
    },
    listContent: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 120,
    },
    loadingMore: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 20,
      gap: 8,
    },
    loadingText: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    loadMoreButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 16,
      marginVertical: 8,
      backgroundColor: theme.primaryLight,
      borderRadius: 12,
      gap: 8,
    },
    loadMoreText: {
      fontSize: 14,
      color: theme.primary,
      fontWeight: '600',
    },
    healthAlertBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.warningLight,
      paddingHorizontal: 16,
      paddingVertical: 10,
      gap: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    healthAlertText: {
      flex: 1,
      fontSize: 13,
      color: theme.warning,
      fontWeight: '600',
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 48,
      marginTop: 48,
    },
    emptyText: {
      fontSize: 20,
      fontWeight: '600',
      color: theme.text,
      marginTop: 16,
    },
    emptySubtext: {
      fontSize: 14,
      color: theme.textSecondary,
      marginTop: 4,
    },
    clearFiltersEmptyButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 20,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: theme.primaryLight,
    },
    clearFiltersEmptyText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.primary,
    },
    undoToast: {
      position: 'absolute',
      left: 16,
      right: 16,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 4,
      elevation: 6,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.16,
      shadowRadius: 8,
      zIndex: 100,
    },
    undoToastRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    undoToastLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    undoToastText: {
      fontSize: 14,
      color: theme.text,
      fontWeight: '500',
    },
    undoToastAction: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.primary,
    },
    undoProgressTrack: {
      height: 3,
      backgroundColor: theme.border,
      borderRadius: 2,
      overflow: 'hidden',
      marginBottom: 8,
    },
    undoProgressBar: {
      height: 3,
      backgroundColor: theme.primary,
      borderRadius: 2,
    },
    filterBottomSpacer: {
      height: 12,
    },
    groupHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 4,
      paddingVertical: 8,
      marginTop: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      marginBottom: 4,
    },
    groupHeaderText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
  });
