import { StyleSheet } from 'react-native';
import type { Theme } from '../theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    editButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.card,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    photo: {
      width: '100%',
      height: 300,
    },
    photoPlaceholder: {
      backgroundColor: theme.backgroundSecondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: {
      padding: 24,
    },
    name: {
      fontSize: 32,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 4,
    },
    variety: {
      fontSize: 18,
      color: theme.textSecondary,
      fontStyle: 'italic',
      marginBottom: 16,
    },
    rowRecordBadge: {
      alignSelf: 'flex-start',
      backgroundColor: theme.primaryLight,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 4,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.primary,
    },
    rowRecordBadgeText: {
      fontSize: 13,
      color: theme.primary,
      fontWeight: '600',
    },
    infoSection: {
      marginBottom: 24,
    },
    careSection: {
      marginBottom: 24,
      backgroundColor: theme.card,
      padding: 16,
      borderRadius: 12,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    infoText: {
      fontSize: 16,
      color: theme.textSecondary,
      marginLeft: 12,
    },
    notesSection: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 12,
    },
    notesText: {
      fontSize: 16,
      color: theme.textSecondary,
      lineHeight: 24,
    },
    // Phase 1 & 2 styles
    seasonBox: {
      backgroundColor: theme.backgroundSecondary,
      padding: 12,
      borderRadius: 8,
      marginBottom: 12,
    },
    seasonTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 8,
    },
    seasonText: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 4,
    },
    seasonNotes: {
      fontSize: 13,
      color: theme.textTertiary,
      fontStyle: 'italic',
      marginTop: 4,
    },
    pestCard: {
      backgroundColor: theme.backgroundSecondary,
      padding: 12,
      borderRadius: 8,
      marginBottom: 8,
      borderLeftWidth: 3,
    },
    pestCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
      marginBottom: 4,
    },
    pestCardName: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.text,
      flex: 1,
    },
    severityBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    severityText: {
      fontSize: 10,
      fontWeight: '700',
    },
    resolvedBadgeDetail: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
    },
    resolvedTextDetail: {
      fontSize: 11,
      color: theme.success,
      fontWeight: '600',
    },
    pestCardDate: {
      fontSize: 12,
      color: theme.textSecondary,
      marginBottom: 4,
    },
    pestCardMeta: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 2,
    },
    pestCardNotes: {
      fontSize: 13,
      color: theme.textTertiary,
      fontStyle: 'italic',
      marginTop: 4,
    },
    seasonAlertCard: {
      backgroundColor: theme.warningLight,
      padding: 10,
      borderRadius: 8,
      marginBottom: 6,
      borderLeftWidth: 3,
      borderLeftColor: theme.warning,
    },
    seasonAlertName: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.warning,
      flex: 1,
    },
    seasonAlertTypeBadge: {
      backgroundColor: theme.warningLight,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    seasonAlertTypeText: {
      fontSize: 10,
      fontWeight: '600',
      color: theme.warning,
    },
    seasonAlertTip: {
      fontSize: 13,
      color: theme.text,
      marginTop: 4,
      lineHeight: 18,
    },
    tasksSection: {
      marginBottom: 24,
    },
    taskItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: theme.card,
      padding: 16,
      borderRadius: 12,
      marginBottom: 8,
    },
    taskLeft: {
      flex: 1,
    },
    taskType: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
    },
    taskFrequency: {
      fontSize: 14,
      color: theme.textSecondary,
      marginTop: 2,
    },
    taskStatus: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.primary,
    },
    taskDisabled: {
      color: theme.textTertiary,
    },
    centered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    link: {
      color: theme.primary,
      fontSize: 16,
      fontWeight: '600',
      marginTop: 16,
    },
    harvestSection: {
      backgroundColor: theme.card,
      padding: 16,
      borderRadius: 12,
      marginBottom: 16,
    },
    harvestHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    harvestStats: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 16,
    },
    statCard: {
      flex: 1,
      backgroundColor: theme.background,
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    statValue: {
      fontSize: 24,
      fontWeight: '700',
      color: theme.primary,
    },
    statLabel: {
      fontSize: 11,
      color: theme.textSecondary,
      marginTop: 4,
      textAlign: 'center',
    },
    recentTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 8,
    },
    harvestItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    harvestLeft: {
      flex: 1,
    },
    harvestDate: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 4,
    },
    harvestQuantity: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
    },
    harvestRight: {
      alignItems: 'flex-end',
    },
    qualityBadge: {
      fontSize: 24,
    },
    viewAllButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      marginTop: 8,
    },
    viewAllText: {
      fontSize: 14,
      color: theme.primary,
      fontWeight: '600',
      marginRight: 4,
    },
    emptyHarvest: {
      alignItems: 'center',
      paddingVertical: 32,
    },
    emptyHarvestText: {
      fontSize: 16,
      color: theme.textTertiary,
      marginTop: 12,
      marginBottom: 16,
    },
    addHarvestButton: {
      backgroundColor: theme.primary,
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 8,
    },
    addHarvestButtonText: {
      color: theme.buttonText,
      fontSize: 14,
      fontWeight: '600',
    },
    // Last Care Summary
    lastCareGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 4,
    },
    lastCareItem: {
      flex: 1,
      minWidth: '45%',
      backgroundColor: theme.background,
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    lastCareLabel: {
      fontSize: 12,
      color: theme.textSecondary,
      marginTop: 6,
    },
    lastCareDate: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.text,
      marginTop: 2,
    },
    // Image zoom modal
    zoomOverlay: {
      flex: 1,
      backgroundColor: theme.shadow,
      justifyContent: 'center',
      alignItems: 'center',
    },
    zoomClose: {
      position: 'absolute',
      top: 16,
      right: 16,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.textInverse + '33',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 10,
    },
    // Coconut metrics
    metricsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 4,
    },
    metricCard: {
      flex: 1,
      minWidth: '45%',
      backgroundColor: theme.background,
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    metricValue: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.primary,
      marginTop: 4,
    },
    metricLabel: {
      fontSize: 11,
      color: theme.textSecondary,
      marginTop: 4,
      textAlign: 'center',
    },
    metricWarning: {
      fontSize: 11,
      color: theme.error,
      fontWeight: '600',
      marginTop: 2,
    },
    // Companion planting
    companionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 4,
    },
    companionChip: {
      backgroundColor: theme.primaryLight,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 16,
    },
    companionChipText: {
      fontSize: 13,
      color: theme.primary,
      fontWeight: '500',
    },
    incompatibleChip: {
      backgroundColor: theme.errorLight,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 16,
    },
    incompatibleChipText: {
      fontSize: 13,
      color: theme.error,
      fontWeight: '500',
    },
    // Coconut age care tips
    careTipItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 6,
    },
    careTipBullet: {
      fontSize: 14,
      color: theme.primary,
      marginRight: 8,
      marginTop: 1,
    },
    careTipText: {
      fontSize: 14,
      color: theme.textSecondary,
      flex: 1,
      lineHeight: 20,
    },
    // Nutrient deficiency
    nutrientCard: {
      backgroundColor: theme.backgroundSecondary,
      padding: 12,
      borderRadius: 8,
      marginBottom: 8,
      borderLeftWidth: 3,
    },
    nutrientName: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 4,
    },
    nutrientSymptom: {
      fontSize: 13,
      color: theme.textSecondary,
      marginLeft: 8,
      marginBottom: 2,
    },
    nutrientCorrection: {
      fontSize: 13,
      color: theme.primary,
      marginLeft: 8,
      marginBottom: 2,
    },
    nutrientSubTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.text,
      marginTop: 6,
      marginBottom: 4,
    },
    // Common pest/disease awareness
    awarenessChip: {
      backgroundColor: theme.warningLight,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 16,
    },
    awarenessChipText: {
      fontSize: 12,
      color: theme.warning,
      fontWeight: '500',
    },
    awarenessRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 4,
      marginBottom: 8,
    },
    subsectionTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 6,
      marginTop: 8,
    },
    gestureRoot: {
      flex: 1,
    },
    zoomGestureContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    healthStatusHealthy: {
      color: theme.success,
      fontWeight: '600',
    },
    healthStatusSick: {
      color: theme.error,
      fontWeight: '600',
    },
    healthStatusWarning: {
      color: theme.warning,
      fontWeight: '600',
    },
    infoRowMarginTop: {
      marginTop: 12,
    },
    nutrientCardHigh: {
      borderLeftColor: theme.error,
    },
    nutrientCardMedium: {
      borderLeftColor: theme.warning,
    },
    nutrientCardLow: {
      borderLeftColor: theme.success,
    },
    growthStageBadge: {
      backgroundColor: theme.primaryLight,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 2,
      marginLeft: 8,
    },
    growthStageBadgeText: {
      fontSize: 11,
      fontWeight: '600' as const,
      color: theme.primary,
    },
    growthStageAction: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 4,
      marginTop: 4,
      marginLeft: 28,
    },
    growthStageActionText: {
      fontSize: 13,
      color: theme.primary,
      fontWeight: '500' as const,
    },
    sectionDivider: {
      height: 1,
      backgroundColor: theme.border,
      marginVertical: 12,
    },
    pinModalOverlay: {
      flex: 1,
      justifyContent: 'center',
    },
    pinModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.overlay,
    },
    pinModalSheet: {
      marginHorizontal: 24,
      borderRadius: 20,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 10,
      overflow: 'hidden',
    },
    pinModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    pinModalTitle: {
      fontSize: 17,
      fontWeight: '700' as const,
      color: theme.text,
    },
    pinModalCloseButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pinModalItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 14,
      gap: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
    },
    pinModalItemLast: {
      borderBottomWidth: 0,
    },
    pinModalItemText: {
      fontSize: 15,
      fontWeight: '500' as const,
      color: theme.text,
    },
    clearBedHint: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 12,
      lineHeight: 18,
    },
    clearBedButton: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 6,
      borderWidth: 1,
      borderRadius: 8,
      padding: 12,
      borderColor: theme.warning,
      backgroundColor: theme.warning + '20',
    },
    beejamruthaCta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginHorizontal: 16,
      marginBottom: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: theme.primaryLight,
      borderWidth: 1,
      borderColor: theme.primary + '40',
    },
    beejamruthaCtaText: {
      flex: 1,
      fontSize: 13,
      fontWeight: '600' as const,
      color: theme.text,
    },
  });
