import { StyleSheet } from 'react-native';
import type { Theme } from '../theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 12,
      backgroundColor: theme.tabBarBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    headerIconButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      backgroundColor: theme.primary,
    },
    title: {
      fontSize: 17,
      fontWeight: '700' as const,
      color: theme.text,
    },
    headerCenter: {
      flex: 1,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 6,
    },
    unsavedDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.warning,
    },
    saveText: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.buttonText,
    },
    saveButton: {
      backgroundColor: theme.primary,
      paddingHorizontal: 18,
      paddingVertical: 8,
      borderRadius: 20,
    },
    saveButtonDisabled: {
      backgroundColor: theme.borderDark,
    },
    saveTextDisabled: {
      color: theme.textTertiary,
    },
    cancelButton: {
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    cancelButtonText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 10,
    },
    scrollContent: {
      paddingBottom: 100,
    },
    photoButton: {
      alignSelf: 'center',
      marginTop: 8,
      marginBottom: 20,
    },
    photo: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 3,
      borderColor: theme.primaryLight,
    },
    photoPlaceholder: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: theme.border,
      borderStyle: 'dashed',
    },
    photoText: {
      marginTop: 4,
      fontSize: 11,
      color: theme.textTertiary,
      fontWeight: '600',
    },
    input: {
      backgroundColor: theme.inputBackground,
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
      fontSize: 16,
      color: theme.inputText,
      borderWidth: 1,
      borderColor: theme.inputBorder,
    },
    dateButton: {
      backgroundColor: theme.inputBackground,
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    dateButtonText: {
      fontSize: 16,
      color: theme.text,
      fontWeight: '500',
    },
    datePlaceholder: {
      fontSize: 16,
      color: theme.inputPlaceholder,
    },
    textArea: {
      height: 100,
      textAlignVertical: 'top',
    },
    noteCounter: {
      fontSize: 12,
      color: theme.textTertiary,
      textAlign: 'right',
      marginTop: 6,
    },
    spaceTypeContainer: {
      flexDirection: 'row',
      marginBottom: 12,
      gap: 12,
    },
    spaceTypeContainerCompact: {
      gap: 8,
    },
    spaceTypeButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      minWidth: 0,
    },
    spaceTypeButtonCompact: {
      paddingVertical: 12,
      paddingHorizontal: 8,
    },
    spaceTypeActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    spaceTypeText: {
      fontSize: 16,
      color: theme.textTertiary,
      marginLeft: 8,
      flexShrink: 1,
    },
    spaceTypeTextCompact: {
      fontSize: 14,
      marginLeft: 6,
    },
    spaceTypeTextActive: {
      color: theme.primary,
      fontWeight: '600',
    },
    label: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 8,
      marginTop: 4,
    },
    nicknameInputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.inputBackground,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.inputBorder,
    },
    nicknameInput: {
      flex: 1,
      padding: 16,
      fontSize: 16,
      color: theme.inputText,
    },
    nicknameClearButton: {
      paddingHorizontal: 12,
      paddingVertical: 16,
    },
    locationPreview: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.primaryLight,
      padding: 12,
      borderRadius: 8,
      marginBottom: 12,
    },
    locationPreviewText: {
      fontSize: 14,
      color: theme.primary,
      fontWeight: '600',
    },
    locationDefaultsHint: {
      fontSize: 12,
      color: theme.primary,
      marginTop: 6,
      marginBottom: 4,
      marginHorizontal: 2,
      fontStyle: 'italic',
    },
    sectionHeader: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.primary,
      marginTop: 16,
      marginBottom: 12,
    },
    checkboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.backgroundSecondary,
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    checkboxLabel: {
      fontSize: 16,
      color: theme.text,
      marginLeft: 12,
    },
    settingToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.backgroundSecondary,
      padding: 14,
      borderRadius: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    settingToggleActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    settingToggleLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
    },
    settingToggleIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      marginRight: 10,
    },
    settingToggleIconWrapActive: {
      borderColor: theme.primary,
      backgroundColor: theme.backgroundSecondary,
    },
    settingToggleLabel: {
      fontSize: 16,
      color: theme.text,
      fontWeight: '600',
      flexShrink: 1,
    },
    settingToggleLabelActive: {
      color: theme.primary,
    },
    settingSwitchTrack: {
      width: 44,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.border,
      justifyContent: 'center',
      paddingHorizontal: 3,
      marginLeft: 12,
    },
    settingSwitchTrackActive: {
      backgroundColor: theme.primary,
    },
    settingSwitchThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: theme.backgroundSecondary,
      alignSelf: 'flex-start',
    },
    settingSwitchThumbActive: {
      alignSelf: 'flex-end',
    },
    smartDefaultsToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.backgroundSecondary,
      padding: 14,
      borderRadius: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    smartDefaultsToggleActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    smartDefaultsLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
    },
    smartDefaultsIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      marginRight: 10,
    },
    smartDefaultsIconWrapActive: {
      borderColor: theme.primary,
      backgroundColor: theme.backgroundSecondary,
    },
    smartDefaultsLabel: {
      fontSize: 16,
      color: theme.text,
      fontWeight: '600',
      flexShrink: 1,
    },
    smartDefaultsLabelCompact: {
      fontSize: 15,
    },
    smartDefaultsLabelActive: {
      color: theme.primary,
    },
    smartDefaultsSwitchTrack: {
      width: 44,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.border,
      justifyContent: 'center',
      paddingHorizontal: 3,
      marginLeft: 12,
    },
    smartDefaultsSwitchTrackActive: {
      backgroundColor: theme.primary,
    },
    smartDefaultsSwitchThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: theme.backgroundSecondary,
      alignSelf: 'flex-start',
    },
    smartDefaultsSwitchThumbActive: {
      alignSelf: 'flex-end',
    },
    helperText: {
      fontSize: 12,
      color: theme.textTertiary,
      marginTop: -2,
      marginBottom: 12,
      marginLeft: 4,
    },
    // --- Plant Category chip selector ---
    categoryChipsScroll: {
      marginBottom: 12,
    },
    categoryChipsContent: {
      paddingRight: 8,
      gap: 8,
    },
    categoryChip: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    categoryChipActive: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    categoryChipText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textTertiary,
    },
    categoryChipTextActive: {
      color: theme.primary,
    },
    // --- Field group visual divider ---
    fieldGroupDivider: {
      height: 1,
      backgroundColor: theme.borderLight,
      marginVertical: 16,
      marginHorizontal: 4,
    },
    fieldGroupLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 10,
      marginTop: 2,
    },
    // --- Direction/Section chips ---
    directionChipsWrapper: {
      borderWidth: 1,
      borderColor: theme.inputBorder,
      borderRadius: 12,
      backgroundColor: theme.inputBackground,
      paddingHorizontal: 12,
      paddingTop: 16,
      paddingBottom: 12,
      marginBottom: 12,
    },
    directionChipsFloatingLabel: {
      position: 'absolute' as const,
      top: -9,
      left: 12,
      paddingHorizontal: 4,
      fontSize: 12,
      fontWeight: '500' as const,
      color: theme.textSecondary,
      backgroundColor: theme.backgroundSecondary,
    },
    directionChipsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    directionChip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 18,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1.5,
      borderColor: theme.border,
      gap: 5,
    },
    directionChipActive: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    directionChipText: {
      fontSize: 13,
      fontWeight: '500',
      color: theme.textTertiary,
    },
    directionChipTextActive: {
      color: theme.primary,
      fontWeight: '700',
    },
    // --- Display Name Card ---
    displayNameCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    displayNameHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    displayNameLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    displayNameLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    autoGenBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: theme.primaryLight,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
    },
    autoGenBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.primary,
    },
    displayNameHelper: {
      fontSize: 12,
      color: theme.textTertiary,
      marginTop: 4,
      marginLeft: 2,
    },
    // --- Date Card ---
    dateCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
      overflow: 'hidden',
    },
    dateCardTouchable: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
    },
    dateCardIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    dateCardContent: {
      flex: 1,
    },
    dateCardLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textTertiary,
      letterSpacing: 0.5,
      marginBottom: 2,
    },
    dateCardValue: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
    },
    dateCardPlaceholder: {
      fontSize: 15,
      color: theme.inputPlaceholder,
    },
    optionalBadge: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 6,
      paddingHorizontal: 6,
      paddingVertical: 1,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    optionalBadgeText: {
      fontSize: 10,
      fontWeight: '600' as const,
      color: theme.textTertiary,
      letterSpacing: 0.3,
    },
    // --- Frequency Row (Water/Feed/Prune inline cards) ---
    frequencyRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 12,
    },
    frequencyCard: {
      flex: 1,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      padding: 12,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    frequencyIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
    },
    frequencyCardLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    frequencyInputWrap: {
      backgroundColor: theme.inputBackground,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      width: '100%',
      alignItems: 'center',
      marginBottom: 4,
    },
    frequencyInput: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.text,
      textAlign: 'center',
      paddingVertical: 6,
      paddingHorizontal: 8,
      minWidth: 50,
    },
    frequencyUnit: {
      fontSize: 11,
      color: theme.textTertiary,
      fontWeight: '600',
    },
    // --- Stat Cards (Coconut metrics) ---
    statCardsRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 8,
    },
    statCard: {
      flex: 1,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      padding: 10,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    statCardIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    statCardLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 4,
    },
    statCardInputWrap: {
      backgroundColor: theme.inputBackground,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      width: '100%',
      alignItems: 'center',
    },
    statCardInput: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.text,
      textAlign: 'center',
      paddingVertical: 4,
      paddingHorizontal: 4,
      minWidth: 40,
    },
    // --- Notes Card ---
    notesCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    notesCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 8,
    },
    notesCardInput: {
      backgroundColor: theme.inputBackground,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      padding: 12,
      fontSize: 15,
      color: theme.inputText,
      minHeight: 80,
      textAlignVertical: 'top',
    },
    // --- Add Pest Button Pill ---
    addPestButtonPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: theme.primaryLight,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.primary,
    },
    addPestButtonText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.primary,
    },
    infoCard: {
      backgroundColor: theme.backgroundSecondary,
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderDark,
    },
    infoCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    infoCardTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      flex: 1,
    },
    infoCardText: {
      fontSize: 16,
      color: theme.primary,
      fontWeight: '600',
      marginBottom: 4,
    },
    infoCardSubtext: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 8,
    },
    chipContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 8,
    },
    varietySuggestions: {
      marginBottom: 12,
    },
    suggestionLabel: {
      fontSize: 12,
      color: theme.textSecondary,
      marginBottom: 6,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    varietySuggestionChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    varietySuggestionChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: theme.primaryLight,
      borderWidth: 1,
      borderColor: theme.primary,
    },
    varietySuggestionText: {
      fontSize: 12,
      color: theme.primary,
      fontWeight: '600',
    },
    companionChip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      gap: 4,
    },
    companionChipSelected: {
      backgroundColor: theme.accentLight,
      borderColor: theme.accent,
    },
    companionChipText: {
      fontSize: 13,
      color: theme.textSecondary,
    },
    companionChipTextSelected: {
      color: theme.accent,
      fontWeight: '600',
    },
    incompatibleChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: theme.warningLight,
      borderWidth: 1,
      borderColor: theme.warning,
    },
    incompatibleChipText: {
      fontSize: 13,
      color: theme.warning,
      fontWeight: '600',
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 16,
      marginBottom: 12,
    },
    sectionHeaderText: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.text,
      flex: 1,
    },
    addPestButton: {
      padding: 4,
    },
    pestDiseaseList: {
      marginBottom: 16,
    },
    pestDiseaseCard: {
      backgroundColor: theme.backgroundSecondary,
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderDark,
      position: 'relative',
    },
    pestDiseaseHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    pestDiseaseName: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      flex: 1,
    },
    resolvedBadge: {
      backgroundColor: theme.primaryLight,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
    },
    resolvedText: {
      fontSize: 11,
      color: theme.primary,
      fontWeight: '600',
    },
    pestDiseaseDate: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 4,
    },
    pestDiseaseMetaText: {
      fontSize: 12,
      color: theme.textTertiary,
      marginBottom: 4,
      fontWeight: '500',
    },
    pestDiseaseTreatment: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 4,
    },
    pestDiseaseNotes: {
      fontSize: 13,
      color: theme.textSecondary,
      fontStyle: 'italic',
    },
    deletePestButton: {
      position: 'absolute',
      top: 12,
      right: 12,
      padding: 4,
    },
    noPestHistory: {
      fontSize: 14,
      color: theme.textTertiary,
      textAlign: 'center',
      paddingVertical: 20,
      fontStyle: 'italic',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'flex-end',
    },
    discardOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 32,
    },
    discardCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 20,
      padding: 28,
      alignItems: 'center',
      width: '100%',
      maxWidth: 340,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 24,
      elevation: 12,
    },
    discardIconWrap: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.errorLight,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    discardTitle: {
      fontSize: 19,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 8,
    },
    discardMessage: {
      fontSize: 14,
      color: theme.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 24,
    },
    discardActions: {
      flexDirection: 'row',
      gap: 12,
      width: '100%',
    },
    discardKeepButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 13,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    discardKeepText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.primary,
    },
    discardButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 13,
      borderRadius: 12,
      backgroundColor: theme.error,
    },
    discardButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textInverse,
    },
    modalContent: {
      backgroundColor: theme.backgroundSecondary,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingTop: 20,
      paddingHorizontal: 20,
      maxHeight: '85%',
    },
    modalScrollView: {
      flexGrow: 0,
      marginBottom: 20,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    modalCloseButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.text,
    },
    typeButtons: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 16,
    },
    typeButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      borderRadius: 12,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      gap: 8,
    },
    typeButtonActive: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    typeButtonText: {
      fontSize: 15,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    typeButtonTextActive: {
      color: theme.primary,
      fontWeight: '600',
    },
    suggestionsScroll: {
      marginBottom: 12,
    },
    suggestionGroupContainer: {
      marginBottom: 12,
    },
    suggestionGroup: {
      marginBottom: 8,
    },
    suggestionGroupLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 6,
      letterSpacing: 0.3,
    },
    suggestionGroupChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    suggestionChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 16,
      backgroundColor: theme.accentLight,
      marginRight: 8,
    },
    suggestionChipText: {
      fontSize: 13,
      color: theme.accent,
    },
    suggestionChipActive: {
      backgroundColor: theme.primary,
    },
    suggestionChipTextActive: {
      color: theme.textInverse,
    },
    treatmentGroupContainer: {
      marginBottom: 8,
    },
    treatmentGroup: {
      marginBottom: 8,
    },
    treatmentGroupLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 6,
      letterSpacing: 0.3,
    },
    treatmentGroupChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    treatmentChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 16,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 4,
    },
    treatmentChipActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    treatmentChipText: {
      fontSize: 13,
      color: theme.textSecondary,
    },
    treatmentChipTextActive: {
      color: theme.textInverse,
      fontWeight: '600',
    },
    affectedPartChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 12,
    },
    affectedPartChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 16,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    affectedPartChipActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    affectedPartChipText: {
      fontSize: 13,
      color: theme.textSecondary,
    },
    affectedPartChipTextActive: {
      color: theme.textInverse,
      fontWeight: '600',
    },
    pestPhotoButton: {
      marginBottom: 12,
      alignSelf: 'flex-start',
    },
    pestPhotoPreviewWrap: {
      position: 'relative',
    },
    pestPhotoPreview: {
      width: 100,
      height: 100,
      borderRadius: 8,
    },
    pestPhotoRemoveBtn: {
      position: 'absolute',
      top: -6,
      right: -6,
    },
    pestPhotoPlaceholder: {
      width: 100,
      height: 100,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: theme.border,
      borderStyle: 'dashed',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.backgroundSecondary,
    },
    pestPhotoPlaceholderText: {
      fontSize: 11,
      color: theme.textTertiary,
      marginTop: 4,
    },
    modalSaveButton: {
      backgroundColor: theme.primary,
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
      marginTop: 16,
    },
    modalSaveButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.textInverse,
    },
    charCounter: {
      fontSize: 12,
      color: theme.textTertiary,
      textAlign: 'right' as const,
      marginTop: -6,
    },

    // --- #2 Photo Hero ---
    photoHeroContainer: {
      width: '100%',
      height: 180,
      borderRadius: 14,
      overflow: 'hidden' as const,
      marginBottom: 12,
      backgroundColor: theme.primaryLight,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    photoHeroImage: {
      width: '100%',
      height: '100%',
    },
    photoHeroPlaceholder: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    photoHeroPlaceholderText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.primary,
    },
    photoHeroEditBadge: {
      position: 'absolute' as const,
      bottom: 10,
      right: 10,
      backgroundColor: theme.overlay,
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 5,
      flexDirection: 'row' as const,
      alignItems: 'center',
      gap: 5,
    },
    photoHeroEditBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textInverse,
    },

    // --- #3 Frequency Presets ---
    frequencyPresetsRow: {
      flexDirection: 'row' as const,
      flexWrap: 'wrap' as const,
      gap: 6,
      marginBottom: 8,
    },
    frequencyPresetChip: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
    },
    frequencyPresetChipActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    frequencyPresetChipText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textTertiary,
    },
    frequencyPresetChipTextActive: {
      color: theme.primary,
    },

    // --- #7 Sticky Save Button ---
    stickySaveContainer: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: theme.background,
      borderTopWidth: 1,
      borderTopColor: theme.borderLight,
    },
    stickySaveButton: {
      backgroundColor: theme.primary,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: 'center' as const,
      flexDirection: 'row' as const,
      justifyContent: 'center' as const,
      gap: 8,
    },
    stickySaveButtonDisabled: {
      backgroundColor: theme.borderDark,
    },
    stickySaveButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.textInverse,
    },
    stickySaveErrorBadge: {
      backgroundColor: theme.error,
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 2,
    },
    stickySaveErrorBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textInverse,
    },

    // --- #9 Auto-Name Preview Inline ---
    namePreviewRow: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      backgroundColor: theme.inputBackground,
      borderRadius: 12,
      paddingHorizontal: 16,
      minHeight: 52,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      gap: 8,
    },
    namePreviewFloatingLabel: {
      position: 'absolute' as const,
      top: -9,
      left: 12,
      paddingHorizontal: 4,
      fontSize: 12,
      fontWeight: '500' as const,
      color: theme.textSecondary,
      backgroundColor: theme.backgroundSecondary,
    },
    namePreviewLabel: {
      fontSize: 12,
      color: theme.textTertiary,
      fontWeight: '600' as const,
    },
    namePreviewValue: {
      fontSize: 14,
      color: theme.text,
      fontWeight: '600' as const,
      flex: 1,
    },
    namePreviewValuePending: {
      fontSize: 13,
      color: theme.textTertiary,
      fontStyle: 'italic',
      flex: 1,
    },
    nameCustomRow: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      backgroundColor: theme.inputBackground,
      borderRadius: 12,
      paddingLeft: 16,
      paddingRight: 10,
      minHeight: 52,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.inputBorder,
    },
    nameCustomInput: {
      flex: 1,
      fontSize: 14,
      fontWeight: '600' as const,
      color: theme.inputText,
      paddingVertical: 14,
      paddingRight: 8,
    },
    nameCustomActions: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      gap: 6,
      flexShrink: 0,
    },
    nameCustomClear: {
      padding: 4,
    },
    namePreviewActionUse: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
      backgroundColor: theme.primaryLight,
    },
    namePreviewActionCustom: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    namePreviewActionText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.primary,
    },
    namePreviewActionTextMuted: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textTertiary,
    },

    // --- #4 Care Profile Card ---
    careProfileCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
      borderLeftWidth: 4,
      borderLeftColor: theme.success,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    careProfileCardHeader: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    careProfileCardTitleRow: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      gap: 6,
    },
    careProfileCardTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.success,
    },
    careProfileCardRow: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      gap: 6,
      marginBottom: 3,
    },
    careProfileCardText: {
      fontSize: 13,
      color: theme.textSecondary,
    },
    careProfileCardDismiss: {
      padding: 4,
    },

    // --- #8 Space Type Visual Cards ---
    spaceTypeCardsRow: {
      flexDirection: 'row' as const,
      gap: 10,
      marginBottom: 12,
    },
    spaceTypeCard: {
      flex: 1,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      paddingVertical: 16,
      paddingHorizontal: 6,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: theme.border,
    },
    spaceTypeCardActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryLight,
    },
    spaceTypeCardIcon: {
      marginBottom: 6,
    },
    spaceTypeCardLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textTertiary,
      textAlign: 'center' as const,
    },
    spaceTypeCardLabelActive: {
      color: theme.primary,
    },

    // --- #1 Phase Gates ---
    phaseLockedBanner: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      gap: 10,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
      opacity: 0.75,
    },
    phaseLockedText: {
      fontSize: 14,
      color: theme.textTertiary,
      fontStyle: 'italic',
      flex: 1,
    },
    moreDetailsTouchable: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      justifyContent: 'center' as const,
      gap: 8,
      padding: 14,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    moreDetailsText: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.primary,
    },

    // --- #10 Quick Add Fast Path ---
    quickSaveWithDefaultsButton: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 18,
      alignItems: 'center' as const,
      flexDirection: 'row' as const,
      justifyContent: 'center' as const,
      gap: 8,
      marginBottom: 12,
      borderWidth: 1.5,
      borderColor: theme.primary,
      borderStyle: 'dashed' as const,
    },
    quickSaveWithDefaultsText: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.primary,
    },

    // --- D: Chip Grid (replaces horizontal ScrollView) ---
    chipGrid: {
      flexDirection: 'row' as const,
      flexWrap: 'wrap' as const,
      gap: 8,
      marginBottom: 12,
    },
    chipGridItem: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    chipGridItemActive: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary,
    },
    chipGridItemText: {
      fontSize: 13,
      fontWeight: '600' as const,
      color: theme.textTertiary,
    },
    chipGridItemTextActive: {
      color: theme.primary,
      fontWeight: '700' as const,
    },

    // --- E: Frequency Stepper ---
    stepperCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    stepperHeader: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    stepperIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: theme.primaryLight,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    stepperLabel: {
      fontSize: 14,
      fontWeight: '700' as const,
      color: theme.text,
    },
    stepperRow: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      justifyContent: 'center' as const,
      gap: 16,
    },
    stepperButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.background,
      borderWidth: 2,
      borderColor: theme.primary,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    stepperValueWrap: {
      alignItems: 'center' as const,
      minWidth: 80,
    },
    stepperValueInput: {
      fontSize: 28,
      fontWeight: '800' as const,
      color: theme.text,
      textAlign: 'center' as const,
      paddingVertical: 2,
      paddingHorizontal: 8,
      minWidth: 60,
    },
    stepperUnit: {
      fontSize: 12,
      fontWeight: '600' as const,
      color: theme.textTertiary,
      marginTop: 2,
    },
    stepperHint: {
      fontSize: 12,
      fontWeight: '700' as const,
      textAlign: 'center' as const,
      marginTop: 8,
    },

    // --- B: Grouped Field Card ---
    groupedFieldCard: {
      flexDirection: 'row' as const,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.borderLight,
      overflow: 'hidden' as const,
    },
    groupedFieldCardAccent: {
      width: 4,
      backgroundColor: theme.primary,
    },
    groupedFieldCardContent: {
      flex: 1,
      padding: 14,
    },
    groupedFieldCardTitle: {
      fontSize: 13,
      fontWeight: '700' as const,
      color: theme.primary,
      textTransform: 'uppercase' as const,
      letterSpacing: 0.8,
      marginBottom: 12,
    },
    waterDropsRow: {
      flexDirection: 'row' as const,
      gap: 1,
    },

    // --- H: Smart Defaults Banner ---
    smartDefaultsBanner: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      backgroundColor: `${theme.info}18`,
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: `${theme.info}55`,
      gap: 10,
    },
    smartDefaultsBannerLeft: {
      flexDirection: 'row' as const,
      alignItems: 'center',
      flex: 1,
      gap: 8,
    },
    smartDefaultsBannerTextWrap: {
      flex: 1,
    },
    smartDefaultsBannerTitle: {
      fontSize: 13,
      fontWeight: '700' as const,
      color: theme.info,
      marginBottom: 2,
    },
    smartDefaultsBannerSummary: {
      fontSize: 12,
      fontWeight: '600' as const,
      color: theme.textSecondary,
    },
    smartDefaultsBannerDismiss: {
      padding: 4,
    },
  });
