import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme/colors';

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    sheetOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'flex-end' as const,
    },
    sheet: {
      backgroundColor: theme.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      height: '85%' as const,
      paddingBottom: 24,
    },
    handle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.border,
      alignSelf: 'center' as const,
      marginTop: 10,
      marginBottom: 4,
    },
    sheetTitle: {
      fontSize: 16,
      fontWeight: '700' as const,
      color: theme.text,
      textAlign: 'center' as const,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    searchBarContainer: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      marginHorizontal: 12,
      marginTop: 10,
      marginBottom: 4,
      paddingHorizontal: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundSecondary,
      gap: 6,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: theme.text,
      paddingVertical: 9,
    },
    listContent: {
      paddingBottom: 16,
    },
    categoryHeader: {
      fontSize: 10,
      fontWeight: '700' as const,
      color: theme.textTertiary,
      letterSpacing: 0.8,
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 4,
      textTransform: 'uppercase' as const,
    },
    row: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
      gap: 12,
    },
    rowSelected: {
      backgroundColor: theme.primaryLight,
    },
    emojiCircle: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    emoji: {
      fontSize: 20,
    },
    rowMeta: { flex: 1 },
    rowName: {
      fontSize: 15,
      fontWeight: '600' as const,
      color: theme.text,
    },
    badgeRow: {
      flexDirection: 'row' as const,
      gap: 6,
      marginTop: 4,
      flexWrap: 'wrap' as const,
    },
    categoryBadge: {
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 8,
      backgroundColor: theme.backgroundTertiary,
    },
    categoryBadgeText: {
      fontSize: 10,
      color: theme.textSecondary,
      fontWeight: '600' as const,
    },
    seasonBadge: {
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 8,
      backgroundColor: theme.primaryLight,
    },
    seasonBadgeText: {
      fontSize: 10,
      color: theme.primary,
      fontWeight: '600' as const,
    },
    pinnedLabel: {
      fontSize: 10,
      fontWeight: '700' as const,
      color: theme.textTertiary,
      letterSpacing: 0.8,
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 4,
      textTransform: 'uppercase' as const,
    },
    emptyState: {
      alignItems: 'center' as const,
      paddingVertical: 32,
    },
    emptyStateText: {
      fontSize: 13,
      color: theme.textTertiary,
      marginTop: 8,
      textAlign: 'center' as const,
      paddingHorizontal: 24,
    },
  });
