import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme/colors';

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 16,
      backgroundColor: theme.tabBarBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    backButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    title: { flex: 1, fontSize: 20, fontWeight: '700', color: theme.text },
    content: { padding: 16 },
    sectionLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 10,
      marginTop: 4,
    },
    stepperRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 10,
      padding: 14,
      marginBottom: 4,
      borderWidth: 1,
      borderColor: theme.border,
    },
    stepperLabel: { fontSize: 14, color: theme.text, flex: 1 },
    stepperControls: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    stepperButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperButtonText: { fontSize: 18, fontWeight: '700', color: theme.primary },
    stepperValue: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.primary,
      minWidth: 32,
      textAlign: 'center',
    },
    helperText: {
      fontSize: 12,
      color: theme.textSecondary,
      marginTop: 4,
      marginBottom: 16,
      paddingHorizontal: 4,
    },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 24 },
    chip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    chipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
    chipText: { fontSize: 13, color: theme.textSecondary },
    chipTextActive: { fontSize: 13, color: theme.textInverse, fontWeight: '600' },
    saveButton: {
      backgroundColor: theme.primary,
      borderRadius: 10,
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 8,
    },
    saveButtonDisabled: { opacity: 0.5 },
    saveButtonText: { color: theme.textInverse, fontSize: 16, fontWeight: '700' },
  });
