/**
 * AUTO-GENERATED by scripts/reference/ingest-images.js — DO NOT EDIT.
 *
 * Maps reference-entry ids to bundled WebP images in `assets/reference/`.
 * Regenerate by dropping source images into `assets-src/<kind>/` and running
 * `npm run reference:ingest`. Keys are validated against config ids by
 * src/__tests__/config/referenceAssets.test.ts.
 */

import type { ImageSource } from 'expo-image';

export const PEST_IMAGES: Record<string, ImageSource> = {};

export const DISEASE_IMAGES: Record<string, ImageSource> = {};

export const PLANT_IMAGES: Record<string, ImageSource> = {};
