/**
 * Public API for bundled pest, disease, catalog-plant, and organic-input reference images.
 *
 * The static `require()` maps live in `referenceImages.gen.ts`, regenerated by
 * `npm run reference:ingest` from the WebP files present in `assets/reference/`
 * (React Native/Metro needs static require literals, so the maps are codegen,
 * never hand-edited). Workflow:
 *
 * 1. `npm run reference:manifest` — writes `assets-src/manifest.json` +
 *    `assets-src/PROMPTS.md` with one image-generation prompt per entry.
 * 2. Drop generated/real images into `assets-src/{pests,diseases,plants,organic-inputs}/`
 *    named `<id>.<ext>`.
 * 3. `npm run reference:ingest` — resizes/compresses to ≤50 KB 400×300 WebP in
 *    `assets/reference/` and regenerates `referenceImages.gen.ts`.
 *
 * Every consumer falls back to a themed semantic icon when no image is bundled.
 */

import type { ImageSource } from 'expo-image';

import {
  DISEASE_IMAGES,
  ORGANIC_INPUT_IMAGES,
  PEST_IMAGES,
  PLANT_IMAGES,
} from './referenceImages.gen';
import { resolvePlantImageKey } from './referenceKeys';

export { PLANT_IMAGE_ALIASES, slugifyReferenceKey } from './referenceKeys';

/**
 * The `cachePolicy` every bundled reference image must render with.
 *
 * These assets are baked into the app binary, so the disk cache buys nothing — the bytes are on
 * local storage either way. Worse, its key derives from the asset path (Android flattens
 * `assets/reference/plants/brinjal.webp` to the drawable `assets_reference_plants_brinjal`), not
 * from the content, and the cache directory survives an install-over-the-top app update. A
 * re-ingested image would therefore keep serving the old bitmap on every existing install until
 * the user uninstalled. Memory-only avoids that at no real cost.
 *
 * User-captured photos are unaffected and keep `memory-disk`: their URIs are already unique per
 * photo, so they never go stale, and persisting them across cold starts is worth it.
 */
export const REFERENCE_IMAGE_CACHE_POLICY = 'memory' as const;

/**
 * Returns the bundled image for a pest, or undefined if none exists.
 * Uses `imageAsset` if set, otherwise falls back to the pest's `id`.
 */
export function getPestImage(id: string, imageAsset?: string): ImageSource | undefined {
  return PEST_IMAGES[imageAsset ?? id];
}

/**
 * Returns the bundled image for a disease, or undefined if none exists.
 * Uses `imageAsset` if set, otherwise falls back to the disease's `id`.
 */
export function getDiseaseImage(id: string, imageAsset?: string): ImageSource | undefined {
  return DISEASE_IMAGES[imageAsset ?? id];
}

/**
 * Returns the bundled catalog image for a plant name, or undefined if none
 * exists. Keyed by slugified plant name with alias resolution; custom user
 * plants simply resolve to undefined (the UI supplies a leaf-icon fallback).
 */
export function getPlantImage(plantName: string): ImageSource | undefined {
  return PLANT_IMAGES[resolvePlantImageKey(plantName)];
}

/**
 * Returns the bundled image for an organic input, or undefined if none exists.
 * Uses `imageAsset` if set, otherwise falls back to the input's `id`.
 */
export function getOrganicInputImage(id: string, imageAsset?: string): ImageSource | undefined {
  return ORGANIC_INPUT_IMAGES[imageAsset ?? id];
}
