import type { PlantCatalogEntry } from '../types';

export const FLOWER_ENTRIES: PlantCatalogEntry[] = [
  {
    name: 'Marigold',
    group: 'flowers',
    subGroup: 'seasonal_flowers',
    habit: 'annual_bed',
    tags: ['puja', 'companion', 'pest_repellent'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'செண்டுமல்லி',
    shortDescription: 'Bright orange-yellow blooms that repel nematodes and attract pollinators',
    varieties: ['African', 'French', 'Local Orange'],
  },
  {
    name: 'Jasmine',
    group: 'flowers',
    subGroup: 'flowering_shrubs',
    habit: 'shrub',
    tags: ['puja'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'மல்லிகை',
    shortDescription:
      'Intensely fragrant evergreen shrub producing white flowers integral to Tamil culture',
    varieties: ['Malli', 'Mullai', 'Jathi Malli'],
  },
  {
    name: 'Hibiscus',
    group: 'flowers',
    subGroup: 'flowering_shrubs',
    habit: 'shrub',
    tags: ['puja', 'medicinal'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'செம்பருத்தி',
    shortDescription:
      'Showy tropical shrub producing large colourful blooms for hair oil and offerings',
    varieties: ['Red', 'Yellow', 'Double Petal'],
  },
  {
    name: 'Rose',
    group: 'flowers',
    subGroup: 'flowering_shrubs',
    habit: 'shrub',
    tags: ['puja'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'ரோஜா',
    shortDescription: 'Classic garden shrub grown for fragrant blooms',
  },
  {
    name: 'Chrysanthemum',
    group: 'flowers',
    subGroup: 'seasonal_flowers',
    habit: 'annual_bed',
    tags: ['puja'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'சாமந்தி',
    shortDescription: 'Popular festival flower grown for bright disc-shaped blooms',
  },
  {
    name: 'Crossandra',
    group: 'flowers',
    subGroup: 'flowering_shrubs',
    habit: 'perennial',
    tags: ['puja'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'கனகாம்பரம்',
    shortDescription: 'Low-growing perennial bearing vibrant orange flowers for garlands',
  },
  {
    name: 'Ixora',
    group: 'flowers',
    subGroup: 'flowering_shrubs',
    habit: 'shrub',
    tags: ['puja'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'வெட்சி',
    shortDescription: 'Evergreen tropical shrub with dense clusters of tiny tubular flowers',
  },
  {
    name: 'Sunflower',
    group: 'flowers',
    subGroup: 'seasonal_flowers',
    habit: 'annual_bed',
    tags: [],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'சூரியகாந்தி',
    shortDescription: 'Tall, cheerful annual grown for large composite flower heads',
  },
  // Moved from `shrub`: woody, but grown for the bloom — nandiyavattai
  // and arali poo for the temple, aavarampoo for the flower itself.
  {
    name: 'Nandiyavattai',
    group: 'flowers',
    subGroup: 'flowering_shrubs',
    habit: 'shrub',
    tags: ['puja'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'நந்தியாவட்டை',
    shortDescription: 'Fragrant white-flowered shrub sacred in Tamil temple gardens',
  },
  {
    name: 'Aavaram',
    group: 'farm_support',
    habit: 'shrub',
    tags: ['green_manure', 'living_fence'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'ஆவாரம்',
    shortDescription:
      'Dryland-hardy shrub grown for its yellow aavarampoo flowers; fixes nitrogen and holds bunds together',
  },
  {
    name: 'Arali',
    group: 'flowers',
    subGroup: 'flowering_shrubs',
    habit: 'shrub',
    tags: ['puja'],
    plantType: 'flower',
    cropFamily: 'flower',
    tamilName: 'அரளி',
    shortDescription:
      'Temple flowering shrub, drought-hardy and long-blooming. Every part is toxic if eaten and the sap irritates skin — plant it away from children, pets and the vegetable beds',
    varieties: ['White', 'Pink', 'Red'],
  },
];
