import type { PlantCatalogEntry } from '../types';

export const HERB_ENTRIES: PlantCatalogEntry[] = [
  {
    name: 'Coriander',
    group: 'herbs_medicinal',
    subGroup: 'kitchen_herbs',
    habit: 'annual_bed',
    tags: ['spice'],
    plantType: 'herb',
    cropFamily: 'apiaceae',
    tamilName: 'கொத்தமல்லி',
    shortDescription: 'Fast-growing cool-season herb prized for its aromatic leaves and seeds',
    varieties: ['CO 4', 'CO 5', 'Local'],
  },
  {
    name: 'Mint',
    group: 'herbs_medicinal',
    subGroup: 'kitchen_herbs',
    habit: 'perennial',
    tags: ['container_ok'],
    plantType: 'herb',
    cropFamily: 'lamiaceae',
    tamilName: 'புதினா',
    shortDescription: 'Vigorous spreading herb that thrives in moist, partially shaded spots',
    varieties: ['Peppermint', 'Spearmint', 'Country Mint'],
  },
  {
    name: 'Curry Leaf',
    group: 'herbs_medicinal',
    subGroup: 'kitchen_herbs',
    habit: 'tree',
    tags: [],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'கறிவேப்பிலை',
    shortDescription: 'Essential South Indian culinary tree producing intensely aromatic leaves',
    varieties: ['Dwarf', 'Regular', 'Local'],
  },
  {
    name: 'Lemongrass',
    group: 'herbs_medicinal',
    subGroup: 'kitchen_herbs',
    habit: 'clump',
    tags: ['medicinal'],
    plantType: 'herb',
    cropFamily: 'poaceae',
    tamilName: 'எலுமிச்சைப்புல்',
    shortDescription: 'Tall aromatic grass used in teas and South-East Asian cuisine',
    varieties: ['East Indian', 'West Indian', 'Local'],
  },
  {
    name: 'Tulsi',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'shrub',
    tags: ['medicinal', 'puja'],
    plantType: 'herb',
    cropFamily: 'lamiaceae',
    tamilName: 'துளசி',
    shortDescription:
      'Sacred herb of Indian households valued for medicinal and spiritual significance',
    varieties: ['Krishna Tulsi', 'Rama Tulsi'],
  },
  {
    name: 'Basil',
    group: 'herbs_medicinal',
    subGroup: 'kitchen_herbs',
    habit: 'annual_bed',
    tags: ['container_ok'],
    plantType: 'herb',
    cropFamily: 'lamiaceae',
    tamilName: 'திருநீற்றுப்பச்சிலை',
    shortDescription: 'Aromatic culinary herb used in Italian and Thai cooking',
  },
  {
    name: 'Dill',
    group: 'herbs_medicinal',
    subGroup: 'kitchen_herbs',
    habit: 'annual_bed',
    tags: [],
    plantType: 'herb',
    cropFamily: 'apiaceae',
    tamilName: 'சதகுப்பை',
    shortDescription: 'Feathery herb with a mild anise flavour, popular in pickles and rice dishes',
  },
  // Kanyakumari spices grown as herbs
  {
    name: 'Turmeric',
    group: 'spices',
    subGroup: 'rhizome',
    habit: 'perennial',
    tags: ['spice', 'medicinal'],
    plantType: 'herb',
    cropFamily: 'zingiberaceae',
    tamilName: 'மஞ்சள்',
    shortDescription: 'Tropical rhizomatous herb yielding the golden spice of Indian cooking',
    varieties: ['Erode Local', 'Salem', 'Finger Turmeric', 'CO 1'],
  },
  {
    name: 'Ginger',
    group: 'spices',
    subGroup: 'rhizome',
    habit: 'perennial',
    tags: ['spice', 'medicinal'],
    plantType: 'herb',
    cropFamily: 'zingiberaceae',
    tamilName: 'இஞ்சி',
    shortDescription: 'Pungent rhizome staple in South Indian cooking and Ayurvedic medicine',
    varieties: ['Maran', 'Rio-de-Janeiro', 'Nadia', 'Local'],
  },
  {
    name: 'Betel Leaf',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'vine',
    tags: ['masticatory', 'medicinal'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'வெற்றிலை',
    shortDescription: 'Tropical climbing vine prized for its glossy heart-shaped leaves',
    varieties: ['Vetrilai', 'Kapur', 'Local'],
  },
  // Spice bed plants
  {
    name: 'Ajwain',
    group: 'spices',
    subGroup: 'seed_clump',
    habit: 'annual_bed',
    tags: ['spice', 'medicinal'],
    plantType: 'herb',
    cropFamily: 'apiaceae',
    tamilName: 'ஓமம்',
    shortDescription:
      'Aromatic annual herb yielding carom seeds used in South Indian tempering and digestive remedies',
  },
  {
    name: 'Cardamom',
    group: 'spices',
    subGroup: 'seed_clump',
    habit: 'clump',
    tags: ['spice'],
    plantType: 'herb',
    cropFamily: 'zingiberaceae',
    tamilName: 'ஏலக்காய்',
    shortDescription:
      'Shade-tolerant tropical rhizome producing the queen of spices; intercropped under forest canopy',
    varieties: ['Small Cardamom', 'Mysore', 'Malabar'],
  },
  {
    name: 'Black Pepper',
    group: 'spices',
    subGroup: 'vine_tree',
    habit: 'vine',
    tags: ['spice', 'coconut_intercrop', 'needs_trellis'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'கருமிளகு',
    shortDescription: 'Climbing spice vine trained on coconut trunks producing the king of spices',
    varieties: ['Panniyur 1', 'Karimunda', 'Local'],
  },
  // Companion-rule plants
  {
    name: 'Fennel',
    group: 'spices',
    subGroup: 'seed_clump',
    habit: 'annual_bed',
    tags: ['spice'],
    plantType: 'herb',
    cropFamily: 'apiaceae',
    tamilName: 'சோம்பு',
    shortDescription:
      'Tall aromatic herb with feathery leaves and anise-flavoured seeds; allelopathic — plant away from most crops',
  },
  // Medicinal guild plants
  {
    name: 'Brahmi',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'perennial',
    tags: ['medicinal'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'பிரம்மி',
    shortDescription:
      'Low-growing medicinal creeper thriving in moist, shaded spots; revered in Ayurveda for cognitive health',
    varieties: ['Water Hyssop', 'Local'],
  },
  {
    name: 'Ashwagandha',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'shrub',
    tags: ['medicinal'],
    plantType: 'herb',
    cropFamily: 'solanaceae',
    tamilName: 'அஷ்வகந்தா',
    shortDescription:
      'Drought-tolerant medicinal shrub producing adaptogenic roots; thrives in sandy well-drained soils',
  },
  {
    name: 'Aloe Vera',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'perennial',
    tags: ['medicinal'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'கற்றாழை',
    shortDescription:
      'Succulent perennial with gel-filled leaves used in medicine, skincare, and soil conditioning',
    varieties: ['Barbadensis', 'Local Green', 'Soap Aloe'],
  },
  // Tamil Nadu homestead medicinals. Filed by use, like Curry Leaf (a
  // tree), Black Pepper (a vine) and Ashwagandha (a shrub) above.
  {
    name: 'Adathodai',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'shrub',
    tags: ['medicinal'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'ஆடாதொடை',
    shortDescription:
      'Hardy medicinal shrub of the Tamil homestead; leaves brewed for coughs and also cut as green-leaf manure',
  },
  {
    name: 'Nithyakalyani',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'shrub',
    tags: ['medicinal', 'puja'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'நித்தியகல்யாணி',
    shortDescription:
      'Tough evergreen flowering year-round on poor soil; self-seeds freely and needs almost no care',
    varieties: ['White', 'Pink', 'Local'],
  },
  {
    name: 'Thoothuvalai',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'vine',
    tags: ['medicinal'],
    plantType: 'herb',
    cropFamily: 'solanaceae',
    tamilName: 'தூதுவளை',
    shortDescription:
      'Scrambling prickly climber of the kitchen doorway, cooked as a cough and cold remedy',
  },
  {
    name: 'Karpooravalli',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'perennial',
    tags: ['medicinal'],
    plantType: 'herb',
    cropFamily: 'lamiaceae',
    tamilName: 'கற்பூரவல்லி',
    shortDescription:
      'Thick-leaved aromatic plant kept by the kitchen door; leaves used fresh for coughs and colds',
    varieties: ['Broad Leaf', 'Variegated', 'Local'],
  },
  // Moved from `shrub`: both are cut for a leaf harvest, one for henna
  // and one for the grain store and the pest spray.
  {
    name: 'Maruthani',
    group: 'farm_support',
    habit: 'shrub',
    tags: ['living_fence'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'மருதாணி',
    shortDescription:
      'The classic Tamil boundary hedge; leaves ground for henna, and it takes hard clipping',
    varieties: ['Broad Leaf', 'Country', 'Local'],
  },
  {
    name: 'Nochi',
    group: 'farm_support',
    habit: 'shrub',
    tags: ['pest_repellent', 'medicinal'],
    plantType: 'herb',
    cropFamily: 'lamiaceae',
    tamilName: 'நொச்சி',
    shortDescription:
      'Aromatic shrub whose leaves are layered into stored grain and steeped as a leaf-extract pest spray',
  },
  // Moved from `shrub`: grown for its leaves and seed cake, both used
  // medicinally and as a pest input, so it is filed by use like the
  // medicinals above rather than by its woody habit.
  {
    name: 'Castor',
    group: 'farm_support',
    habit: 'shrub',
    tags: ['pest_repellent', 'companion', 'oilseed'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'ஆமணக்கு',
    shortDescription:
      'Tall fast-growing shrub with repellent properties; pest-deterrent companion around vegetable beds',
  },
  {
    name: 'Adamant Creeper',
    group: 'herbs_medicinal',
    subGroup: 'medicinal',
    habit: 'vine',
    tags: ['medicinal'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'பிரண்டை',
    shortDescription:
      'Square-stemmed succulent climber; tender tips made into thuvaiyal and pickle. Raw sap irritates skin',
  },
  // Kanyakumari hill spices. Trees, but this is the spice tab — Curry Leaf is
  // a tree and Black Pepper a vine, filed the same way for the same reason.
  {
    name: 'Clove',
    group: 'spices',
    subGroup: 'vine_tree',
    habit: 'tree',
    tags: ['spice'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'கிராம்பு',
    shortDescription:
      'Evergreen hill spice tree harvested for unopened flower buds; wants shade, shelter, and humidity',
    varieties: ['Zanzibar', 'Local'],
  },
  {
    name: 'Cinnamon',
    group: 'spices',
    subGroup: 'vine_tree',
    habit: 'tree',
    tags: ['spice'],
    plantType: 'herb',
    cropFamily: 'other',
    tamilName: 'கருவாப்பட்டை',
    shortDescription:
      'Coppiced spice tree harvested for its inner bark; cut back hard and re-shooted rather than grown tall',
    varieties: ['Sri Lankan', 'Konkan Tej', 'Local'],
  },
  {
    name: 'Mango Ginger',
    group: 'spices',
    subGroup: 'rhizome',
    habit: 'perennial',
    tags: ['spice', 'medicinal'],
    plantType: 'herb',
    cropFamily: 'zingiberaceae',
    tamilName: 'மாஇஞ்சி',
    shortDescription:
      'Raw-mango-scented rhizome of the turmeric family, used fresh in pachadi and pickle',
    varieties: ['Local'],
  },
];
