import type { PlantCatalogEntry } from '../types';

export const TIMBER_TREE_ENTRIES: PlantCatalogEntry[] = [
  {
    name: 'Neem',
    group: 'plantation_timber',
    subGroup: 'timber_utility',
    habit: 'tree',
    tags: ['timber', 'pest_repellent', 'companion', 'medicinal'],
    plantType: 'timber_tree',
    cropFamily: 'other',
    tamilName: 'வேம்பு',
    shortDescription:
      'Fast-growing evergreen valued for pest-repellent properties and durable timber',
  },
  {
    name: 'Teak',
    group: 'plantation_timber',
    subGroup: 'timber_utility',
    habit: 'tree',
    tags: ['timber'],
    plantType: 'timber_tree',
    cropFamily: 'other',
    tamilName: 'தேக்கு',
    shortDescription: 'Premier hardwood timber tree with large deciduous leaves',
  },
  {
    name: 'Mahogany',
    group: 'plantation_timber',
    subGroup: 'timber_utility',
    habit: 'tree',
    tags: ['timber'],
    plantType: 'timber_tree',
    cropFamily: 'other',
    tamilName: 'மகாகனி',
    shortDescription: 'High-value tropical timber with a straight trunk and broad canopy',
  },
  {
    name: 'Rosewood',
    group: 'plantation_timber',
    subGroup: 'timber_utility',
    habit: 'tree',
    tags: ['timber'],
    plantType: 'timber_tree',
    cropFamily: 'other',
    tamilName: 'ரோஸ்வுட்',
    shortDescription: 'Prized hardwood with dark fragrant heartwood, a nitrogen-fixing legume',
  },
  {
    name: 'Sandalwood',
    group: 'plantation_timber',
    subGroup: 'timber_utility',
    habit: 'tree',
    tags: ['timber'],
    plantType: 'timber_tree',
    cropFamily: 'other',
    tamilName: 'சந்தனம்',
    shortDescription: 'Aromatic heartwood tree and hemi-parasite that needs a host plant nearby',
  },
  {
    name: 'Bamboo',
    group: 'plantation_timber',
    subGroup: 'timber_utility',
    habit: 'clump',
    tags: ['timber'],
    plantType: 'timber_tree',
    cropFamily: 'other',
    tamilName: 'மூங்கில்',
    shortDescription: 'Giant clumping grass producing strong culms for construction and crafts',
  },
  {
    name: 'Wild Jack',
    group: 'plantation_timber',
    subGroup: 'timber_utility',
    habit: 'tree',
    tags: ['timber'],
    plantType: 'timber_tree',
    cropFamily: 'other',
    tamilName: 'ஐயன்பலா',
    shortDescription: 'Large evergreen tree native to the Western Ghats yielding durable timber',
  },
];
