import type { PlantCatalogEntry } from '../types';

export const VEGETABLE_ENTRIES: PlantCatalogEntry[] = [
  {
    name: 'Brinjal',
    group: 'vegetables',
    subGroup: 'fruit_vegetables',
    habit: 'annual_bed',
    tags: ['container_ok'],
    plantType: 'vegetable',
    cropFamily: 'solanaceae',
    tamilName: 'கத்தரிக்காய்',
    shortDescription:
      'Versatile tropical nightshade yielding glossy purple fruit for curries and grills',
    varieties: ['Long Purple', 'Round Green', 'Striped', 'Long Brinjal'],
  },
  {
    name: 'Tomato',
    group: 'vegetables',
    subGroup: 'fruit_vegetables',
    habit: 'annual_bed',
    tags: ['container_ok'],
    plantType: 'vegetable',
    cropFamily: 'solanaceae',
    tamilName: 'தக்காளி',
    shortDescription: 'Prolific warm-season fruit used fresh, in sambar, rasam, and chutneys',
    varieties: ['Country Tomato', 'Hybrid Tomato', 'Cherry Tomato'],
  },
  {
    name: 'Chilli',
    group: 'vegetables',
    subGroup: 'fruit_vegetables',
    habit: 'annual_bed',
    tags: ['spice', 'container_ok'],
    plantType: 'vegetable',
    cropFamily: 'solanaceae',
    tamilName: 'மிளகாய்',
    shortDescription: 'Pungent hot pepper central to South Indian spice blends and daily cooking',
    varieties: ["Bird's Eye", 'Gundu', 'Long Chilli'],
  },
  {
    name: 'Tapioca',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'shrub',
    tags: ['tuber'],
    plantType: 'vegetable',
    cropFamily: 'other',
    tamilName: 'மரவள்ளிக்கிழங்கு',
    shortDescription:
      'Starchy root crop grown widely in Kanyakumari for kappa and traditional dishes',
    varieties: ['Mulluvadi', 'CO 2', 'H-165'],
  },
  {
    name: 'Drumstick',
    group: 'vegetables',
    subGroup: 'other',
    habit: 'tree',
    tags: ['keerai', 'companion'],
    plantType: 'vegetable',
    cropFamily: 'other',
    tamilName: 'முருங்கை',
    shortDescription:
      'Fast-growing tropical tree providing nutrient-dense pods, leaves, and flowers',
    varieties: ['PKM 1', 'PKM 2', 'Local'],
  },
  {
    name: 'Cowpea',
    group: 'vegetables',
    subGroup: 'beans_pods',
    habit: 'annual_bed',
    tags: ['pulse'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'காராமணி',
    shortDescription: 'Heat-tolerant nitrogen-fixing legume yielding protein-rich pods and beans',
    varieties: ['Bush', 'Pole', 'Red Cowpea', 'Yardlong Beans'],
  },
  {
    name: 'Beans',
    group: 'vegetables',
    subGroup: 'beans_pods',
    habit: 'vine',
    tags: ['pulse', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'பீன்ஸ்',
    shortDescription: 'Versatile climbing legume producing tender pods for stir-fries and curries',
    varieties: ['Bush Beans', 'Pole Beans', 'Double Beans', 'French Beans'],
  },
  {
    name: 'Bitter Gourd',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'பாகற்காய்',
    shortDescription: 'Warty-skinned climbing cucurbit prized for its medicinal bitter flavour',
    varieties: ['Mithipagal', 'Long Green', 'CO 1'],
  },
  {
    name: 'Snake Gourd',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'புடலங்காய்',
    shortDescription: 'Long striped cucurbit vine producing mild-flavoured gourds for sambar',
    varieties: ['Long White', 'Striped', 'CO 2'],
  },
  {
    name: 'Ridge Gourd',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'பீர்க்கங்காய்',
    shortDescription: 'Ridged climbing vine bearing tender gourds widely used in kootu and poriyal',
    varieties: ['Long Ridge', 'Dark Green', 'CO 1'],
  },
  {
    name: 'Bottle Gourd',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'சுரைக்காய்',
    shortDescription: 'Vigorous trailing vine producing mild watery gourds for kootu and sweets',
    varieties: ['Long Bottle', 'Round Bottle', 'CO 1'],
  },
  {
    name: 'Pumpkin',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'பரங்கிக்காய்',
    shortDescription: 'Sprawling cucurbit yielding large sweet-fleshed fruit for kootu and aviyal',
    varieties: ['Parangikkai', 'CO 2', 'Red Pumpkin'],
  },
  {
    name: 'Ash Gourd',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'வெள்ளைப்பூசணி',
    shortDescription: 'Wax-coated trailing cucurbit used in petha, kootu, and traditional medicine',
    varieties: ['White Ash', 'Long Ash', 'CO 1'],
  },
  {
    name: 'Cucumber',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'வெள்ளரிக்காய்',
    shortDescription: 'Fast-growing warm-season vine producing crisp, refreshing fruits',
    varieties: ['Country Cucumber', 'Hybrid Green', 'Slicing'],
  },
  {
    name: 'Radish',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'annual_bed',
    tags: [],
    plantType: 'vegetable',
    cropFamily: 'brassica',
    tamilName: 'முள்ளங்கி',
    shortDescription: 'One of the fastest-maturing root vegetables, excellent beginner crop',
    varieties: ['Pusa Chetki', 'White Long', 'Pink'],
  },
  {
    name: 'Onion',
    group: 'vegetables',
    subGroup: 'onion_family',
    habit: 'annual_bed',
    tags: [],
    plantType: 'vegetable',
    cropFamily: 'allium',
    tamilName: 'வெங்காயம்',
    shortDescription: 'Essential kitchen staple grown as a bulb crop',
    varieties: ['Bellary', 'Nasik Red', 'CO Onion'],
  },
  {
    name: 'Shallot',
    group: 'vegetables',
    subGroup: 'onion_family',
    habit: 'annual_bed',
    tags: [],
    plantType: 'vegetable',
    cropFamily: 'allium',
    tamilName: 'சின்ன வெங்காயம்',
    shortDescription: 'Small, pungent bulb onion widely used in South Indian cooking',
    varieties: ['Sambar Onion', 'Small Red', 'CO Shallot'],
  },
  {
    name: 'Garlic',
    group: 'vegetables',
    subGroup: 'onion_family',
    habit: 'annual_bed',
    tags: ['spice'],
    plantType: 'vegetable',
    cropFamily: 'allium',
    tamilName: 'பூண்டு',
    shortDescription: 'Pungent bulb with potent medicinal and culinary value',
  },
  {
    name: 'Cabbage',
    group: 'vegetables',
    subGroup: 'cabbage_family',
    habit: 'annual_bed',
    tags: [],
    plantType: 'vegetable',
    cropFamily: 'brassica',
    tamilName: 'முட்டைக்கோஸ்',
    shortDescription: 'Cool-season brassica forming dense leafy heads',
    varieties: ['Golden Acre', 'CO 1', 'Green Ball'],
  },
  {
    name: 'Cauliflower',
    group: 'vegetables',
    subGroup: 'cabbage_family',
    habit: 'annual_bed',
    tags: [],
    plantType: 'vegetable',
    cropFamily: 'brassica',
    tamilName: 'காலிஃபிளவர்',
    shortDescription: 'Cool-season brassica producing compact white curds',
    varieties: ['Pusa Snowball', 'CO 1', 'Early White'],
  },
  {
    name: 'Carrot',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'annual_bed',
    tags: [],
    plantType: 'vegetable',
    cropFamily: 'apiaceae',
    tamilName: 'கேரட்',
    shortDescription: 'Popular root vegetable rich in beta-carotene',
  },
  {
    name: 'Potato',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'annual_bed',
    tags: ['tuber'],
    plantType: 'vegetable',
    cropFamily: 'solanaceae',
    tamilName: 'உருளைக்கிழங்கு',
    shortDescription: 'Versatile tuberous crop grown worldwide',
  },
  {
    // "Pepper" until it was renamed: the Tamil name is குடைமிளகாய் and the care
    // profile's binomial is Capsicum annuum, so the row sat one grep away from
    // Black Pepper (கருமிளகு) meaning something else entirely.
    name: 'Capsicum',
    group: 'vegetables',
    subGroup: 'fruit_vegetables',
    habit: 'annual_bed',
    tags: ['container_ok'],
    plantType: 'vegetable',
    cropFamily: 'solanaceae',
    tamilName: 'குடைமிளகாய்',
    shortDescription: 'Warm-season fruiting plant producing sweet or mildly hot fruits',
  },
  // Kanyakumari root vegetables & tubers
  {
    name: 'Taro',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'perennial',
    tags: ['tuber'],
    plantType: 'vegetable',
    cropFamily: 'araceae',
    tamilName: 'சேப்பங்கிழங்கு',
    shortDescription: 'Tropical tuber crop with edible corms and leaves',
    varieties: ['Seppan Kizhangu', 'White Taro', 'Purple Stem', 'Green Stem', 'Local'],
  },
  {
    name: 'Elephant Yam',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'perennial',
    tags: ['tuber'],
    plantType: 'vegetable',
    cropFamily: 'araceae',
    tamilName: 'கருணைக்கிழங்கு',
    shortDescription: 'Large tropical tuber crop valued in South Indian cuisine',
    varieties: ['Karunai Kizhangu', 'White Yam', 'Local'],
  },
  {
    name: 'Sweet Potato',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'vine',
    tags: ['tuber'],
    plantType: 'vegetable',
    cropFamily: 'convolvulaceae',
    tamilName: 'சர்க்கரைவள்ளிக்கிழங்கு',
    shortDescription: 'Nutritious tropical vine producing sweet tuberous roots',
    varieties: ['Orange Flesh', 'White Flesh', 'Local'],
  },
  {
    name: 'Ladies Finger',
    group: 'vegetables',
    subGroup: 'fruit_vegetables',
    habit: 'annual_bed',
    tags: [],
    plantType: 'vegetable',
    cropFamily: 'malvaceae',
    tamilName: 'வெண்டைக்காய்',
    shortDescription: 'Heat-loving mucilaginous pod vegetable essential in South Indian cooking',
    varieties: ['CO 4', 'CO 5', 'Arka Anamika'],
  },
  // Bed-type plants — fruiting & climbing
  // Bed-type plants — root & legume
  {
    name: 'Beetroot',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'annual_bed',
    tags: [],
    plantType: 'vegetable',
    cropFamily: 'amaranthaceae',
    tamilName: 'பீட்ரூட்',
    shortDescription: 'Jewel-red root vegetable with earthy sweetness, rich in folate and iron',
    varieties: ['Detroit Dark Red', 'Crimson Globe', 'Local Red'],
  },
  {
    name: 'Cluster Beans',
    group: 'vegetables',
    subGroup: 'beans_pods',
    habit: 'annual_bed',
    tags: ['pulse'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'கொத்தவரை',
    shortDescription: 'Heat-tolerant legume yielding slender pods and nitrogen-fixing roots',
    varieties: ['Pusa Navbahar', 'Goma 1', 'Local'],
  },
  {
    name: 'Black Gram',
    group: 'vegetables',
    subGroup: 'pulses_oilseeds_cereals',
    habit: 'annual_bed',
    tags: ['pulse'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'உளுந்து',
    shortDescription:
      'Essential South Indian pulse crop yielding protein-rich seeds for idli and dosa',
    varieties: ['Vamban 6', 'CO 6', 'Local'],
  },
  {
    name: 'Groundnut',
    group: 'vegetables',
    subGroup: 'pulses_oilseeds_cereals',
    habit: 'annual_bed',
    tags: ['pulse', 'oilseed'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'வேர்க்கடலை',
    shortDescription:
      'Nitrogen-fixing oilseed legume producing underground pods rich in protein and fat',
    varieties: ['TMV 2', 'CO 3', 'Local Bunch'],
  },
  {
    name: 'Pigeon Pea',
    group: 'vegetables',
    subGroup: 'pulses_oilseeds_cereals',
    habit: 'perennial',
    tags: ['pulse', 'companion'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'துவரை',
    shortDescription: 'Perennial legume producing protein-rich toor dal; a staple of Tamil cuisine',
    varieties: ['CO 6', 'Vamban 1', 'Local'],
  },
  {
    name: 'Yam',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'vine',
    tags: ['tuber'],
    plantType: 'vegetable',
    cropFamily: 'other',
    tamilName: 'பெருவள்ளிக்கிழங்கு',
    shortDescription:
      'Starchy tropical vine tuber with thick bark; distinct from elephant yam in texture',
  },
  // Bed-type plants — three sisters & grain
  {
    name: 'Maize',
    group: 'vegetables',
    subGroup: 'pulses_oilseeds_cereals',
    habit: 'annual_bed',
    tags: ['cereal', 'companion'],
    plantType: 'vegetable',
    cropFamily: 'poaceae',
    tamilName: 'மக்காச்சோளம்',
    shortDescription:
      'Tall cereal grass forming the structural canopy in Three Sisters polyculture',
    varieties: ['Hybrid Sweet', 'Country Corn', 'CO 1'],
  },
  // Bed-type plants — aquatic
  {
    name: 'Lotus Stem',
    group: 'vegetables',
    subGroup: 'roots_tubers',
    habit: 'aquatic',
    tags: ['tuber'],
    plantType: 'vegetable',
    cropFamily: 'other',
    tamilName: 'தாமரைத்தண்டு',
    shortDescription:
      'Aquatic perennial with crunchy, tunnel-riddled rhizomes used in South Indian cooking',
  },
  // Additional Tamil Nadu warm-season and short cool-season crops
  {
    name: 'Knol Khol',
    group: 'vegetables',
    subGroup: 'cabbage_family',
    habit: 'annual_bed',
    tags: [],
    plantType: 'vegetable',
    cropFamily: 'brassica',
    tamilName: 'நூல்கோல்',
    shortDescription: 'Cool-season brassica grown for its tender swollen stem',
    varieties: ['White Vienna', 'Purple Vienna', 'Local'],
  },
  {
    name: 'Green Peas',
    group: 'vegetables',
    subGroup: 'beans_pods',
    habit: 'vine',
    tags: ['pulse', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'பச்சைப் பட்டாணி',
    shortDescription: 'Short cool-season climbing legume suited to the mildest local months',
    varieties: ['Arkel', 'Bonneville', 'Local'],
  },
  {
    name: 'Lablab Bean',
    group: 'vegetables',
    subGroup: 'beans_pods',
    habit: 'vine',
    tags: ['pulse', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'அவரைக்காய்',
    shortDescription: 'Heat-tolerant perennial bean widely grown as avarai in Tamil Nadu',
    varieties: ['CO 1', 'CO 2', 'Local'],
  },
  {
    name: 'Winged Bean',
    group: 'vegetables',
    subGroup: 'beans_pods',
    habit: 'vine',
    tags: ['pulse', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'சிறகவரை',
    shortDescription:
      'Humid-tropical climbing legume with edible pods, leaves, flowers, and tubers',
    varieties: ['AKWB 1', 'Local Green'],
  },
  {
    name: 'Sword Bean',
    group: 'vegetables',
    subGroup: 'beans_pods',
    habit: 'vine',
    tags: ['pulse', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'legume',
    tamilName: 'வாள் அவரை',
    shortDescription:
      'Vigorous tropical bean suited to fences and trellises; young pods are cooked',
    varieties: ['Bush', 'Climbing', 'Local'],
  },
  {
    name: 'Watermelon',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd', 'fruit'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'தர்பூசணி',
    shortDescription:
      'Warm-season trailing cucurbit requiring drainage and a relatively dry fruiting period',
    varieties: ['Sugar Baby', 'Arka Manik', 'Local'],
  },
  {
    name: 'Muskmelon',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd', 'fruit'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'முலாம்பழம்',
    shortDescription:
      'Warm-season melon performing best with full sun, drainage, and low leaf wetness',
    varieties: ['Pusa Sharbati', 'Hara Madhu', 'Local'],
  },
  // Tamil Nadu homestead staples the catalog had never carried.
  {
    name: 'Ivy Gourd',
    group: 'vegetables',
    subGroup: 'gourds_melons',
    habit: 'vine',
    tags: ['gourd', 'needs_trellis'],
    plantType: 'vegetable',
    cropFamily: 'cucurbit',
    tamilName: 'கோவைக்காய்',
    shortDescription:
      'Perennial pandal vine grown from cuttings; crops for years with almost no replanting',
    varieties: ['Sulabha', 'CO 1', 'Local Green'],
  },
  {
    name: 'Turkey Berry',
    group: 'vegetables',
    subGroup: 'fruit_vegetables',
    habit: 'shrub',
    tags: ['medicinal'],
    plantType: 'vegetable',
    cropFamily: 'solanaceae',
    tamilName: 'சுண்டைக்காய்',
    shortDescription:
      'Hardy perennial bearing clustered green berries for sundakkai vathal and kuzhambu',
    varieties: ['Local'],
  },
  {
    name: 'Sesame',
    group: 'vegetables',
    subGroup: 'pulses_oilseeds_cereals',
    habit: 'annual_bed',
    tags: ['oilseed'],
    plantType: 'vegetable',
    cropFamily: 'other',
    tamilName: 'எள்ளு',
    shortDescription:
      'Short-duration oilseed for gingelly oil and ellu urundai; tolerates poor, dry soil',
    varieties: ['TMV 7', 'CO 1', 'VRI 1'],
  },
];
