import { PlantType, PlantCareProfile } from '@/types/database.types';

export const DEFAULT_PROFILES_BY_TYPE: Record<PlantType, PlantCareProfile> = {
  vegetable: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 14,
    pruningFrequencyDays: 21,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    growthStageDurations: { seedling: 18, vegetative: 25, flowering: 15, fruiting: 22 },
  },
  herb: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 21,
    sunlight: 'partial_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    growthStageDurations: { seedling: 14, vegetative: 30, mature: 16 },
  },
  flower: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 3,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 30,
    sunlight: 'full_sun',
    soilType: 'potting_mix',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    growthStageDurations: { seedling: 14, vegetative: 30, flowering: 25 },
  },
  fruit_tree: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    growthStageDurations: { seedling: 150, vegetative: 1310 },
    annualCycleDurations: { flowering: 45, fruiting: 120, dormant: 200 },
    floweringStartMonth: 2,
    // Required for the annual cycle to activate — without it, non-catalog
    // varieties would stay "vegetative" forever.
    yearsToFirstHarvest: 4,
  },
  timber_tree: {
    waterRequirement: 'low',
    wateringFrequencyDays: 10,
    fertilisingFrequencyDays: 90,
    pruningFrequencyDays: 365,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    growthStageDurations: { seedling: 150, vegetative: 1460, mature: 730 },
  },
  coconut_tree: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 75,
    pruningFrequencyDays: 180,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'vermicompost',
    initialGrowthStage: 'vegetative',
    // Coconut growth stages handled by getCoconutAgeInfo() — no durations here
  },
  shrub: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 5,
    fertilisingFrequencyDays: 45,
    pruningFrequencyDays: 60,
    sunlight: 'full_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'vegetative',
    growthStageDurations: { seedling: 35, vegetative: 100, flowering: 45, mature: 65 },
  },
  spinach: {
    waterRequirement: 'medium',
    wateringFrequencyDays: 2,
    fertilisingFrequencyDays: 21,
    pruningFrequencyDays: 14,
    sunlight: 'partial_sun',
    soilType: 'garden_soil',
    preferredFertiliser: 'compost',
    initialGrowthStage: 'seedling',
    growthStageDurations: { seedling: 10, vegetative: 20, mature: 10 },
  },
};
