import { PlantType } from '@/types/database.types';

export const PLANT_VARIETIES_BY_TYPE: Record<PlantType, string[]> = {
  vegetable: [
    'Brinjal',
    'Long Brinjal',
    'Ladies Finger',
    'Tomato',
    'Chilli',
    'Tapioca',
    'Drumstick',
    'Amaranthus',
    'Cowpea',
    'Beans',
    'Bitter Gourd',
    'Snake Gourd',
    'Ridge Gourd',
    'Bottle Gourd',
    'Pumpkin',
    'Ash Gourd',
    'Cucumber',
    'Radish',
    'Onion',
    'Shallot',
    'Garlic',
    'Cabbage',
    'Cauliflower',
    'Carrot',
    'Potato',
    'Pepper',
    // Kanyakumari root vegetables & tubers
    'Taro',
    'Elephant Yam',
    'Sweet Potato',
    'Ash Plantain',
    // Bed-type plants
    'Lettuce',
    'Purslane',
    'Pasalai Keerai',
    'Fenugreek',
    'Squash',
    'Yardlong Beans',
    'Beetroot',
    'French Beans',
    'Cluster Beans',
    'Black Gram',
    'Groundnut',
    'Pigeon Pea',
    'Yam',
    'Maize',
    'Lotus Stem',
    'Strawberry',
    'Turnip',
    'Knol Khol',
    'Green Peas',
    'Lablab Bean',
    'Winged Bean',
    'Sword Bean',
    'Watermelon',
    'Muskmelon',
  ],
  herb: [
    'Coriander',
    'Mint',
    'Curry Leaf',
    'Lemongrass',
    'Tulsi',
    'Basil',
    'Dill',
    'Parsley',
    'Rosemary',
    'Thyme',
    'Oregano',
    // Kanyakumari spices grown as herbs
    'Turmeric',
    'Ginger',
    'Betel Leaf',
    // Spice bed plants
    'Ajwain',
    'Cardamom',
    'Black Pepper',
    // Companion-rule plants
    'Fennel',
    'Sage',
    // Medicinal guild plants
    'Brahmi',
    'Ashwagandha',
    'Aloe Vera',
  ],
  flower: [
    'Marigold',
    'Jasmine',
    'Hibiscus',
    'Rose',
    'Chrysanthemum',
    'Crossandra',
    'Ixora',
    'Sunflower',
    'Dahlia',
    'Orchid',
  ],
  fruit_tree: [
    'Banana',
    'Mango',
    'Guava',
    'Papaya',
    'Lemon',
    'Pomegranate',
    'Jackfruit',
    'Chikoo',
    'Water Apple',
    'Custard Apple',
    'Amla',
    'Orange',
    'Fig',
    'Avocado',
    'Soursop',
    'Mangosteen',
    'Rambutan',
    // Kanyakumari-specific fruit trees
    'Red Banana',
    'Breadfruit',
    'Pineapple',
    'Passion Fruit',
    'Star Fruit',
    'Arecanut',
    // Coconut intercrop trees
    'Cocoa',
    'Nutmeg',
  ],
  timber_tree: ['Neem', 'Teak', 'Mahogany', 'Rosewood', 'Sandalwood', 'Bamboo', 'Wild Jack'],
  coconut_tree: ['Dwarf Coconut', 'Tall Coconut', 'Hybrid Coconut', 'King Coconut'],
  shrub: [
    'Hibiscus',
    'Ixora',
    'Nandiyavattai',
    'Bougainvillea',
    'Jasmine',
    'Agathi',
    'Castor',
    'Coleus',
    'Crossandra',
    'Lantana',
    'Gardenia',
  ],
  spinach: [
    'Palak',
    'Malabar Spinach',
    'Water Spinach',
    'Amaranth Greens',
    'Ponnanganni Keerai',
    'Manathakkali Keerai',
    'Mustard Greens',
    'Vallarai Keerai',
  ],
};
