import { PlantType } from '@/types/database.types';

export const PLANT_VARIETIES_BY_TYPE: Record<PlantType, string[]> = {
  vegetable: [
    'Brinjal',
    'Long Brinjal',
    'Ladies Finger',
    'Tomato',
    'Chilli',
    'Tapioca',
    'Drumstick',
    'Cowpea',
    'Beans',
    'Bitter Gourd',
    'Snake Gourd',
    'Ridge Gourd',
    'Bottle Gourd',
    'Pumpkin',
    'Ash Gourd',
    'Cucumber',
    'Radish',
    'Onion',
    'Shallot',
    'Garlic',
    'Cabbage',
    'Cauliflower',
    'Carrot',
    'Potato',
    'Pepper',
    // Kanyakumari root vegetables & tubers
    'Taro',
    'Elephant Yam',
    'Sweet Potato',
    'Ash Plantain',
    // Bed-type plants
    'Yardlong Beans',
    'Beetroot',
    'French Beans',
    'Cluster Beans',
    'Black Gram',
    'Groundnut',
    'Pigeon Pea',
    'Yam',
    'Maize',
    'Lotus Stem',
    'Knol Khol',
    'Green Peas',
    'Lablab Bean',
    'Winged Bean',
    'Sword Bean',
    'Watermelon',
    'Muskmelon',
  ],
  herb: [
    'Coriander',
    'Mint',
    'Curry Leaf',
    'Lemongrass',
    'Tulsi',
    'Basil',
    'Dill',
    // Kanyakumari spices grown as herbs
    'Turmeric',
    'Ginger',
    'Betel Leaf',
    // Spice bed plants
    'Ajwain',
    'Cardamom',
    'Black Pepper',
    // Companion-rule plants
    'Fennel',
    // Medicinal guild plants
    'Brahmi',
    'Ashwagandha',
    'Aloe Vera',
    // Tamil Nadu homestead medicinals, filed by use rather than growth habit
    'Adathodai',
    'Nithyakalyani',
    'Thoothuvalai',
    'Karpooravalli',
    // Moved from `shrub`: cut for a leaf harvest, so filed with the herbs
    'Maruthani',
    'Nochi',
  ],
  flower: [
    'Marigold',
    'Jasmine',
    'Hibiscus',
    'Rose',
    'Chrysanthemum',
    'Crossandra',
    'Ixora',
    'Sunflower',
    // Moved from `shrub`: woody, but grown for the bloom
    'Nandiyavattai',
    'Aavaram',
    'Arali',
  ],
  fruit_tree: [
    'Banana',
    'Mango',
    'Guava',
    'Papaya',
    'Lemon',
    'Pomegranate',
    'Jackfruit',
    'Chikoo',
    'Water Apple',
    'Custard Apple',
    'Amla',
    'Orange',
    'Fig',
    'Avocado',
    'Soursop',
    'Mangosteen',
    'Rambutan',
    // Kanyakumari-specific fruit trees
    'Red Banana',
    'Breadfruit',
    'Pineapple',
    'Passion Fruit',
    'Star Fruit',
    'Arecanut',
    // Coconut intercrop trees
    'Cocoa',
    'Nutmeg',
  ],
  timber_tree: ['Neem', 'Teak', 'Mahogany', 'Rosewood', 'Sandalwood', 'Bamboo', 'Wild Jack'],
  coconut_tree: ['Dwarf Coconut', 'Tall Coconut', 'Hybrid Coconut', 'King Coconut'],
  // Only the woody perennials grown for the plant itself; everything cut for a
  // leaf or a flower is filed under that harvest instead.
  shrub: ['Bougainvillea', 'Castor'],
  spinach: [
    'Palak',
    'Water Spinach',
    'Ponnanganni Keerai',
    'Manathakkali Keerai',
    'Mustard Greens',
    'Vallarai Keerai',
    'Purslane',
    'Amaranthus',
    'Pasalai Keerai',
    'Fenugreek',
    // Moved from `shrub`: agathi keerai is a keerai
    'Agathi',
  ],
};
